# Generated by Django 4.2.13 on 2026-03-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_remove_question_answer_models'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
