# Generated by Django 5.2.8 on 2026-06-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('script_type', models.CharField(choices=[('latin', 'Latin'), ('sinhala', 'Sinhala'), ('tamil', 'Tamil'), ('devanagari', 'Devanagari'), ('arabic', 'Arabic'), ('cjk', 'CJK')], default='latin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('letter_writing', 'Letter Writing'), ('phonics_mcq', 'Phonics MCQ'), ('spelling_mcq', 'Spelling MCQ'), ('spelling_type', 'Spelling — Type Answer'), ('crossword', 'Crossword'), ('grammar_fill_blank', 'Grammar Fill-in-the-Blank'), ('sentence_order', 'Sentence Ordering'), ('advanced_crossword', 'Advanced Crossword')], max_length=30)),
                ('prompt', models.TextField()),
                ('media_url', models.URLField(blank=True)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['topic_level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LanguageAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='languages.languageexercise')),
            ],
            options={
                'ordering': ['exercise', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='LanguageTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='languages.language')),
            ],
            options={
                'ordering': ['language', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageTopicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_choice', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='languages.languagetopic')),
            ],
            options={
                'ordering': ['topic', 'level_choice'],
                'unique_together': {('topic', 'level_choice')},
            },
        ),
        migrations.AddField(
            model_name='languageexercise',
            name='topic_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='languages.languagetopiclevel'),
        ),
        migrations.CreateModel(
            name='LanguageStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='languages.languageexercise')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.languageanswer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answered_at'],
                'unique_together': {('student', 'exercise')},
            },
        ),
    ]
