# Generated by Django 5.2.8 on 2026-06-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagestudentanswer',
            name='stroke_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
