# Generated by Django 5.2.8 on 2026-06-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_cpp310_stroke_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagestudentanswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='languages.languageanswer'),
        ),
    ]
