# Generated by Django 5.2.8 on 2026-06-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_cpp310_selected_answer_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagestudentanswer',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
