# Generated by Django 5.2.8 on 2026-06-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_cpp316_language_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagestudentanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
