# Generated by Django 4.2.13 on 2026-09-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0011_case_accent_sensitive_prompt_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='script_type',
            field=models.CharField(choices=[('latin', 'Latin'), ('sinhala', 'Sinhala'), ('tamil', 'Tamil'), ('devanagari', 'Devanagari'), ('arabic', 'Arabic'), ('cjk', 'CJK'), ('kana', 'Kana')], default='latin', max_length=20),
        ),
    ]
