# Generated by Django 4.2.13 on 2026-09-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0012_alter_language_script_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='script_type',
            field=models.CharField(choices=[('latin', 'Latin'), ('sinhala', 'Sinhala'), ('tamil', 'Tamil'), ('devanagari', 'Devanagari'), ('arabic', 'Arabic'), ('cjk', 'CJK'), ('kana', 'Kana'), ('hangul', 'Hangul')], default='latin', max_length=20),
        ),
    ]
