# Generated by Django 4.2.13 on 2026-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="jira_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Key of the Jira issue auto-created for this bug (e.g. CPP-123). Used for traceability and to dedupe re-reports.",
                max_length=30,
            ),
        ),
    ]
