# Generated by Django 4.2.13 on 2026-07-06 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_jira_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedback_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feedback.feedback')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
