# Generated by Django 4.2.13 on 2026-03-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block_type',
            field=models.CharField(blank=True, choices=[('', 'Not blocked'), ('payment', 'Payment overdue'), ('manual', 'Manual block'), ('policy', 'Policy violation')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
