# Generated by Django 4.2.13 on 2026-03-24 23:58
# Amended: depends on 0003_account_blocking to avoid duplicate column error.
# block_type and is_blocked are already added by 0003_account_blocking.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_blocking'),
    ]

    operations = [
        # block_type and is_blocked already exist from 0003_account_blocking.
        # This migration is kept as a no-op to preserve the migration history.
    ]
