# Generated by Django 4.2.13 on 2026-03-25 02:28
# Amended: must_change_password already added by 0004_add_profile_completion_fields.
# Depends on both 0004 branches so the merge (0006) remains valid.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_block_fields'),
        ('accounts', '0004_add_profile_completion_fields'),
    ]

    operations = [
        # must_change_password already exists from 0004_add_profile_completion_fields.
        # This migration is kept as a no-op to preserve the migration history.
    ]
