# Generated by Django 4.2.13 on 2026-03-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_must_change_password'),
        ('accounts', '0005_add_user_address_fields'),
    ]

    operations = [
    ]
