# Generated by Django 4.2.13 on 2026-03-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260325_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='block_type',
            field=models.CharField(blank=True, choices=[('', 'Not blocked'), ('payment', 'Payment overdue'), ('manual', 'Manual block'), ('policy', 'Policy violation'), ('temporary', 'Temporary'), ('permanent', 'Permanent')], default='', max_length=20),
        ),
    ]
