# Generated by Django 4.2.13 on 2026-04-07 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html-css', 'HTML / CSS'), ('scratch', 'Scratch')], unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier used in templates', max_length=50)),
                ('color', models.CharField(blank=True, help_text="Tailwind color class, e.g. 'blue-500'", max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Full problem statement shown to the student, including input/output format')),
                ('starter_code', models.TextField(blank=True, help_text='Skeleton code to give students a starting point')),
                ('solution_code', models.TextField(blank=True, help_text='Reference solution — never exposed to students')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='Difficulty level 1 (easiest) to 8 (hardest)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='coding.codinglanguage')),
            ],
            options={
                'ordering': ['language', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CodingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='coding.codinglanguage')),
            ],
            options={
                'ordering': ['language', 'order', 'name'],
                'unique_together': {('language', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProblemTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, help_text="stdin passed to the student's program (leave blank if no input needed)")),
                ('expected_output', models.TextField(help_text='Expected stdout (stripped of trailing whitespace during comparison)')),
                ('is_visible', models.BooleanField(default=True, help_text='True = shown to student as a sample. False = hidden boundary/edge case.')),
                ('description', models.CharField(blank=True, help_text="Short label, e.g. 'Empty list input'", max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='coding.codingproblem')),
            ],
            options={
                'ordering': ['problem', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_total_seconds', models.PositiveIntegerField(default=0)),
                ('weekly_total_seconds', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now=True)),
                ('last_reset_week', models.IntegerField(default=0, help_text='ISO week number of last weekly reset')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_time_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='CodingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Instructions shown to the student')),
                ('starter_code', models.TextField(blank=True, help_text='Pre-filled code shown in the editor when the student opens the exercise')),
                ('solution_code', models.TextField(blank=True, help_text='Reference solution — shown only to teachers, never to students')),
                ('expected_output', models.TextField(blank=True, help_text='Expected stdout for simple output-matching exercises (leave blank for free-form exercises)')),
                ('hints', models.TextField(blank=True, help_text='Optional hint text shown on request')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='coding.codingtopic')),
            ],
            options={
                'ordering': ['topic', 'level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentProblemSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default=uuid.uuid4, help_text='Unique identifier for this submission session', max_length=100)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Attempt number for this student-problem combination')),
                ('code_submitted', models.TextField()),
                ('passed_all_tests', models.BooleanField(default=False, help_text='True only when every test case (visible + hidden) passes')),
                ('visible_passed', models.PositiveSmallIntegerField(default=0, help_text='Number of visible test cases passed')),
                ('visible_total', models.PositiveSmallIntegerField(default=0)),
                ('hidden_passed', models.PositiveSmallIntegerField(default=0, help_text='Number of hidden test cases passed')),
                ('hidden_total', models.PositiveSmallIntegerField(default=0)),
                ('test_results', models.JSONField(blank=True, default=list, help_text='List of dicts: {test_case_id, is_visible, passed, actual_output, expected_output}. actual_output is only stored for visible test cases.')),
                ('points', models.FloatField(default=0.0, help_text='Points awarded based on tests passed and time taken')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, help_text='Time from opening problem to submission')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingproblem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problem_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['student', 'problem'], name='coding_sps_stu_prob_idx'), models.Index(fields=['student', 'problem', 'attempt_number'], name='coding_sps_stu_prob_att_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_submitted', models.TextField()),
                ('output_received', models.TextField(blank=True, help_text='stdout returned by the code executor')),
                ('stderr_received', models.TextField(blank=True, help_text='stderr returned by the code executor')),
                ('is_completed', models.BooleanField(default=False, help_text='True once the student marks the exercise as done or output matches expected')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on this submission in seconds')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_exercise_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['student', 'exercise'], name='coding_ses_stu_ex_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodingTopicStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('average_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sigma', models.DecimalField(decimal_places=2, default=0, help_text='Standard deviation', max_digits=10)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='coding.codingtopic')),
            ],
            options={
                'ordering': ['topic', 'level'],
                'indexes': [models.Index(fields=['topic', 'level'], name='coding_cts_topic_level_idx')],
                'unique_together': {('topic', 'level')},
            },
        ),
    ]
