# Generated by Django 5.2.8 on 2026-04-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='category',
            field=models.CharField(choices=[('algorithm', 'Algorithm'), ('logic', 'Logic'), ('string', 'String'), ('math', 'Math'), ('data-structures', 'Data Structures'), ('other', 'Other')], default='other', help_text='Problem category (Algorithm, Logic, String, Math, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='constraints',
            field=models.TextField(blank=True, help_text="Constraints shown to the student, e.g. '1 ≤ n ≤ 10^5, values are integers'"),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='memory_limit_mb',
            field=models.PositiveSmallIntegerField(default=64, help_text='Memory limit per test case in megabytes'),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(default=10, help_text='Execution time limit per test case in seconds'),
        ),
        migrations.AddField(
            model_name='problemtestcase',
            name='is_boundary_test',
            field=models.BooleanField(default=False, help_text='True for edge/boundary value tests (e.g. empty input, max value). Always hidden.'),
        ),
        migrations.AddField(
            model_name='studentproblemsubmission',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Language the student used for this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_submissions', to='coding.codinglanguage'),
        ),
        migrations.AddField(
            model_name='studentproblemsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', help_text='Submission status: Pending (being evaluated), Passed, or Failed', max_length=10),
        ),
        migrations.CreateModel(
            name='ProblemSubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_output', models.TextField(blank=True, help_text="stdout produced by the student's code for this test case")),
                ('is_passed', models.BooleanField(default=False, help_text='True when actual_output matches expected_output')),
                ('execution_time_ms', models.PositiveIntegerField(default=0, help_text='Wall-clock time taken to execute this test case in milliseconds')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='coding.studentproblemsubmission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_results', to='coding.problemtestcase')),
            ],
            options={
                'ordering': ['submission', 'test_case__order', 'test_case__id'],
                'indexes': [models.Index(fields=['submission'], name='coding_psr_submission_idx')],
                'unique_together': {('submission', 'test_case')},
            },
        ),
    ]
