# Generated by Django 5.2.8 on 2026-04-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_auto_add_codingproblem_fields'),
        ('coding', '0005_problem_solving_schema'),
    ]

    operations = [
    ]
