# Generated by Django 5.2.8 on 2026-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_merge_20260409_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codingproblem',
            options={'ordering': ['difficulty', 'title']},
        ),
        migrations.AlterModelOptions(
            name='problemtestcase',
            options={'ordering': ['problem', 'display_order', 'id']},
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='description',
            field=models.CharField(blank=True, help_text="Short label, e.g. 'Empty list input' or 'Maximum constraint'", max_length=200),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Controls the order test cases are displayed / run'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='True = shown to student as a sample case. False = hidden boundary/edge case.'),
        ),
    ]
