# Generated by Django 5.2.8 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_alter_codingproblem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='forbidden_code_patterns',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "List of forbidden source-code substrings for this problem, e.g. "
                    "['sorted(', '.sort('] for Bubble Sort. A submission containing any "
                    "forbidden pattern fails immediately with zero points."
                ),
            ),
        ),
    ]
