# Generated by Django 5.2.8 on 2026-04-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0011_seed_coding_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingexercise',
            name='uses_browser_sandbox',
            field=models.BooleanField(default=False, help_text='Override execution environment for this exercise. When True, the editor renders an iframe sandbox instead of sending code to Piston. Use for DOM/HTML-in-JS exercises that belong to a non-browser language topic (e.g. JavaScript DOM Basics).'),
        ),
        migrations.AlterField(
            model_name='topiclevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
