# Generated by Django 4.2.13 on 2026-04-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0012_add_exercise_uses_browser_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingexercise',
            name='required_code_patterns',
            field=models.TextField(blank=True, help_text="Optional. One regular expression per line. ALL patterns must match the student's submitted code (re.search) before the exercise can be marked correct. Use this to stop students bypassing the exercise intent — e.g. require `name\\s*=` so they cannot just print the expected output literally.", null=True),
        ),
    ]
