# Generated by Django 5.2.8 on 2026-04-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0014_codinganswer_timestamps_exercise_shortanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingexercise',
            name='question_type',
            field=models.CharField(choices=[('write_code', 'Write Code'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank')], default='write_code', help_text='write_code (default) keeps existing behaviour. Other types expose MCQ/TF/short-answer options via CodingAnswer and allow the exercise to be used in BrainBuzz sessions.', max_length=20),
        ),
    ]
