# Generated by Django 5.2.8 on 2026-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0013_codingexercise_required_code_patterns'),
        ('coding', '0016_add_coding_exercise_visibility'),
    ]

    operations = [
    ]
