# Generated by Django 4.2.13 on 2026-02-28 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_seconds', models.PositiveIntegerField(default=0)),
                ('weekly_seconds', models.PositiveIntegerField(default=0)),
                ('last_daily_reset', models.DateField(blank=True, null=True)),
                ('last_weekly_reset', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicLevelStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_points', models.FloatField(default=0.0)),
                ('sigma', models.FloatField(default=0.0)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='classroom.level')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='classroom.topic')),
            ],
            options={
                'unique_together': {('topic', 'level')},
            },
        ),
        migrations.CreateModel(
            name='StudentFinalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('topic', 'Topic Quiz'), ('mixed', 'Mixed Quiz'), ('times_table', 'Times Table')], default='topic', max_length=20)),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('points', models.FloatField(default=0.0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_answers', to='classroom.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_answers', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_answers', to='classroom.topic')),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['student', 'topic', 'level'], name='progress_st_student_79a4f4_idx'), models.Index(fields=['session_id'], name='progress_st_session_e1a942_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('ordered_answer_ids', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt_id', models.UUIDField(default=uuid.uuid4)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='classroom.level')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='quiz.question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='quiz.answer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(help_text='Stored explicitly to enable per-topic breakdown in Mixed Quiz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='classroom.topic')),
            ],
            options={
                'ordering': ['-answered_at'],
                'indexes': [models.Index(fields=['student', 'topic', 'level'], name='progress_st_student_c7985e_idx'), models.Index(fields=['attempt_id'], name='progress_st_attempt_1d7906_idx')],
            },
        ),
        migrations.CreateModel(
            name='BasicFactsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(choices=[('Addition', 'Addition'), ('Subtraction', 'Subtraction'), ('Multiplication', 'Multiplication'), ('Division', 'Division'), ('PlaceValue', 'Place Value Facts')], max_length=20)),
                ('level_number', models.PositiveIntegerField()),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=10)),
                ('points', models.FloatField(default=0.0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('questions_data', models.JSONField(default=list, help_text='Stores generated questions + student answers for review.')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_facts_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['student', 'subtopic', 'level_number'], name='progress_ba_student_12715c_idx')],
            },
        ),
    ]
