# Generated by Django 4.2.13 on 2026-03-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        # Delete models directly — field-by-field removal fails on SQLite
        # due to index rebuild referencing removed fields.
        migrations.DeleteModel(
            name='BasicFactsResult',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
        migrations.AlterUniqueTogether(
            name='topiclevelstatistics',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='TopicLevelStatistics',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='StudentFinalAnswer',
        ),
    ]
