# Generated by Django 4.2.13 on 2026-03-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinalanswer',
            name='operation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
