# Generated by Django 4.2.13 on 2026-03-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='studentfinalanswer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentfinalanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentfinalanswer',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='topiclevelstatistics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topiclevelstatistics',
            name='level',
        ),
        migrations.RemoveField(
            model_name='topiclevelstatistics',
            name='topic',
        ),
        migrations.DeleteModel(
            name='BasicFactsResult',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='StudentFinalAnswer',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
        migrations.DeleteModel(
            name='TopicLevelStatistics',
        ),
    ]
