# Generated by Django 4.2.13 on 2026-08-23 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classroom", "0117_school_free_ai_grading"),
        ("progress", "0002_remove_question_answer_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("term", "Term"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Frozen snapshot: totals, topics, attempts, trend, awards.",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the in-app notification went to the student and parents.",
                        null=True,
                    ),
                ),
                (
                    "parent_emailed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the end-of-term email went to the parents. Term reports only.",
                        null=True,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_reports",
                        to="classroom.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set on term reports; null on weekly/monthly ones.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_reports",
                        to="classroom.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "period_type"],
                "indexes": [
                    models.Index(
                        fields=["student", "period_type", "-period_start"],
                        name="progress_pe_student_f7631e_idx",
                    )
                ],
                "unique_together": {("student", "period_type", "period_start")},
            },
        ),
    ]
