# Generated by Django 4.2.13 on 2026-08-24 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classroom", "0117_school_free_ai_grading"),
        ("progress", "0003_periodreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressReportSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekly", models.BooleanField(blank=True, null=True)),
                ("monthly", models.BooleanField(blank=True, null=True)),
                ("term", models.BooleanField(blank=True, null=True)),
                ("notify_student", models.BooleanField(blank=True, null=True)),
                ("notify_parents", models.BooleanField(blank=True, null=True)),
                ("email_parents_at_term", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for a single class. Null = department/school-level.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_report_settings",
                        to="classroom.classroom",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for a department-level rule. Null = school-level.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_report_settings",
                        to="classroom.department",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_report_settings",
                        to="classroom.school",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["school", "department", "classroom"],
            },
        ),
        migrations.AddConstraint(
            model_name="progressreportsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("classroom__isnull", True), ("department__isnull", True)
                ),
                fields=("school",),
                name="unique_progress_setting_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="progressreportsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("classroom__isnull", True), ("department__isnull", False)
                ),
                fields=("department",),
                name="unique_progress_setting_department",
            ),
        ),
        migrations.AddConstraint(
            model_name="progressreportsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("classroom__isnull", False)),
                fields=("classroom",),
                name="unique_progress_setting_classroom",
            ),
        ),
    ]
