# Generated by Django 4.2.13 on 2026-08-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0004_progressreportsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressreportsetting",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual — staff review and send"),
                    ("auto", "Automatic — send on the scheduled day"),
                ],
                help_text="Null = inherit. An unset chain resolves to manual.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="send_monthly_on",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Day of month for the monthly run (1–28). Capped at 28 so the run exists in February; a "31st" schedule would skip four months a year.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="send_term_after_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Days after a term ends before its report is sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="send_weekly_on",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of week for the weekly run: 0=Monday … 6=Sunday.",
                null=True,
            ),
        ),
    ]
