# Generated by Django 4.2.13 on 2026-08-28 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classroom", "0120_repair_classroom_subject"),
        ("progress", "0005_report_mode_and_schedule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="periodreport",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="periodreport",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text='The subject this report covers. Null only on pre-CPP-395 rows that have not been split yet — here null means "legacy", not "inherit".',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="period_reports",
                to="classroom.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="periodreport",
            unique_together={("student", "period_type", "period_start", "subject")},
        ),
    ]
