# Generated by Django 4.2.13 on 2026-08-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0006_alter_periodreport_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_awards",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_homework",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_practice",
            field=models.BooleanField(
                blank=True,
                help_text="Quizzes, times tables and basic facts. Maths reports only — a setting cannot make a times table part of a coding report.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_rubric",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_teacher_comment",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_topics",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_worksheets",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
