# Generated by Django 4.2.13 on 2026-08-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0007_progressreportsetting_include_awards_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progressreportsetting",
            name="include_practice",
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_basic_facts",
            field=models.BooleanField(
                blank=True,
                help_text="Basic facts. Maths only by nature, as above.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_quizzes",
            field=models.BooleanField(
                blank=True,
                help_text="Quizzes, resolved per subject: a maths report carries maths quizzes, a coding report carries coding quizzes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_times_tables",
            field=models.BooleanField(
                blank=True,
                help_text="Times tables. Maths only by nature — a setting cannot make a times table part of a coding report.",
                null=True,
            ),
        ),
    ]
