# Generated by Django 4.2.13 on 2026-08-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0008_remove_progressreportsetting_include_practice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_subject_practice",
            field=models.BooleanField(
                blank=True,
                help_text="Practice a student did in the subject's own app rather than as homework — coding exercises and problems. Each subject supplies its own; a subject with none shows no section.",
                null=True,
            ),
        ),
    ]
