# Generated by Django 4.2.13 on 2026-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0009_progressreportsetting_include_subject_practice"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressreportsetting",
            name="include_next_steps",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
