# Generated by Django 4.2.13 on 2026-09-14 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classroom", "0121_topic_alias"),
        ("progress", "0010_next_steps_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressreportsetting",
            name="email_parents_no_data",
            field=models.BooleanField(
                blank=True,
                help_text="Email the parents when there is nothing to show, saying why — no active subscription, or no work done this period. Defaults on once whole_school is on. School-level setting.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressreportsetting",
            name="whole_school",
            field=models.BooleanField(
                blank=True,
                help_text="Cover every active student in the school, not only those in a class with the report switched on, and not only subscribed ones. School-level setting. Null = inherit; an unset chain is off.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PeriodReportNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("term", "Term"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("no_subscription", "No active subscription"),
                            ("no_activity", "Subscribed, but nothing done this period"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipients", models.PositiveSmallIntegerField(default=0)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_report_notices",
                        to="classroom.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_report_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "period_type"],
                "indexes": [
                    models.Index(
                        fields=["school", "period_type", "-period_start"],
                        name="progress_pe_school__102371_idx",
                    )
                ],
                "unique_together": {("student", "period_type", "period_start")},
            },
        ),
    ]
