# Generated by Django 4.2.13 on 2026-03-20 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0060_school_suspension'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('billing', 'Billing'), ('entitlement', 'Entitlement'), ('admin_action', 'Admin Action'), ('data_change', 'Data Change')], max_length=30)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('result', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked')], default='allowed', max_length=10)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='classroom.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='audit_audit_user_id_40970d_idx'), models.Index(fields=['school', 'category'], name='audit_audit_school__03b5be_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['category', 'result', 'created_at'], name='audit_audit_categor_1e2aa2_idx')],
            },
        ),
    ]
