# Generated by Django 4.2.13 on 2026-03-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_audit_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
