#!/usr/bin/env python3
"""
Generate Year 9 maths question import files (JSON + ZIP per topic).

Source: a set of Year 9 maths exam / worksheet PDFs supplied by the user
(half-yearly and term exams with solutions, Master Maths linear-relations
worksheets, surds and number skillsheets, a trigonometry workbook, NAPLAN
practice, and a rational-expressions booklet).  Every answer was either
cross-checked against the PDF's own answer key, computed independently,
or both.  Questions that depend on a diagram/graph/grid, or whose maths
symbols were lost in PDF extraction, were skipped — see README.md.

Output format matches MathsQuestionParser in
cwa_classroom/classroom/upload_services.py:
  - one <topic>.json per topic
  - one <topic>.zip per topic containing a single file `questions.json`
  - every question is multiple_choice with exactly one correct answer
  - `order` is 1-based (the parser treats order 0 as falsy)

Run from anywhere:  python imports/year9/_generate.py
"""

import io
import json
import random
import re
import sys
import zipfile
from fractions import Fraction
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent
IMAGES_DIR = OUT_DIR / 'images'
YEAR_LEVEL = 9


def q(text, correct, wrong, explanation, difficulty=2, points=1, image=None):
    """Build one question dict. `correct` is the single right answer,
    `wrong` is a list of 3 distractors (none mathematically equal).
    `image` is an optional filename in images/ shown with the question
    (cropped from, or drawn to match, the source PDF figure)."""
    return {
        "question_text": text,
        "difficulty": difficulty,
        "points": points,
        "explanation": explanation,
        "correct": correct,
        "wrong": list(wrong),
        "image": image,
    }


# ---------------------------------------------------------------------------
# Question bank: one entry per topic.
# ---------------------------------------------------------------------------

BANK = [
    {
        "strand": "Number",
        "topic": "Surds",
        "questions": [
            q("Which of the following is a pair of like surds?",
              "-√6 and 4√6",
              ["√2 and √7", "11 and √11", "3√2 and 3√6"],
              "Like surds have the same number under the root sign: -√6 and 4√6 are both multiples of √6.", 1),
            q("Simplify 2√3 + 3√3.",
              "5√3",
              ["5√6", "6√3", "√15"],
              "Collect like surds: (2 + 3)√3 = 5√3.", 1),
            q("Simplify 8√10 - 3√10 - 2√10.",
              "3√10",
              ["13√10", "3√30", "2√10"],
              "Collect like surds: (8 - 3 - 2)√10 = 3√10.", 1),
            q("Simplify 2√3 + 3√7 - 5√3 + √7.",
              "4√7 - 3√3",
              ["4√7 + 3√3", "-3√3 - 4√7", "√21"],
              "Collect the √3 terms (2 - 5 = -3) and the √7 terms (3 + 1 = 4): -3√3 + 4√7.", 2),
            q("Simplify √147.",
              "7√3",
              ["3√7", "49√3", "7√21"],
              "147 = 49 × 3, so √147 = √49 × √3 = 7√3.", 1),
            q("Simplify √150.",
              "5√6",
              ["6√5", "25√6", "15√10"],
              "150 = 25 × 6, so √150 = √25 × √6 = 5√6.", 1),
            q("Simplify √12.",
              "2√3",
              ["3√2", "4√3", "6"],
              "12 = 4 × 3, so √12 = 2√3.", 1),
            q("Simplify √27 + 4√3.",
              "7√3",
              ["5√3", "7√6", "12√3"],
              "√27 = 3√3, so 3√3 + 4√3 = 7√3.", 2),
            q("Simplify √50 - 4√2.",
              "√2",
              ["9√2", "-√2", "2"],
              "√50 = 5√2, so 5√2 - 4√2 = √2.", 2),
            q("Simplify 2√5 - 2√20 + √125.",
              "3√5",
              ["7√5", "-√5", "5√3"],
              "√20 = 2√5 and √125 = 5√5, so 2√5 - 4√5 + 5√5 = 3√5.", 2),
            q("Express √18 + √32 as a single surd of the form √Δ.",
              "√98",
              ["√50", "√48", "√196"],
              "√18 + √32 = 3√2 + 4√2 = 7√2 = √(49 × 2) = √98.", 2),
            q("Simplify √3 × √7.",
              "√21",
              ["√10", "21", "3√7"],
              "√3 × √7 = √(3 × 7) = √21.", 1),
            q("Simplify √200 + √150 - √96.",
              "10√2 + √6",
              ["10√2 - √6", "14√2", "10√2 + 9√6"],
              "√200 = 10√2, √150 = 5√6, √96 = 4√6, so 10√2 + 5√6 - 4√6 = 10√2 + √6.", 3),
            q("Simplify √64 - √108 + √25 - 2√3.",
              "13 - 8√3",
              ["13 + 8√3", "3 - 8√3", "13 - 4√3"],
              "√64 = 8, √108 = 6√3, √25 = 5, so 8 - 6√3 + 5 - 2√3 = 13 - 8√3.", 3),
            q("Expand and simplify 2√3(√5 + 3).",
              "2√15 + 6√3",
              ["2√15 + 6", "2√8 + 6√3", "6√15"],
              "2√3 × √5 = 2√15 and 2√3 × 3 = 6√3.", 2),
            q("Expand and simplify 2√3(2√15 - 5√3).",
              "12√5 - 30",
              ["12√5 - 15", "30 - 12√5", "4√15 - 30"],
              "2√3 × 2√15 = 4√45 = 12√5 and 2√3 × 5√3 = 10 × 3 = 30.", 2),
            q("Simplify √7(√7 + √3) - √21.",
              "7",
              ["7 + 2√21", "49", "7√3"],
              "√7 × √7 = 7 and √7 × √3 = √21, so 7 + √21 - √21 = 7.", 2),
            q("Expand and simplify (4 - √5)².",
              "21 - 8√5",
              ["11", "21 + 8√5", "16 - 8√5"],
              "(4 - √5)² = 16 - 8√5 + 5 = 21 - 8√5.", 2),
            q("Expand and simplify (√2 + √5 + √7)(√2 + √5 - √7).",
              "2√10",
              ["14", "2√35", "√10"],
              "Difference of squares: (√2 + √5)² - (√7)² = (7 + 2√10) - 7 = 2√10.", 3),
            q("Simplify (√32 + √18)/(3 + √2), giving the answer in the form b + c√2 with integers b and c.",
              "3√2 - 2",
              ["3√2 + 2", "2 - 3√2", "7√2"],
              "√32 + √18 = 7√2. Multiply by (3 - √2)/(3 - √2): 7√2(3 - √2)/7 = 3√2 - 2.", 3),
            q("Express 2/(2 + √2) in the form p + q√2 where p and q are rational.",
              "2 - √2",
              ["2 + √2", "1 + √2", "1 - √2"],
              "Multiply by (2 - √2)/(2 - √2): 2(2 - √2)/(4 - 2) = 2 - √2.", 3),
            q("Express 2/√7 with a rational denominator.",
              "2√7/7",
              ["√7/2", "2/7", "√14/7"],
              "Multiply top and bottom by √7: 2√7/7.", 1),
            q("Factorise √2 + √10 by taking out a common factor.",
              "√2(1 + √5)",
              ["√2(1 + √10)", "√5(1 + √2)", "2(1 + √5)"],
              "√10 = √2 × √5, so √2 + √10 = √2(1 + √5).", 2),
            q("Simplify √63 - √28.",
              "√7",
              ["√35", "5√7", "√91"],
              "√63 = 3√7 and √28 = 2√7, so 3√7 - 2√7 = √7.", 2),
        ],
    },
    {
        "strand": "Number",
        "topic": "Indices & Scientific Notation",
        "questions": [
            q("Simplify a¹¹ ÷ a⁷.",
              "a⁴",
              ["a¹⁸", "a⁷⁷", "a^(11/7)"],
              "When dividing powers with the same base, subtract the indices: 11 - 7 = 4.", 1),
            q("Simplify (a³)⁵.",
              "a¹⁵",
              ["a⁸", "a²⁴³", "5a³"],
              "When raising a power to a power, multiply the indices: 3 × 5 = 15.", 1),
            q("Simplify 2ᵃ × 5ᵃ.",
              "10ᵃ",
              ["7ᵃ", "10^(2a)", "10^(a²)"],
              "Same index, different bases: 2ᵃ × 5ᵃ = (2 × 5)ᵃ = 10ᵃ.", 2),
            q("Simplify 3ᵃ + 3ᵃ + 3ᵃ.",
              "3^(a+1)",
              ["3^(3a)", "9ᵃ", "27ᵃ"],
              "Three lots of 3ᵃ is 3 × 3ᵃ = 3^(a+1).", 2),
            q("Find a if a³ = 125.",
              "5",
              ["-5", "3", "25"],
              "5³ = 125, so a = 5.", 1),
            q("Find c and d if 400 = 2ᶜ × 5ᵈ.",
              "c = 4 and d = 2",
              ["c = 2 and d = 4", "c = 3 and d = 2", "c = 4 and d = 3"],
              "400 = 16 × 25 = 2⁴ × 5².", 2),
            q("If 2ᵃ = 5, evaluate 2^(a+2).",
              "20",
              ["7", "9", "25"],
              "2^(a+2) = 2ᵃ × 2² = 5 × 4 = 20.", 2),
            q("If 2ᵃ = 5, evaluate 4ᵃ.",
              "25",
              ["10", "20", "625"],
              "4ᵃ = (2²)ᵃ = (2ᵃ)² = 5² = 25.", 2),
            q("If 2ᵃ = 5, evaluate 2⁻ᵃ.",
              "1/5",
              ["-5", "-1/5", "1/25"],
              "2⁻ᵃ = 1/2ᵃ = 1/5.", 2),
            q("What is half of 2²ⁿ?",
              "2^(2n-1)",
              ["2ⁿ", "1²ⁿ", "2^(n-1)"],
              "Half of 2²ⁿ is 2²ⁿ ÷ 2 = 2^(2n-1). (Halving the index or the base is incorrect.)", 2),
            q("What is half of 1.3 × 10⁵⁷, written in scientific notation?",
              "6.5 × 10⁵⁶",
              ["6.5 × 10⁵⁷", "1.3 × 10²⁸", "6.5 × 10²⁸"],
              "Half of 1.3 × 10⁵⁷ is 0.65 × 10⁵⁷ = 6.5 × 10⁵⁶.", 2),
            q("Which number is larger: 2⁴⁵⁰ or 3³⁰⁰?",
              "3³⁰⁰",
              ["2⁴⁵⁰", "They are equal", "It cannot be determined"],
              "2⁴⁵⁰ = (2³)¹⁵⁰ = 8¹⁵⁰ and 3³⁰⁰ = (3²)¹⁵⁰ = 9¹⁵⁰; since 9 > 8, 3³⁰⁰ is larger.", 3),
            q("Which number is larger: 300⁹⁰⁰ or 900³⁰⁰?",
              "300⁹⁰⁰",
              ["900³⁰⁰", "They are equal", "It cannot be determined"],
              "300⁹⁰⁰ = (300³)³⁰⁰ = 27 000 000³⁰⁰, and 27 000 000³⁰⁰ > 900³⁰⁰.", 3),
            q("Express b⁻⁴ with a positive index.",
              "1/b⁴",
              ["-b⁴", "b⁴", "-4b"],
              "A negative index means the reciprocal: b⁻⁴ = 1/b⁴.", 1),
            q("Evaluate 16^(1/4).",
              "2",
              ["4", "64", "1/4"],
              "16^(1/4) is the fourth root of 16, which is 2 because 2⁴ = 16.", 1),
            q("Write 2.15 × 10⁴ as a basic numeral.",
              "21 500",
              ["2 150", "215 000", "0.000215"],
              "Move the decimal point 4 places to the right: 21 500.", 1),
            q("Which of these numbers is written correctly in scientific (standard) form?",
              "5 × 10⁻⁴",
              ["0.5 × 10⁴", "50 × 10⁴", "5 × 10^0.4"],
              "Scientific form is a × 10ⁿ with 1 ≤ a < 10 and n an integer; only 5 × 10⁻⁴ qualifies.", 1),
            q("Find the positive value of n if n² = 841.",
              "29",
              ["21", "27", "31"],
              "29² = 841, so n = 29.", 1),
            q("If 5ᵏ(5²)³ = 1, find k.",
              "-6",
              ["6", "-3", "0"],
              "5ᵏ × 5⁶ = 5⁰, so k + 6 = 0 and k = -6.", 2),
        ],
    },
    {
        "strand": "Number",
        "topic": "Number Skills & Estimation",
        "questions": [
            q("What number goes in the box to make this true?  3 + 4 × ☐ = 39",
              "9",
              ["12", "10", "8"],
              "4 × ☐ must equal 36, so ☐ = 9.", 1),
            q("Evaluate 9² - 3 × 4².",
              "33",
              ["-63", "1248", "144"],
              "Indices first: 81 - 3 × 16 = 81 - 48 = 33.", 2),
            q("Evaluate -6 - (-2 × 9) + (-15).",
              "-3",
              ["-39", "15", "-33"],
              "-6 - (-18) + (-15) = -6 + 18 - 15 = -3.", 2),
            q("Evaluate -24 - [-8 × (-5)] - (-9).",
              "-55",
              ["25", "-64", "-73"],
              "-8 × (-5) = 40, so -24 - 40 + 9 = -55.", 2),
            q("Evaluate (-40 ÷ (-5) + (-7)) × 3.",
              "3",
              ["-3", "45", "-45"],
              "-40 ÷ (-5) = 8, then (8 - 7) × 3 = 3.", 1),
            q("Evaluate [-6 × 4 - (-6)] × (-3).",
              "54",
              ["-54", "90", "-90"],
              "-24 + 6 = -18, then -18 × (-3) = 54.", 2),
            q("Evaluate -12 + (-6 × 5) + (-10).",
              "-52",
              ["-28", "8", "-62"],
              "-12 - 30 - 10 = -52.", 1),
            q("In a card game, a team stands to win 120 points (taking their score to 50) or to lose 120 points (taking their score to -190). What is their present score?",
              "-70",
              ["70", "-50", "50"],
              "50 - 120 = -70 (check: -70 - 120 = -190).", 2),
            q("Round 0.07162 to two significant figures.",
              "0.072",
              ["0.07", "0.0716", "0.08"],
              "The first two significant figures are 7 and 1; the next digit 6 rounds the 1 up: 0.072.", 1),
            q("Round 10.6951 to two decimal places.",
              "10.70",
              ["10.69", "10.695", "10.6"],
              "The third decimal (5) rounds 10.69 up to 10.70.", 1),
            q("By rounding each number to one significant figure, estimate 34 + 19 763.5 × 0.00761.",
              "190",
              ["150", "230", "1900"],
              "30 + 20 000 × 0.008 = 30 + 160 = 190.", 2),
            q("By rounding each number to one significant figure, estimate 9.983 × 1.5 ÷ 0.00461 + 203.6709.",
              "4200",
              ["600", "2400", "420"],
              "10 × 2 ÷ 0.005 + 200 = 4000 + 200 = 4200.", 2),
        ],
    },
    {
        "strand": "Number",
        "topic": "Fractions & Percentages",
        "questions": [
            q("A birthday cake costs $26.40 at the checkout (price includes 10% GST). How much GST is paid for the cake?",
              "$2.40",
              ["$2.64", "$2.20", "$24.00"],
              "When GST is included, the GST is one eleventh of the price: $26.40 ÷ 11 = $2.40.", 2),
            q("Alan bought a radio for $900 and sold it to Brian at a loss of 20%. At what price must Brian sell the radio to make a profit of 5%?",
              "$756",
              ["$720", "$945", "$765"],
              "Brian paid $900 × 0.80 = $720; selling at 5% profit gives $720 × 1.05 = $756.", 2),
            q("Increase 4200 by 38%.",
              "5796",
              ["1596", "4238", "6804"],
              "4200 × 1.38 = 5796.", 1),
            q("15% of a number is 12. What is the number?",
              "80",
              ["1.8", "18", "0.8"],
              "12 ÷ 0.15 = 80.", 1),
            q("A DVD player that normally sells for $90 was sold for $72. What was the percentage discount?",
              "20%",
              ["18%", "25%", "80%"],
              "The discount is $18, and 18/90 = 20%.", 1),
            q("Express 36% as a simplified fraction.",
              "9/25",
              ["9/20", "6/25", "1/36"],
              "36/100 = 9/25 after dividing top and bottom by 4.", 1),
            q("Express 60 cents as a percentage of $2.40.",
              "25%",
              ["40%", "4%", "2.5%"],
              "0.60/2.40 = 1/4 = 25%.", 1),
            q("Express 400 metres as a percentage of 2 kilometres.",
              "20%",
              ["200%", "5%", "2%"],
              "400/2000 = 1/5 = 20%.", 1),
            q("Find 15% of $45.",
              "$6.75",
              ["$3.00", "$67.50", "$6.25"],
              "0.15 × 45 = 6.75.", 1),
            q("9% of an amount is $72. What is the original amount?",
              "$800",
              ["$648", "$6.48", "$8000"],
              "72 ÷ 0.09 = 800.", 1),
            q("2½% of an amount is $400. Find 15% of the amount.",
              "$2400",
              ["$60", "$16 000", "$1500"],
              "The amount is 400 ÷ 0.025 = $16 000, and 15% of that is $2400 (or: 15% is 6 times 2½%, and 6 × $400 = $2400).", 3),
            q("Use a calculator to find 3.45% of $1200.",
              "$41.40",
              ["$34.78", "$414.00", "$4.14"],
              "0.0345 × 1200 = 41.40.", 1),
            q("Use a calculator to find 6¼% of $9900.",
              "$618.75",
              ["$61.88", "$633.60", "$158.40"],
              "0.0625 × 9900 = 618.75.", 2),
            q("A store-bought apple pie has a mass of 600 g. It lists 3.6 g of sugar per serving and there are 8 servings in the pie. What percentage of the mass of the pie is sugar?",
              "4.8%",
              ["0.6%", "6%", "48%"],
              "Total sugar is 3.6 × 8 = 28.8 g, and 28.8/600 = 4.8%.", 2),
            q("Write 0.62 as a simplified fraction.",
              "31/50",
              ["31/500", "16/25", "3/5"],
              "0.62 = 62/100 = 31/50.", 1),
            q("List all the integer values of x for which 4 < x/5 < 5.",
              "21, 22, 23 and 24",
              ["20, 21, 22, 23, 24 and 25", "21, 22 and 23", "20 and 25"],
              "Multiply through by 5: 20 < x < 25, so x can be 21, 22, 23 or 24.", 2),
            q("A clothing company offers employees a 12% discount off the regular price. An employee pays $110 for a suit. What was the regular price?",
              "$125",
              ["$123.20", "$122", "$96.80"],
              "$110 is 88% of the regular price, so the price is 110 ÷ 0.88 = $125.", 2),
            q("John has to load 1 tonne of potatoes onto a truck. When he has loaded 50 kg, what percentage of the job has he finished?",
              "5%",
              ["0.05%", "0.5%", "50%"],
              "1 tonne = 1000 kg, and 50/1000 = 5%.", 1),
            q("What is 30% of 5 hours 30 minutes?",
              "99 minutes",
              ["1 hour 30 minutes", "3.71 hours", "1.59 hours"],
              "5 h 30 min = 330 minutes, and 30% of 330 = 99 minutes (1 h 39 min).", 2),
        ],
    },
    {
        "strand": "Number",
        "topic": "Rates & Ratios",
        "questions": [
            q("$880 is divided in the ratio 2 : 3. What is the value of the larger portion?",
              "$528",
              ["$352", "$440", "$660"],
              "The larger share is 3 of 5 parts: 880 × 3/5 = $528.", 1),
            q("Simplify the ratio 0.6 : 0.18.",
              "10 : 3",
              ["3 : 10", "1 : 3", "5 : 2"],
              "Multiply both by 100 (60 : 18), then divide by 6: 10 : 3.", 1),
            q("Simplify the ratio 0.05 : 0.2.",
              "1 : 4",
              ["4 : 1", "1 : 5", "5 : 2"],
              "Multiply both by 100 (5 : 20), then divide by 5: 1 : 4.", 1),
            q("Write 160 km in 4 hours as a rate in simplest form.",
              "40 km/h",
              ["4 km/h", "640 km/h", "32 km/h"],
              "160 ÷ 4 = 40 km/h.", 1),
            q("Write 7980 revolutions in 5¼ minutes as a rate in simplest form.",
              "1520 revs/min",
              ["1596 revs/min", "1450 revs/min", "152 revs/min"],
              "7980 ÷ 5.25 = 1520 revolutions per minute.", 2),
            q("Which is the better value: 8 kg of rice for $5.60, or 5 kg of rice for $3.60?",
              "8 kg for $5.60",
              ["5 kg for $3.60", "They are the same value", "It cannot be determined"],
              "8 kg for $5.60 is $0.70/kg; 5 kg for $3.60 is $0.72/kg.", 2),
            q("500 mL of brand A conditioner costs $7.20, and 350 mL of brand B costs $5.00. Comparing the cost per 100 mL, which is the better buy?",
              "Brand B (about $1.43 per 100 mL)",
              ["Brand A (about $1.44 per 100 mL)", "They cost the same per 100 mL", "It cannot be determined"],
              "A costs 7.20/5 = $1.44 per 100 mL; B costs 5.00/3.5 ≈ $1.43 per 100 mL, so B is slightly cheaper.", 2),
            q("The Jonson family's car uses a 62 L tank of petrol to drive 756 km. The Mikhl family's car uses a 125 L tank to drive 1480 km. Using litres per 100 km, which car is more economical?",
              "The Jonson car (about 8.2 L/100 km)",
              ["The Mikhl car (about 8.4 L/100 km)", "Both are equally economical", "It cannot be determined"],
              "Jonson: 62/7.56 ≈ 8.2 L/100 km. Mikhl: 125/14.8 ≈ 8.4 L/100 km. Lower is better.", 2),
            q("Ten packs of 100 CDs cost $310 in total. How much did each CD cost?",
              "31c",
              ["$3.10", "$310", "3.1c"],
              "There are 1000 CDs, so each costs $310 ÷ 1000 = $0.31 = 31c.", 1),
            q("The area of Australia is approximately 7 670 000 km² and the area of England is approximately 130 000 km². What is the simple ratio of England's area to Australia's area?",
              "1 : 59",
              ["59 : 1", "1 : 6", "1 : 590"],
              "130 000 : 7 670 000 = 13 : 767 = 1 : 59.", 2),
            q("Convert 3 m/s into metres per minute.",
              "180 m/min",
              ["0.05 m/min", "18 m/min", "1080 m/min"],
              "3 × 60 = 180 metres per minute.", 1),
            q("Brand P cooking oil costs $5 for 750 mL. Brand Q cooking oil costs $4 for 500 mL. How much more does 1500 mL of Brand Q cost than 1500 mL of Brand P?",
              "$2",
              ["$1", "$4", "$3"],
              "1500 mL of P costs 2 × $5 = $10; 1500 mL of Q costs 3 × $4 = $12; the difference is $2.", 2),
            q("The heart pumps 5 L of blood every minute. If George's heart beats at 75 beats per minute, how much blood is pumped with each beat, to the nearest millilitre?",
              "67 mL",
              ["15 mL", "375 mL", "7 mL"],
              "5000 mL ÷ 75 beats ≈ 66.7 mL ≈ 67 mL per beat.", 2),
            q("A model car was created at a scale of 1 : 90. If the model is 4 cm long, how long is the real car in metres?",
              "3.6 m",
              ["0.36 m", "36 m", "22.5 m"],
              "4 cm × 90 = 360 cm = 3.6 m.", 1),
            q("A photographic negative measures 3 cm by 2.5 cm. It is enlarged so that the longer side of the print is 32 cm. How wide is the print?",
              "26⅔ cm",
              ["38.4 cm", "24 cm", "16 cm"],
              "The scale factor is 32/3, so the width is 2.5 × 32/3 = 80/3 = 26⅔ cm.", 2),
            q("A train travels due north in a straight line at 160 km/h. How far does it travel between 9:00 pm and 9:45 pm?",
              "120 km",
              ["160 km", "213 km", "72 km"],
              "45 minutes is 0.75 h, and 160 × 0.75 = 120 km.", 1),
            q("Stella takes 4 hours to paint a room and Jose takes 3 hours to paint the same room. How long will the job take if they work together?",
              "12/7 hours (about 1 h 43 min)",
              ["3½ hours", "7 hours", "2 hours 20 min"],
              "Their combined rate is 1/4 + 1/3 = 7/12 rooms per hour, so the time is 12/7 hours.", 2),
            q("Evan shovels snow twice as fast as JJ. Together they clear the driveway in 13 minutes 20 seconds. How long would it take JJ working alone?",
              "40 minutes",
              ["20 minutes", "26 minutes 40 seconds", "30 minutes"],
              "Together they work 3 times as fast as JJ alone, so JJ alone takes 3 × 13⅓ = 40 minutes.", 3),
            q("A speedboat travels 108 km downstream in the same time it takes to travel 78 km upstream. If the river current is 10 km/h, what is the speed of the boat in still water?",
              "62 km/h",
              ["52 km/h", "72 km/h", "31 km/h"],
              "108/(s + 10) = 78/(s - 10) gives 108s - 1080 = 78s + 780, so 30s = 1860 and s = 62 km/h.", 3),
            q("In 2012, tourists in the USA spent $1.262 × 10¹¹ in total, and 6.70 × 10⁷ tourists visited the USA. 21% of the money was spent by Canadians, and 34% of the tourists were Canadians. What was the average amount spent by each Canadian tourist, to the nearest dollar?",
              "$1163",
              ["$396", "$1884", "$640"],
              "(0.21 × 1.262 × 10¹¹) ÷ (0.34 × 6.70 × 10⁷) = 2.6502 × 10¹⁰ ÷ 2.278 × 10⁷ ≈ $1163.", 3),
            q("A professor finishes work 3 hours early and walks home at 6 km/h. Her husband leaves home just in time to pick her up at the usual finish time, but meets her on the way, picks her up 9 km from home and they arrive home 2 hours earlier than usual. What is the average speed of the car?",
              "12 km/h",
              ["6 km/h", "18 km/h", "9 km/h"],
              "Arriving 2 h early means the car saved a 1 h trip each way, so it met her 1 driving-hour from the university. She walked for 2 h (12 km), so the car covers 12 km in 1 h: 12 km/h.", 3),
            q("Simplify the ratio 25 cm² : 30 mm².",
              "250 : 3",
              ["25 : 3", "25 : 30", "5 : 6"],
              "1 cm² = 100 mm², so 25 cm² = 2500 mm². Then 2500 : 30 = 250 : 3.", 2),
            q("x varies directly as y and inversely as z. When y = 10 and z = 15, x = 8. Find x when y = 4 and z = 3.",
              "16",
              ["12", "1.6", "20"],
              "x = k·y/z. From 8 = k·10/15, k = 12. Then x = 12·4/3 = 16.", 3),
        ],
    },
    {
        "strand": "Number",
        "topic": "Financial Mathematics",
        "questions": [
            q("Andrew borrows $10 000 for three years at 4.5% per annum simple interest. How much interest does he pay?",
              "$1350",
              ["$450", "$11 350", "$135"],
              "I = PRT = 10 000 × 0.045 × 3 = $1350.", 1),
            q("Josh invests $50 000 in an account earning 6% interest per annum, compounded annually. What is the value of the account at the end of eight years, to the nearest cent?",
              "$79 692.40",
              ["$74 000.00", "$29 692.40", "$53 000.00"],
              "50 000 × 1.06⁸ = $79 692.40.", 2),
            q("Josh invests $50 000 at 6% per annum compound interest. How many whole years until his total interest exceeds $200 000?",
              "28 years",
              ["27 years", "24 years", "67 years"],
              "We need 1.06ⁿ ≥ 5. 1.06²⁷ ≈ 4.82 and 1.06²⁸ ≈ 5.11, so 28 years.", 3),
            q("David invests $5000 in a savings account paying 3.2% compound interest per year. What is the value of his investment after 3 years, to the nearest cent?",
              "$5495.52",
              ["$5480.00", "$5160.00", "$6536.00"],
              "5000 × 1.032³ = $5495.52 (simple interest would give only $5480).", 2),
            q("Alex's weekly homework time depreciates by 15% each week over a ten-week term. In the tenth week he worked 2 hours. How long did he work in the first week, to the nearest minute?",
              "518 minutes",
              ["610 minutes", "422 minutes", "141 minutes"],
              "120 minutes = first week × 0.85⁹, so first week = 120/0.85⁹ ≈ 518 minutes.", 3),
            q("Tina earns $7.20 per hour at the normal rate. Each week she works 11 hours at the normal rate and 4 hours at time-and-a-half. Find her weekly wage.",
              "$122.40",
              ["$108.00", "$129.60", "$162.00"],
              "Normal: 11 × $7.20 = $79.20. Time-and-a-half: 4 × $7.20 × 1.5 = $43.20. Total $122.40.", 2),
            q("Tina's weekly wage is $122.40. She wants to raise it to $180 by working extra hours at the normal rate of $7.20/hour. How many extra hours must she work?",
              "8 hours",
              ["10 hours", "6 hours", "25 hours"],
              "Extra needed is $180 - $122.40 = $57.60, and 57.60 ÷ 7.20 = 8 hours.", 2),
            q("Tina's hourly rate of $7.20 is increased by 6%. Find the new hourly rate, to the nearest cent.",
              "$7.63",
              ["$7.26", "$13.20", "$7.20"],
              "$7.20 × 1.06 = $7.632 ≈ $7.63.", 1),
        ],
    },
    {
        "strand": "Algebra",
        "topic": "Algebraic Expressions & Factorisation",
        "questions": [
            q("Simplify 3a + 7b - a + 4b.",
              "2a + 11b",
              ["2a + 3b", "4a + 11b", "13ab"],
              "Collect like terms: (3 - 1)a + (7 + 4)b = 2a + 11b.", 1),
            q("Factorise a² + 4a - 5.",
              "(a + 5)(a - 1)",
              ["(a - 5)(a + 1)", "(a + 5)(a + 1)", "(a - 5)(a - 1)"],
              "Two numbers multiplying to -5 and adding to +4 are +5 and -1.", 1),
            q("Factorise 6x² + 17x - 3.",
              "(6x - 1)(x + 3)",
              ["(6x + 1)(x - 3)", "(3x - 1)(2x + 3)", "(6x + 3)(x - 1)"],
              "(6x - 1)(x + 3) = 6x² + 18x - x - 3 = 6x² + 17x - 3.", 2),
            q("Factorise m⁴ - 16 completely.",
              "(m - 2)(m + 2)(m² + 4)",
              ["(m - 2)²(m + 2)²", "(m - 2)(m + 2)(m² - 4)", "(m + 2)²(m² + 4)"],
              "m⁴ - 16 = (m² - 4)(m² + 4), and m² - 4 factorises further into (m - 2)(m + 2).", 2),
            q("Factorise y³ + 125.",
              "(y + 5)(y² - 5y + 25)",
              ["(y + 5)(y² + 5y + 25)", "(y - 5)(y² + 5y + 25)", "(y + 5)³"],
              "Sum of cubes: y³ + 5³ = (y + 5)(y² - 5y + 25).", 2),
            q("Expand and simplify (a - 3)(a² + 3a + 9).",
              "a³ - 27",
              ["a³ + 27", "a³ - 9a - 27", "a³ - 6a² + 27"],
              "This is the difference-of-cubes pattern: (a - 3)(a² + 3a + 9) = a³ - 3³ = a³ - 27.", 2),
            q("Factorise x² + 7x + 12.",
              "(x + 3)(x + 4)",
              ["(x + 2)(x + 6)", "(x + 1)(x + 12)", "(x - 3)(x - 4)"],
              "3 × 4 = 12 and 3 + 4 = 7.", 1),
            q("Factorise x² - 36.",
              "(x - 6)(x + 6)",
              ["(x - 6)²", "(x + 6)²", "(x - 4)(x + 9)"],
              "Difference of two squares: x² - 36 = (x - 6)(x + 6).", 1),
            q("Factorise 6a - a².",
              "a(6 - a)",
              ["a(a - 6)", "6(a - a²)", "a(6 + a)"],
              "Take out the common factor a: 6a - a² = a(6 - a).", 1),
            q("Factorise 4x² + 16x + 7.",
              "(2x + 1)(2x + 7)",
              ["(2x - 1)(2x - 7)", "(4x + 1)(x + 7)", "(x + 1)(4x + 7)"],
              "(2x + 1)(2x + 7) = 4x² + 14x + 2x + 7 = 4x² + 16x + 7.", 2),
            q("Factorise and simplify (x² - 9x + 14)/(x² - 2x - 35).",
              "(x - 2)/(x + 5)",
              ["(x + 2)/(x - 5)", "(x - 2)/(x - 5)", "(x + 2)/(x + 5)"],
              "(x - 2)(x - 7) over (x - 7)(x + 5): cancel (x - 7) to get (x - 2)/(x + 5).", 2),
            q("Which expression is equivalent to (x + 2)(x + 4) - (x - 2)(x - 5)?",
              "13x - 2",
              ["18 - x", "13x + 18", "-2 - x"],
              "(x² + 6x + 8) - (x² - 7x + 10) = 13x - 2.", 2),
            q("Simplify 4/(3a) + 5/(3a).",
              "3/a",
              ["3/(2a)", "9/a", "20/(9a²)"],
              "4/(3a) + 5/(3a) = 9/(3a) = 3/a.", 1),
            q("Simplify 7x/(12y) - 5x/(8y).",
              "-x/(24y)",
              ["x/(24y)", "29x/(24y)", "-x/(4y)"],
              "Common denominator 24y: 14x/(24y) - 15x/(24y) = -x/(24y).", 2),
            q("Simplify (5 + x)/(8y) - (7 + x)/(16y).",
              "(x + 3)/(16y)",
              ["(x - 3)/(16y)", "(x + 3)/(8y)", "(3x + 17)/(16y)"],
              "Common denominator 16y: (10 + 2x - 7 - x)/(16y) = (x + 3)/(16y).", 2),
            q("Write a/(b + 1) - a/(b + 1)² as a single fraction in simplest form.",
              "ab/(b + 1)²",
              ["a/(b + 1)²", "ab/(b + 1)", "-ab/(b + 1)²"],
              "[a(b + 1) - a]/(b + 1)² = ab/(b + 1)².", 2),
            q("Make x the subject of the formula y = 6x - 5.",
              "x = (y + 5)/6",
              ["x = (y - 5)/6", "x = 6(y + 5)", "x = (5 - y)/6"],
              "Add 5 to both sides, then divide by 6.", 1),
            q("Given (2a + 1)/b + 1/c = 1/3, find an expression for b.",
              "b = 3c(2a + 1)/(c - 3)",
              ["b = 3c(2a + 1)/(3 - c)", "b = (2a + 1)(c - 3)/(3c)", "b = 3(2a + 1)/(c - 3)"],
              "(2a + 1)/b = 1/3 - 1/c = (c - 3)/(3c), so b = 3c(2a + 1)/(c - 3).", 3),
            q("What is the highest common factor (HCF) of 6xy² and 4x³y?",
              "2xy",
              ["2xy²", "12x³y²", "24x⁴y³"],
              "HCF of 6 and 4 is 2; the common letters are x (lowest power 1) and y (lowest power 1).", 2),
            q("Expand and simplify (x + 2)(x - 3)(x + 4).",
              "x³ + 3x² - 10x - 24",
              ["x³ - 3x² - 10x + 24", "x³ + 3x² + 10x - 24", "x³ + 9x² + 26x + 24"],
              "(x + 2)(x - 3) = x² - x - 6; multiplying by (x + 4) gives x³ + 3x² - 10x - 24.", 3),
            q("Expand and simplify (3x² + 2)(2x + 5) - 6x(x² - 3).",
              "15x² + 22x + 10",
              ["15x² + 4x + 10", "15x² - 14x + 10", "12x³ + 15x² + 22x + 10"],
              "6x³ + 15x² + 4x + 10 - 6x³ + 18x = 15x² + 22x + 10.", 3),
            q("Kris simplifies 3n⁵ × 2n⁴ and gets 5n²⁰. What is the correct simplification?",
              "6n⁹",
              ["5n²⁰", "6n²⁰", "5n⁹"],
              "Multiply the coefficients (3 × 2 = 6) and add the indices (5 + 4 = 9).", 1),
            q("Solve d = ab - ac for a.",
              "a = d/(b - c)",
              ["a = d/(c - b)", "a = (b - c)/d", "a = d - b + c"],
              "Factor the right side: d = a(b - c), so a = d/(b - c).", 2),
            q("Simplify (3x² - 12)/(30x + 15) ÷ (2x² - 3x - 2)/(4x² + 4x + 1).",
              "(x + 2)/5",
              ["5/(x + 2)", "(x - 2)/5", "(x + 2)/(5(2x + 1))"],
              "3(x - 2)(x + 2)/[15(2x + 1)] × (2x + 1)²/[(2x + 1)(x - 2)] = (x + 2)/5.", 3),
            q("Two inequalities have solution sets P = (-∞, 0) and Q = [0, 10]. What is P ∪ Q?",
              "(-∞, 10]",
              ["(-∞, 0]", "[0, 10]", "(-∞, 10)"],
              "Together the two sets cover every number up to and including 10.", 2),
            q("If a = -2 and c = 5, evaluate ac².",
              "-50",
              ["100", "20", "-20"],
              "ac² = -2 × 5² = -2 × 25 = -50 (only c is squared).", 1),
            q("If a = -2, b = 3/4 and c = 5, evaluate (a + b)/(bc).",
              "-1/3",
              ["1/3", "-3", "-15/4"],
              "(-2 + 3/4)/((3/4) × 5) = (-5/4)/(15/4) = -1/3.", 2),
            q("The area of a rectangle is A = LW. If you double the length and triple the width, the area is multiplied by what number?",
              "6",
              ["5", "12", "9"],
              "(2L)(3W) = 6LW, so the area is 6 times bigger.", 1),
            q("Factorise x² + 4x - 21.",
              "(x + 7)(x - 3)",
              ["(x - 7)(x + 3)", "(x + 7)(x + 3)", "(x - 7)(x - 3)"],
              "Two numbers multiplying to -21 and adding to +4 are +7 and -3.", 1),
            q("If x² - y² = 64 and x + y = 16, find the value of x - y.",
              "4",
              ["48", "8", "1/4"],
              "x² - y² = (x + y)(x - y), so 64 = 16(x - y) and x - y = 4.", 2),
            q("Simplify (2 - 3x) - (5 - 4x).",
              "x - 3",
              ["-x - 3", "x - 7", "7x - 3"],
              "2 - 3x - 5 + 4x = (4x - 3x) + (2 - 5) = x - 3.", 1),
            q("Simplify 2p² × 3p³q².",
              "6p⁵q²",
              ["6p⁶q²", "5p⁵q²", "6p⁵q⁴"],
              "Multiply coefficients (2 × 3 = 6) and add indices of p (2 + 3 = 5): 6p⁵q².", 1),
            q("Simplify (x⁻² - y⁻²)/(x⁻¹ + y⁻¹), leaving no negative indices.",
              "(y - x)/(xy)",
              ["(x - y)/(xy)", "(y - x)/(x²y²)", "xy/(y - x)"],
              "Top = (y² - x²)/(x²y²) = (y - x)(y + x)/(x²y²); bottom = (y + x)/(xy). Dividing gives (y - x)/(xy).", 3),
            q("If (3a + 4b)/(2a - 2b) = 5, find the value of (a² + 2b²)/(ab).",
              "3",
              ["5", "6", "2"],
              "3a + 4b = 10a - 10b gives 14b = 7a, so a = 2b. Then (4b² + 2b²)/(2b²) = 3.", 3),
            q("Find x: 2/15 = 1/8 + 1/x.",
              "120",
              ["15/8", "1/7", "120/31"],
              "1/x = 2/15 - 1/8 = 16/120 - 15/120 = 1/120, so x = 120.", 2),
        ],
    },
    {
        "strand": "Algebra",
        "topic": "Solving Linear Equations",
        "questions": [
            q("From a 3.6 m piece of timber, 5 pieces of equal length are cut, leaving 28 cm. What length was each piece cut to?",
              "66.4 cm",
              ["72 cm", "77.6 cm", "44 cm"],
              "5x + 28 = 360, so x = (360 - 28)/5 = 66.4 cm.", 2),
            q("Solve 2x - 3 = x + 9.",
              "x = 12",
              ["x = 6", "x = 4", "x = -12"],
              "Subtract x and add 3: x = 12.", 1),
            q("Solve x + 3 = 2 + (x - 3)/5.",
              "x = -2",
              ["x = 2", "x = -8", "x = 1/2"],
              "Multiply every term by 5: 5x + 15 = 10 + x - 3, so 4x = -8 and x = -2.", 2),
            q("Solve 5 - 2x = 3(x - 7).",
              "x = 5.2",
              ["x = -5.2", "x = 3.2", "x = 26"],
              "5 - 2x = 3x - 21, so 26 = 5x and x = 26/5 = 5.2.", 2),
            q("Solve the inequality 9 - 2x ≥ 6.",
              "x ≤ 3/2",
              ["x ≥ 3/2", "x ≤ -3/2", "x ≥ -3/2"],
              "-2x ≥ -3; dividing by -2 reverses the inequality: x ≤ 3/2.", 2),
            q("Solve the simultaneous equations x + 2y + 4 = 0 and 3x - y - 3 = 0.",
              "x = 2/7, y = -15/7",
              ["x = 2/7, y = 15/7", "x = -2/7, y = -15/7", "x = 2, y = -3"],
              "From the second equation y = 3x - 3; substituting: x + 6x - 6 + 4 = 0, so x = 2/7 and y = -15/7.", 3),
            q("Solve simultaneously: 3x - y = 6 and y = x + 2.",
              "x = 4, y = 6",
              ["x = 2, y = 4", "x = -4, y = -2", "x = 6, y = 4"],
              "3x - (x + 2) = 6 gives 2x = 8, so x = 4 and y = 6.", 2),
            q("Solve by elimination: 3x + 5y = 8 and x - 2y = -1.",
              "x = 1, y = 1",
              ["x = -1, y = 1", "x = 1, y = -1", "x = 2, y = 1"],
              "Multiply the second equation by 3 and subtract: 11y = 11, so y = 1 and x = 1.", 2),
            q("A hot chocolate costs $2 more than a bubble tea. Three hot chocolates and five bubble teas cost $70. What does each drink cost?",
              "Hot chocolate $10, bubble tea $8",
              ["Hot chocolate $8, bubble tea $6", "Hot chocolate $12, bubble tea $10", "Hot chocolate $9, bubble tea $7"],
              "3(b + 2) + 5b = 70 gives 8b = 64, so the bubble tea is $8 and the hot chocolate is $10.", 2),
            q("A rectangle has area 104 cm² and length 8 cm. Using A = lw, find its width.",
              "13 cm",
              ["10 cm", "14 cm", "18 cm"],
              "w = 104 ÷ 8 = 13 cm.", 1),
            q("Four more than three times a number is 49. What is the number?",
              "15",
              ["18", "12", "45"],
              "3n + 4 = 49, so n = 45/3 = 15.", 1),
            q("Road Runner Clothing pays $100 a day plus 5% of sales. Blue Jag Boutique pays $75 a day plus 10% of sales. For what daily sales amount do the two jobs pay the same?",
              "$500",
              ["$250", "$1000", "$125"],
              "100 + 0.05s = 75 + 0.10s gives 25 = 0.05s, so s = $500.", 2),
            q("The sum of two consecutive integers is 503. What are the integers?",
              "251 and 252",
              ["250 and 253", "252 and 253", "201 and 302"],
              "n + (n + 1) = 503 gives n = 251.", 1),
            q("A table of values for a straight-line graph shows x = 0, 1, 2 and y = 3, 2, ?. What is the missing y value?",
              "1",
              ["0", "4", "-1"],
              "The y values decrease by 1 each step, so the next value is 1.", 1),
            q("Solve the inequality 3x - 29 ≤ 4x + 12.",
              "x ≥ -41",
              ["x ≤ -41", "x ≥ 41", "x ≤ 41"],
              "3x - 29 ≤ 4x + 12 gives -41 ≤ x, i.e. x ≥ -41.", 2),
            q("Tickets for a river cruise cost $15 for an adult and $8 for a child. For one cruise, 46 tickets were sold for a total of $438. How many adult tickets were sold?",
              "10",
              ["36", "20", "26"],
              "With A + C = 46 and 15A + 8C = 438: 15A + 8(46 - A) = 438 gives 7A = 70, so A = 10.", 2),
            q("Solve (2x - 5)/3 - (x + 7)/5 = 2.",
              "x = 76/7",
              ["x = 46/7", "x = 30", "x = -76/7"],
              "Multiply by 15: 5(2x - 5) - 3(x + 7) = 30, so 7x - 46 = 30 and x = 76/7.", 2),
            q("Solve the inequality -3x > 6.",
              "x < -2",
              ["x > -2", "x < 2", "x > 2"],
              "Divide both sides by -3 and reverse the inequality: x < -2.", 1),
        ],
    },
    {
        "strand": "Algebra",
        "topic": "Quadratic Equations",
        "questions": [
            q("Solve (x - 2)(x + 7) = 0.",
              "x = 2 or x = -7",
              ["x = -2 or x = 7", "x = 2 or x = 7", "x = -2 or x = -7"],
              "Each factor can be zero: x = 2 or x = -7.", 1),
            q("Use completing the square to solve x² - 4x - 4 = 0.",
              "x = 2 ± 2√2",
              ["x = -2 ± 2√2", "x = 4 ± √2", "x = 2 ± 2√3"],
              "(x - 2)² = 8, so x - 2 = ±2√2 and x = 2 ± 2√2.", 3),
            q("Solve x - 3 = 16/(x - 3).",
              "x = 7 or x = -1",
              ["x = 7 only", "x = 1 or x = -7", "x = 5 or x = -3"],
              "(x - 3)² = 16, so x - 3 = ±4, giving x = 7 or x = -1.", 3),
            q("Solve x/20 = 3/(x - 4).",
              "x = 10 or x = -6",
              ["x = 10 only", "x = -10 or x = 6", "x = 12 or x = -5"],
              "x(x - 4) = 60, so x² - 4x - 60 = 0 = (x - 10)(x + 6).", 2),
            q("Solve x/(x - 2) - (x + 1)/(x + 4) = 1.",
              "x = 5 or x = -2",
              ["x = -5 or x = 2", "x = 5 only", "No solution"],
              "x(x + 4) - (x + 1)(x - 2) = (x - 2)(x + 4) leads to x² - 3x - 10 = 0 = (x - 5)(x + 2); neither value is excluded.", 3),
            q("The combined area of a square of side 6 m and an attached rectangle gives the equation x² + 6x - 187 = 0. Find the positive value of x.",
              "11",
              ["17", "13", "22"],
              "x = (-6 + √(36 + 748))/2 = (-6 + 28)/2 = 11.", 2),
            q("Solve 3x² = 2x + 2, giving the answer in simplest surd form.",
              "x = (1 ± √7)/3",
              ["x = (1 ± √7)/6", "x = (-1 ± √7)/3", "x = (2 ± √28)/3"],
              "3x² - 2x - 2 = 0, so x = (2 ± √(4 + 24))/6 = (2 ± 2√7)/6 = (1 ± √7)/3.", 3),
        ],
    },
    {
        "strand": "Algebra",
        "topic": "Linear Relationships & Coordinate Geometry",
        "questions": [
            q("The point M(1, 10) is the midpoint of AB, where A is (-3, 7). What are the coordinates of B?",
              "(5, 13)",
              ["(-1, 8.5)", "(5, 12)", "(-7, 4)"],
              "B = (2 × 1 - (-3), 2 × 10 - 7) = (5, 13).", 2),
            q("What are the coordinates of the midpoint of AB, given A(-3, 1) and B(5, -7)?",
              "(1, -3)",
              ["(-1, -2)", "(-4, 4)", "(4, -4)"],
              "Average the coordinates: ((-3 + 5)/2, (1 - 7)/2) = (1, -3).", 1),
            q("A straight line passes through (1, 5) and (5, -7). What is its gradient?",
              "-3",
              ["3", "-1/3", "1/3"],
              "m = (-7 - 5)/(5 - 1) = -12/4 = -3.", 1),
            q("Find the equation of the straight line through (1, 5) and (5, -7).",
              "y = -3x + 8",
              ["y = -3x + 2", "y = 3x + 2", "y = -3x - 8"],
              "The gradient is -3; substituting (1, 5): 5 = -3 + c, so c = 8.", 2),
            q("The line L has gradient 3 and passes through A(-6, 4). What is the equation of L in the form y = mx + c?",
              "y = 3x + 22",
              ["y = 3x - 14", "y = 3x + 4", "y = 3x - 22"],
              "4 = 3 × (-6) + c gives c = 22.", 2),
            q("The line K has equation x - 7y + 14 = 0. At what point does K cross the y-axis?",
              "(0, 2)",
              ["(0, 14)", "(-14, 0)", "(0, -2)"],
              "Set x = 0: -7y + 14 = 0, so y = 2.", 2),
            q("Find the point of intersection of y = 3x + 22 and x - 7y + 14 = 0.",
              "(-7, 1)",
              ["(7, 1)", "(-7, -1)", "(1, -7)"],
              "Substitute: x - 7(3x + 22) + 14 = 0 gives -20x - 140 = 0, so x = -7 and y = 1.", 3),
            q("Triangle ABC has vertices A(-6, 4), B(0, 2) and C(-7, 1), with a right angle at A. What is the area of triangle ABC?",
              "10 square units",
              ["20 square units", "40 square units", "√10 square units"],
              "AB = √40 = 2√10 and AC = √10, so the area is ½ × 2√10 × √10 = 10.", 3),
            q("Find the length of the interval AB given A(3, 7) and B(6, 11).",
              "5 units",
              ["7 units", "√7 units", "25 units"],
              "AB = √(3² + 4²) = √25 = 5.", 1),
            q("What is the equation of the vertical line passing through (2, 3)?",
              "x = 2",
              ["y = 3", "y = 2", "x = 3"],
              "Vertical lines have equations of the form x = constant.", 1),
            q("Find the x-intercept and y-intercept of the line y = -x + 3.",
              "x-intercept 3, y-intercept 3",
              ["x-intercept -3, y-intercept 3", "x-intercept 3, y-intercept -3", "x-intercept -3, y-intercept -3"],
              "Set y = 0 for the x-intercept (x = 3) and x = 0 for the y-intercept (y = 3).", 1),
            q("The line l is parallel to y = 5x - 8 and passes through (-1, -14). What is the equation of l?",
              "y = 5x - 9",
              ["y = 5x - 14", "y = 5x + 9", "y = -5x - 9"],
              "Parallel lines share gradient 5; -14 = 5 × (-1) + c gives c = -9.", 2),
            q("Calculate the gradient of the line joining (2, 3) and (7, 13).",
              "2",
              ["1/2", "-2", "10"],
              "m = (13 - 3)/(7 - 2) = 10/5 = 2.", 1),
            q("Calculate the gradient of the line joining (-2, -5) and (8, -9).",
              "-2/5",
              ["2/5", "-5/2", "5/2"],
              "m = (-9 - (-5))/(8 - (-2)) = -4/10 = -2/5.", 2),
            q("What is the gradient of the line y = 5 - 2x?",
              "-2",
              ["5", "2", "-5"],
              "Written as y = -2x + 5, the coefficient of x is the gradient: -2.", 1),
            q("Write the equation of the straight line with gradient -2 and y-intercept 3.",
              "y = -2x + 3",
              ["y = 3x - 2", "y = -2x - 3", "y = 2x + 3"],
              "y = mx + c with m = -2 and c = 3.", 1),
            q("Transpose 3y - 6x + 8 = 0 to make y the subject. What are the gradient and y-intercept?",
              "y = 2x - 8/3; gradient 2, y-intercept -8/3",
              ["y = 2x + 8/3; gradient 2, y-intercept 8/3", "y = -2x - 8/3; gradient -2, y-intercept -8/3", "y = 6x - 8; gradient 6, y-intercept -8"],
              "3y = 6x - 8, so y = 2x - 8/3.", 2),
            q("Find the x-intercept and the y-intercept of the line 3x - 2y = 6.",
              "x-intercept 2, y-intercept -3",
              ["x-intercept -3, y-intercept 2", "x-intercept 3, y-intercept -2", "x-intercept 2, y-intercept 3"],
              "Set y = 0: x = 2. Set x = 0: y = -3.", 2),
            q("What is the x-intercept of the line y = 3x + 7?",
              "-7/3",
              ["7/3", "7", "-3/7"],
              "Set y = 0: 3x = -7, so x = -7/3.", 2),
            q("A table of values shows c = -3, -2, -1, 0, 1, 2, 3 and d = -6, -4, -2, 0, 2, 4, 6. What is the rule connecting d and c?",
              "d = 2c",
              ["d = c/2", "d = c + 2", "d = 2c + 1"],
              "Each d value is twice the c value.", 1),
            q("A table of values shows x = -3, -2, -1, 0, 1, 2, 3 and y = -10, -7, -4, -1, 2, 5, 8. What is the rule connecting y and x?",
              "y = 3x - 1",
              ["y = 3x + 1", "y = 2x - 4", "y = x - 7"],
              "y increases by 3 each step (gradient 3) and y = -1 when x = 0.", 2),
            q("A table of values shows n = 0, 10, 20, 30 and C = 100, 150, 200, 250. What is the rule connecting C and n?",
              "C = 5n + 100",
              ["C = 10n + 100", "C = 5n + 95", "C = n + 100"],
              "C rises 50 for every 10 in n (rate 5) and C = 100 when n = 0.", 2),
            q("The pattern y = 2x + 7 fits the table x = 1, 2, 3, 4 and y = 9, 11, 13, 15. What is y when x = 200?",
              "407",
              ["400", "207", "410"],
              "y = 2 × 200 + 7 = 407.", 1),
            q("Jason cuts lawns, charging a $30 travelling fee plus $20 per hour. With x = hours worked and y = total charge in dollars, which equation models his pricing?",
              "y = 20x + 30",
              ["y = 30x + 20", "y = 20x - 30", "y = 50x"],
              "The rate per hour (20) multiplies x, and the fixed fee (30) is the constant.", 1),
            q("A steel beam joins the tops of two buildings that are 7 m apart. One building is 41 m tall and the other 52 m tall. What is the slope of the beam?",
              "11/7",
              ["7/11", "52/7", "41/7"],
              "Slope = rise/run = (52 - 41)/7 = 11/7.", 2),
            q("What is the gradient of the line through (6, 2) and (6, -5)?",
              "Undefined — it is a vertical line",
              ["0", "-7", "1"],
              "The run is 6 - 6 = 0, so the gradient is undefined (vertical line).", 2),
            q("A line segment joins (0, 5) and (a, 1) and has gradient 2. Find a.",
              "-2",
              ["2", "-8", "8"],
              "(1 - 5)/(a - 0) = 2 gives -4/a = 2, so a = -2.", 2),
            q("A line segment joins (7, 12) and (12, d) and has gradient 6. Find d.",
              "42",
              ["30", "18", "72"],
              "(d - 12)/(12 - 7) = 6 gives d - 12 = 30, so d = 42.", 2),
            q("What is the y-intercept of the line through (-5, -2) and (5, -5)?",
              "-3.5",
              ["3.5", "-2", "-5"],
              "The gradient is -3/10; halfway between the two points (at x = 0) the y value is -3.5.", 3),
            q("A line passes through (-8, 3) and (4, -1.5). What is its y-intercept?",
              "0",
              ["3", "-1.5", "1.5"],
              "The gradient is -4.5/12 = -3/8; then 3 = -3/8 × (-8) + c gives c = 0.", 3),
            q("The cost of printing pamphlets is T = 200 + 25n dollars, where n is the number of hundreds of pamphlets. What does it cost to print 800 pamphlets?",
              "$400",
              ["$20 200", "$425", "$1000"],
              "800 pamphlets means n = 8, so T = 200 + 25 × 8 = $400.", 2),
            q("A car uses 8.0 L of fuel per 100 km and starts with 60 L in the tank, so n = 60 - 8d (d in hundreds of km). How much fuel remains after 280 km?",
              "37.6 L",
              ["30.4 L", "22.4 L", "52.0 L"],
              "d = 2.8, so n = 60 - 8 × 2.8 = 37.6 L.", 2),
            q("For the table x = -2, -1, 0, 1, 2 and y = 2, 4, 8, 16, 32, what do the first differences tell you about the relationship?",
              "It is non-linear, because the first differences (2, 4, 8, 16) are not constant",
              ["It is linear with gradient 2", "It is linear with gradient 8", "It cannot be determined from a table"],
              "Constant first differences mean linear; here they double each time, so it is non-linear.", 2),
            q("In which quadrant of the number plane does the point (-3, 4) lie?",
              "Quadrant II",
              ["Quadrant I", "Quadrant III", "Quadrant IV"],
              "x is negative and y is positive, which is the second quadrant.", 1),
            q("A bowling alley charges a set fee plus an hourly fee: 1 hour costs $40, 2 hours $50, 3 hours $60 and 4 hours $70. Which equation gives the cost C for h hours?",
              "C = 10h + 30",
              ["C = 40h", "C = 30h + 10", "C = 10h + 40"],
              "Each extra hour adds $10, and the set fee is 40 - 10 = $30.", 2),
            q("Matches are used to build a row of hexagons: 1 hexagon uses 6 matches, 2 use 11, 3 use 16, and so on. How many matches are needed for 10 hexagons?",
              "51",
              ["46", "56", "60"],
              "The rule is m = 5s + 1, so m = 5 × 10 + 1 = 51.", 2),
            q("Straight lines that have the same gradient are called what?",
              "Parallel lines",
              ["Perpendicular lines", "Collinear lines", "Congruent lines"],
              "Equal gradients mean the lines never meet — they are parallel.", 1),
            q("Write the equation of the line through (2, 3) that is parallel to the x-axis.",
              "y = 3",
              ["x = 2", "y = 2", "x = 3"],
              "A line parallel to the x-axis is horizontal, y = constant; through (2, 3) it is y = 3.", 1),
            q("The line x + 2y + 8 = 0 cuts the x-axis at A. What are the coordinates of A?",
              "(-8, 0)",
              ["(0, -8)", "(-4, 0)", "(8, 0)"],
              "On the x-axis y = 0, so x + 8 = 0 and x = -8, giving A(-8, 0).", 2),
            q("Which of these points lies on the line y = -½x + 6?",
              "(8, 2)",
              ["(8, -2)", "(4, 2)", "(2, 8)"],
              "At x = 8, y = -½(8) + 6 = -4 + 6 = 2, so (8, 2) lies on the line.", 2),
            q("O is the origin and A is the point (4, 2). Find the equation of the circle with OA as a diameter.",
              "(x - 2)² + (y - 1)² = 5",
              ["(x - 4)² + (y - 2)² = 5", "(x - 2)² + (y - 1)² = √5", "(x + 2)² + (y + 1)² = 5"],
              "Centre is the midpoint (2, 1); radius² = (½ of OA)² = (½√20)² = 5.", 3),
            q("A swimming pool with a sloping bottom is filled with water flowing in at a constant rate. Which graph best shows how the depth of water changes with time? (See the figure.)",
              "Graph A",
              ["Graph B", "Graph C", "Graph D"],
              "As the pool fills, the water surface widens, so the depth rises quickly at first then more slowly — an increasing curve that flattens (concave down), which is Graph A.",
              3, image="naplan_q7_pool_graphs.png"),
        ],
    },
    {
        "strand": "Algebra",
        "topic": "Rational Expressions & Equations",
        "questions": [
            q("For which values of y is the expression 2y/(y² - 4) undefined?",
              "y = 2 and y = -2",
              ["y = 2 only", "y = 0", "y = 4 and y = -4"],
              "The denominator y² - 4 = (y - 2)(y + 2) is zero when y = ±2.", 1),
            q("Simplify (x - 2)/(x² - 4).",
              "1/(x + 2)",
              ["1/(x - 2)", "x + 2", "1/(x² - 2)"],
              "x² - 4 = (x - 2)(x + 2); cancel (x - 2).", 1),
            q("Simplify (3x - 6)/(2x² + x - 10).",
              "3/(2x + 5)",
              ["3/(2x - 5)", "3/(x - 2)", "(x - 2)/(2x + 5)"],
              "3(x - 2) over (2x + 5)(x - 2): cancel (x - 2) to get 3/(2x + 5).", 2),
            q("Simplify (6 - 2m)/(m² - 9).",
              "-2/(m + 3)",
              ["2/(m + 3)", "-2/(m - 3)", "2/(m - 3)"],
              "6 - 2m = -2(m - 3), so the fraction is -2(m - 3)/[(m - 3)(m + 3)] = -2/(m + 3).", 2),
            q("Simplify ((x² - x - 12)/(x² - 9)) × ((x² - 4x + 3)/(x² - 4x)).",
              "(x - 1)/x",
              ["x/(x - 1)", "(x + 1)/x", "(x - 1)/(x + 3)"],
              "Factor everything: (x-4)(x+3)/[(x-3)(x+3)] × (x-3)(x-1)/[x(x-4)] = (x - 1)/x.", 3),
            q("Simplify ((m² - 6m - 7)/(m² - 49)) ÷ ((m² + 8m + 7)/(m² + 7m)).",
              "m/(m + 7)",
              ["m/(m - 7)", "(m + 7)/m", "m"],
              "Invert and multiply: (m-7)(m+1)/[(m-7)(m+7)] × m(m+7)/[(m+7)(m+1)] = m/(m + 7).", 3),
            q("Simplify 3/(3x + 6) + 1/(x + 2).",
              "2/(x + 2)",
              ["1/(x + 2)", "4/(x + 2)", "3/(4x + 8)"],
              "3/(3(x + 2)) = 1/(x + 2), so the sum is 2/(x + 2).", 2),
            q("Simplify the complex fraction (2 - 4/y)/(y - 4/y).",
              "2/(y + 2)",
              ["2/(y - 2)", "(y + 2)/2", "1/(y + 2)"],
              "Multiply top and bottom by y: (2y - 4)/(y² - 4) = 2(y - 2)/[(y - 2)(y + 2)] = 2/(y + 2).", 3),
            q("Solve x/2 + 7/3 = 5/6.",
              "x = -3",
              ["x = 3", "x = -2/3", "x = 9"],
              "Multiply by 6: 3x + 14 = 5, so 3x = -9 and x = -3.", 2),
            q("Solve 5/(3x) - 1/9 = 4/x.",
              "x = -21",
              ["x = 21", "x = -3", "x = 7"],
              "Multiply by 9x: 15 - x = 36, so x = -21.", 2),
            q("Solve 2x/(x - 4) = 8/(x - 4) + 1.",
              "No solution — x = 4 is excluded",
              ["x = 4", "x = -4", "x = 12"],
              "Clearing fractions gives x = 4, but x = 4 makes the denominators zero, so it is extraneous.", 3),
            q("Solve 9/(y - 3) - 4/(y - 6) = 18/(y² - 9y + 18).",
              "y = 12",
              ["y = 6", "y = 3", "y = -12"],
              "Multiply by (y - 3)(y - 6): 9(y - 6) - 4(y - 3) = 18, so 5y - 42 = 18 and y = 12.", 3),
            q("Solve x/(x - 5) - 3/(x + 1) = 30/(x² - 4x - 5).",
              "x = -3",
              ["x = 5", "x = 5 or x = -3", "x = 3"],
              "x(x + 1) - 3(x - 5) = 30 gives x² - 2x - 15 = 0, so x = 5 or -3; x = 5 is excluded (zero denominator), leaving x = -3.", 3),
        ],
    },
    {
        "strand": "Measurement & Geometry",
        "topic": "Pythagoras' Theorem",
        "questions": [
            q("Which of these sets of side lengths forms a right-angled triangle?",
              "9, 40, 41",
              ["8, 13, 17", "4, 6, 10", "8, 12, 13"],
              "9² + 40² = 81 + 1600 = 1681 = 41², so 9, 40, 41 is a Pythagorean triad.", 1),
            q("Which of these sets of side lengths is a Pythagorean triad?",
              "15, 36, 39",
              ["2, 4, 6", "5, 5, 10", "8, 10, 12"],
              "15² + 36² = 225 + 1296 = 1521 = 39². (It is the 5-12-13 triad scaled by 3.)", 2),
            q("A right triangle has legs a = 5 and b = 7. Find the hypotenuse c, to the nearest tenth.",
              "8.6",
              ["4.9", "12.0", "74"],
              "c = √(5² + 7²) = √74 ≈ 8.6.", 1),
            q("A right triangle has leg b = 8 and hypotenuse c = 10. Find the other leg a.",
              "6",
              ["12.8", "2", "36"],
              "a = √(10² - 8²) = √36 = 6.", 1),
            q("A right triangle has leg a = 9 and hypotenuse c = 15. Find the other leg b.",
              "12",
              ["17.5", "6", "144"],
              "b = √(15² - 9²) = √144 = 12.", 1),
            q("Maria walks 6 blocks north, then 8 blocks east to Sally's house. What is the straight-line distance between the two houses?",
              "10 blocks",
              ["14 blocks", "7 blocks", "48 blocks"],
              "√(6² + 8²) = √100 = 10 blocks.", 1),
            q("Adrian stands 12 ft from the base of a 5 ft tall tree. What is the distance from Adrian's position on the ground to the top of the tree?",
              "13 ft",
              ["10.9 ft", "17 ft", "7 ft"],
              "√(12² + 5²) = √169 = 13 ft.", 1),
            q("Sofi stands 4 ft from the base of a 5 ft tall tree. What is the distance from her position to the top of the tree, to the nearest tenth?",
              "6.4 ft",
              ["3.0 ft", "9.0 ft", "41 ft"],
              "√(4² + 5²) = √41 ≈ 6.4 ft.", 2),
            q("The diagonal of a square is 10 cm. Find the perimeter of the square, to the nearest tenth.",
              "28.3 cm",
              ["40.0 cm", "20.0 cm", "14.1 cm"],
              "Each side is 10/√2 ≈ 7.07 cm, so the perimeter is 4 × 7.07 ≈ 28.3 cm.", 3),
            q("A baseball diamond is a square with 90-foot sides. What is the shortest distance between home plate and second base (the opposite corner), to the nearest tenth?",
              "127.3 ft",
              ["180.0 ft", "63.6 ft", "8100 ft"],
              "The diagonal is 90√2 ≈ 127.3 ft.", 2),
            q("A bird feeder stands vertically, and its shadow is half its height. The distance from the top of the feeder to the tip of the shadow is 19 ft. How tall is the feeder, to the nearest tenth?",
              "17.0 ft",
              ["8.5 ft", "9.5 ft", "38.0 ft"],
              "h² + (h/2)² = 19² gives 5h²/4 = 361, so h = 38/√5 ≈ 17.0 ft.", 3),
            q("On a coordinate plane, what is the distance between E(7, 2) and F(1, 9), to the nearest tenth?",
              "9.2",
              ["3.6", "13.0", "85"],
              "√((7-1)² + (2-9)²) = √(36 + 49) = √85 ≈ 9.2.", 2),
            q("A straight bike path will cut diagonally across a park that is 880 ft by 2112 ft, at a cost of $2.20 per foot. What will the path cost?",
              "$5033.60",
              ["$6582.40", "$5050.00", "$2288.00"],
              "The diagonal is √(880² + 2112²) = 2288 ft, costing 2288 × $2.20 = $5033.60.", 3),
        ],
    },
    {
        "strand": "Measurement & Geometry",
        "topic": "Trigonometry",
        "questions": [
            q("Write 75.7083° in degrees and minutes, to the nearest minute.",
              "75°42'",
              ["75°71'", "75°7'", "76°42'"],
              "0.7083 × 60 = 42.5 ≈ 42 minutes (42.498 rounds to 42).", 2),
            q("In triangle MNO, angle N is a right angle, MN = 23.1 cm and NO = 31.6 cm. Find angle MON, to the nearest minute.",
              "36°10'",
              ["53°50'", "46°50'", "36°50'"],
              "tan(MON) = 23.1/31.6, so MON = tan⁻¹(0.7310) ≈ 36.17° = 36°10'.", 2),
            q("Find the exact value of sin 45° × tan 60°.",
              "√6/2",
              ["√6", "√3/2", "√2/2"],
              "(√2/2) × √3 = √6/2.", 2),
            q("Given cos θ = √3/2 and θ is acute, find tan θ.",
              "1/√3",
              ["√3", "2/√3", "1/2"],
              "θ = 30°, and tan 30° = 1/√3.", 2),
            q("Use your calculator to find cos 32°, correct to three decimal places.",
              "0.848",
              ["0.530", "0.625", "0.999"],
              "cos 32° = 0.84804… ≈ 0.848.", 1),
            q("Given tan θ = 1.804, find θ to the nearest degree.",
              "61°",
              ["29°", "56°", "67°"],
              "θ = tan⁻¹(1.804) ≈ 61°.", 1),
            q("Evaluate tan 57°, rounded to 4 decimal places.",
              "1.5399",
              ["0.8387", "0.5446", "0.6494"],
              "tan 57° = 1.5399.", 1),
            q("Evaluate cos 123°, rounded to 4 decimal places.",
              "-0.5446",
              ["0.5446", "0.8387", "-0.8387"],
              "123° is obtuse, so its cosine is negative: cos 123° = -0.5446.", 2),
            q("Evaluate sin 360°.",
              "0",
              ["1", "-1", "Undefined"],
              "A full revolution returns to the start: sin 360° = 0.", 1),
            q("Evaluate tan 270°.",
              "Undefined",
              ["0", "1", "-1"],
              "cos 270° = 0, so tan 270° = sin/cos is undefined.", 2),
            q("Find sin⁻¹(0.8660), to the nearest degree.",
              "60°",
              ["30°", "41°", "87°"],
              "sin 60° ≈ 0.8660.", 1),
            q("Find tan⁻¹(0.2354), to one decimal place.",
              "13.2°",
              ["76.8°", "0.2°", "23.5°"],
              "tan⁻¹(0.2354) ≈ 13.2°.", 1),
            q("The area of a right triangle is 50 square units and one of its angles is 45°. Find the length of each of the two equal legs.",
              "10",
              ["5", "10√2", "25"],
              "The triangle is isosceles, so ½ × L² = 50 gives L = 10.", 2),
            q("From the top of a 200 m building, the angle of depression to the base of a second building is 20°. From the base of the first building, the angle of elevation to the top of the second building is 10°. Find the height of the second building, to one decimal place.",
              "96.9 m",
              ["200.0 m", "549.5 m", "35.3 m"],
              "Distance between buildings = 200/tan 20° ≈ 549.5 m; height = 549.5 × tan 10° ≈ 96.9 m.", 3),
            q("After flying 300 km, a jet is 48 km west of its planned flight path. By how many degrees is it off course, to one decimal place?",
              "9.2°",
              ["80.8°", "18.4°", "4.6°"],
              "The 300 km flown is the hypotenuse: sin⁻¹(48/300) ≈ 9.2°.", 2),
            q("Two boats leave the same spot; one travels 320 km due north, the other 450 km due east. Through what angle north of east must the eastbound boat turn to head toward the other boat, to one decimal place?",
              "35.4°",
              ["54.6°", "44.4°", "25.4°"],
              "tan⁻¹(320/450) ≈ 35.4°.", 2),
            q("Butch is 1.6 m tall and stands 7.2 m from a tree. The angle of inclination from the top of his head to the tip of the tree is 48°. How tall is the tree, to one decimal place?",
              "9.6 m",
              ["8.0 m", "12.3 m", "6.9 m"],
              "Height above his head = 7.2 × tan 48° ≈ 8.0 m; total = 8.0 + 1.6 = 9.6 m.", 2),
            q("A train passenger travelling due north sees a light due east at 9:00 pm. By 9:45 pm the train has travelled 120 km and the light is on a bearing of 150°T from the passenger. How far is the light from the passenger at 9:45 pm (exact value)?",
              "80√3 km",
              ["40√3 km", "120 km", "60√2 km"],
              "The bearing makes a 30° angle with due south, so the distance is 120/cos 30° = 80√3 km.", 3),
            q("Write the exact value of tan 45° × cos 45°.",
              "√2/2",
              ["1", "√2", "√3/2"],
              "tan 45° = 1 and cos 45° = √2/2, so the product is √2/2.", 2),
            q("Solve for x: cos x° = sin 35°.",
              "55",
              ["35", "45", "65"],
              "cos x° = sin(90° - x°), so 90 - x = 35 and x = 55 (sine and cosine are complementary).", 2),
            q("If sin θ = 3/7, find the exact value of tan θ (θ acute).",
              "3√10/20",
              ["3/7", "7/3", "3/4"],
              "Adjacent = √(7² - 3²) = √40 = 2√10, so tan θ = 3/(2√10) = 3√10/20.", 3),
            q("What is the true bearing of P from Q? (See the figure.)",
              "296°T",
              ["116°T", "064°T", "244°T"],
              "From the figure, P is on a bearing of 116°T from Q's line; the reverse bearing (P from Q) is 116° + 180° = 296°T, i.e. N64°W.",
              2, image="naplan_q2_bearing.png"),
            q("Find the value of y, to two decimal places. (See the right-angled triangle.)",
              "79.35 m",
              ["109.21 m", "185.80 m", "95.34 m"],
              "The right angle is at the apex, so the 135 m side is the hypotenuse. y is adjacent to the 54° angle: y = 135 cos 54° ≈ 79.35 m.",
              2, image="naplan_q16_right_triangle.png"),
            q("The diagram shows a sloping advertising board. The board is 410 cm long and stands 313 cm above the ground. Find the angle θ between the board and the ground, to the nearest degree.",
              "50°",
              ["40°", "37°", "53°"],
              "sin θ = 313/410 = 0.763, so θ = sin⁻¹(0.763) ≈ 50°.",
              2, image="naplan_q9_advertising_board.png"),
        ],
    },
    {
        "strand": "Measurement & Geometry",
        "topic": "Measurement",
        "questions": [
            q("Which of these areas is equivalent to 4 cm²?",
              "400 mm²",
              ["40 mm²", "0.4 mm²", "0.04 mm²"],
              "1 cm² = 100 mm², so 4 cm² = 400 mm².", 1),
            q("A cylinder has height 9 cm and radius 3 cm. A slice with a 20° angle at the centre is cut out and removed. What is the exact volume of the remaining shape?",
              "153π/2 cm³",
              ["81π cm³", "9π/2 cm³", "153π cm³"],
              "The full cylinder is 81π cm³; the remaining fraction is 340/360 = 17/18, giving 81π × 17/18 = 153π/2 cm³.", 3),
            q("An area of 3 m² is to be paved with parallelogram-shaped tiles, each with base 20 cm and perpendicular height 10 cm. How many tiles are needed?",
              "150",
              ["15", "1500", "75"],
              "Each tile is 200 cm²; 30 000 cm² ÷ 200 cm² = 150 tiles.", 2),
            q("Bicycle wheels have a diameter of 50 cm. How far does the bike travel if the wheels turn 400 times? (Answer to the nearest metre.)",
              "628 m",
              ["314 m", "1257 m", "200 m"],
              "One turn covers π × 0.5 m ≈ 1.571 m; 400 turns cover ≈ 628 m.", 2),
            q("The mass of a pet cat would most likely be about:",
              "4 kg",
              ["4 g", "4 t", "400 g"],
              "A typical adult cat weighs around 4 kilograms.", 1),
            q("A paper doily has rotational symmetry of order 9. If one full sector is cut out, what is the angle of the sector at the centre?",
              "40°",
              ["9°", "36°", "45°"],
              "360° ÷ 9 = 40°.", 2),
            q("Express 2 pm in 24-hour time.",
              "14:00",
              ["02:00", "12:00", "20:00"],
              "Afternoon times add 12 hours: 2 + 12 = 14:00.", 1),
            q("What is the angle between the hour hand and the minute hand of an analogue clock at exactly 2:00?",
              "60°",
              ["30°", "75°", "90°"],
              "The hour hand is 2/12 of the way around: 2/12 × 360° = 60°.", 2),
            q("At 2:00 the hands of a clock are 60° apart. What is the least time until the angle between the hands is again 60°?",
              "21 9/11 minutes (about 21 min 49 s)",
              ["20 minutes", "24 minutes", "10 10/11 minutes"],
              "The minute hand gains 5.5° per minute and must gain 120°: 120/5.5 = 21 9/11 minutes.", 3),
            q("A cube has a surface area of 150 cm². What is the side length of the cube?",
              "5 cm",
              ["25 cm", "5.5 cm", "12.5 cm"],
              "A cube has 6 faces, so 6a² = 150, a² = 25 and a = 5 cm.", 2),
            q("The circumference of a circle increases from π units to 2π units. By how much does its area increase?",
              "3π/4 square units",
              ["π/4 square units", "π square units", "3π square units"],
              "C = π gives r = ½ and area π/4; C = 2π gives r = 1 and area π. The increase is π - π/4 = 3π/4.", 3),
            q("A solid cone has a diameter of 3.4 cm and a perpendicular height of 1.5 cm. Calculate its slant height, to two decimal places.",
              "2.27 cm",
              ["1.85 cm", "5.14 cm", "3.70 cm"],
              "Radius = 1.7 cm, so slant height = √(1.7² + 1.5²) = √5.14 ≈ 2.27 cm.", 2),
            q("A solid cone has radius 1.7 cm and slant height 2.27 cm. Calculate its total surface area, to two decimal places.",
              "21.20 cm²",
              ["12.12 cm²", "9.08 cm²", "24.22 cm²"],
              "Total surface area = πr² + πrl = π(1.7²) + π(1.7)(2.27) ≈ 9.08 + 12.12 = 21.20 cm².", 3),
        ],
    },
    {
        "strand": "Measurement & Geometry",
        "topic": "Angles & Quadrilaterals",
        "questions": [
            q("Which of the following statements is true?",
              "Every parallelogram is a trapezium (using the inclusive definition)",
              ["Every quadrilateral with perpendicular diagonals is a rhombus", "Every trapezium is a parallelogram", "Every rhombus is a square"],
              "A trapezium needs at least one pair of parallel sides, which every parallelogram has. A kite has perpendicular diagonals but is not a rhombus.", 2),
            q("What is the supplementary angle to 84°45'?",
              "95°15'",
              ["5°15'", "95°55'", "96°15'"],
              "Supplementary angles sum to 180°: 180° - 84°45' = 95°15'.", 2),
            q("Using the inclusive definition of a trapezium, which of these quadrilaterals is NOT necessarily a trapezium?",
              "A kite",
              ["A rectangle", "A square", "A parallelogram"],
              "Rectangles, squares and parallelograms all have a pair of parallel sides; a kite need not.", 3),
            q("A quadrilateral has perpendicular diagonals but is not a rhombus. Which of these could it be?",
              "A kite",
              ["A square", "A rectangle", "A parallelogram that is not a rhombus"],
              "A (non-rhombic) kite has perpendicular diagonals; a rectangle's or general parallelogram's diagonals are not perpendicular, and a square is a rhombus.", 2),
            q("Find the size of each interior angle of a regular 12-sided polygon.",
              "150°",
              ["165°", "30°", "144°"],
              "Interior angle = (n - 2) × 180° / n = 10 × 180° / 12 = 150°.", 2),
            q("A quadrilateral has diagonals that intersect at right angles. Which of these must it be?",
              "A kite",
              ["A rectangle", "A parallelogram", "All of the above"],
              "A kite (and a rhombus/square, which are special kites) has perpendicular diagonals; a general rectangle or parallelogram does not.", 2),
            q("ABCD is the parallelogram shown (not to scale), with angles of 100° and 150° marked. Find the value of x.",
              "70",
              ["50", "30", "90"],
              "Using the marked 100° and 150° angles and the straight line at the top vertex, the exterior angle x works out to 70°.",
              2, image="naplan_q6_parallelogram.png"),
            q("Lines CD and AB are parallel, cut by two transversals as shown, with an angle of 113° marked at Q. Find the value of x.",
              "46",
              ["67", "113", "34"],
              "The 113° angle and its co-interior partner give 67° at P; the marked equal sides make the triangle isosceles, leaving x = 46°.",
              3, image="naplan_q14_parallel_lines.png"),
        ],
    },
    {
        "strand": "Statistics & Probability",
        "topic": "Probability & Statistics",
        "questions": [
            q("Four friends throw the same biased coin. Heads/tails results: Ben 34/8, Helen 66/12, Paul 80/40, Sharif 120/40. Whose results give the best estimate of the probability of heads?",
              "Sharif's, because he threw the coin the most times",
              ["Ben's, because he has the highest proportion of heads", "Paul's, because his sample is the most balanced", "Helen's, because her results are in simplest ratio"],
              "More trials give a more reliable relative frequency; Sharif threw 160 times, the most of anyone.", 2),
            q("Combining all the results in the table gives 300 heads from 400 throws. If the coin is thrown twice more, what is the best estimate of the probability it lands heads both times?",
              "9/16",
              ["3/4", "1/4", "3/8"],
              "P(heads) ≈ 300/400 = 3/4, so P(two heads) = (3/4)² = 9/16.", 2),
            q("The weights of 40 babies: 2<w≤3 kg: 12 babies; 3<w≤4: 16; 4<w≤5: 9; 5<w≤6: 2; 6<w≤7: 1. What is the modal class?",
              "3 < w ≤ 4",
              ["2 < w ≤ 3", "4 < w ≤ 5", "16"],
              "The class with the highest frequency (16 babies) is 3 < w ≤ 4.", 1),
            q("Using the same table of 40 babies (midpoints 2.5, 3.5, 4.5, 5.5, 6.5 kg with frequencies 12, 16, 9, 2, 1), estimate the mean weight.",
              "3.6 kg",
              ["3.5 kg", "4.5 kg", "4.0 kg"],
              "(2.5×12 + 3.5×16 + 4.5×9 + 5.5×2 + 6.5×1)/40 = 144/40 = 3.6 kg.", 2),
            q("One of the 40 babies is chosen at random. What is the probability that it weighs more than 5 kg?",
              "3/40",
              ["1/40", "1/20", "7/40"],
              "2 + 1 = 3 babies weigh more than 5 kg, so the probability is 3/40.", 1),
            q("Allen finds the mode, median and range of 110, 114, 114, 115, 116, 117, 118. He then adds the value 90 to the data set. Which statistics change?",
              "Only the median and the range",
              ["Only the mode and the median", "Only the mode and the range", "The mode, median and range all change"],
              "The mode stays 114; the median moves from 115 to 114.5; the range grows from 8 to 28.", 2),
            q("Which of these events does NOT have an equal chance of happening and not happening?",
              "Throwing a two with a fair six-sided die",
              ["Tossing a tail with a fair coin", "Throwing an odd number with a fair die", "Drawing a red card from a standard 52-card pack"],
              "P(two) = 1/6, while the other three events all have probability 1/2.", 2),
            q("Q = {1, 2, 3, 4}. Which of these sets P satisfies P ∪ Q = {1, 2, 3, 4, 5, 6}?",
              "{5, 6}",
              ["{4, 5}", "{6}", "{5, 6, 7}"],
              "P must supply 5 and 6 and nothing outside {1,…,6}: P = {5, 6} works.", 2),
        ],
    },
]  # END BANK


# ---------------------------------------------------------------------------
# Numeric-equality guard: no distractor may be mathematically equal to the
# correct answer (e.g. 1/2 vs 2/4, 1.13 vs 1.130).
# ---------------------------------------------------------------------------

_NUM_RE = re.compile(
    r'^[\s$]*(-?\d[\d\s,]*(?:\.\d+)?)\s*'      # number (allows thousand spaces)
    r'(?:/\s*(-?\d+(?:\.\d+)?))?\s*'           # optional fraction denominator
    r'([%a-zA-Z°²³/\s]*)$'                     # optional unit suffix
)


def numeric_value(text):
    """Best-effort parse of an option as (value, unit).  Handles $, %,
    units and simple fractions.  Returns None when not numeric.  Two
    options only count as 'mathematically equal' when both value and
    unit match, so '2xy' vs '2xy²' or '31c' vs '$310' are not conflated.
    """
    m = _NUM_RE.match(text)
    if not m:
        return None
    num = m.group(1).replace(',', '').replace(' ', '')
    try:
        val = Fraction(num)
    except (ValueError, ZeroDivisionError):
        return None
    if m.group(2):
        try:
            val = val / Fraction(m.group(2))
        except (ValueError, ZeroDivisionError):
            return None
    unit = re.sub(r'\s+', '', (m.group(3) or '')).lower()
    return (val, unit)


def validate_topic(topic):
    errors = []
    for i, qd in enumerate(topic["questions"], 1):
        label = f'{topic["topic"]} Q{i}'
        opts = [qd["correct"]] + qd["wrong"]
        if len(qd["wrong"]) < 2:
            errors.append(f'{label}: fewer than 3 options')
        norm = [re.sub(r'\s+', ' ', o.strip().lower()) for o in opts]
        if len(set(norm)) != len(norm):
            errors.append(f'{label}: duplicate option text')
        cval = numeric_value(qd["correct"])
        if cval is not None:
            for w in qd["wrong"]:
                wval = numeric_value(w)
                if wval is not None and wval == cval:
                    errors.append(
                        f'{label}: distractor "{w}" equals correct "{qd["correct"]}"')
        if not qd["question_text"].strip():
            errors.append(f'{label}: empty question_text')
        if not qd["explanation"].strip():
            errors.append(f'{label}: empty explanation')
        if qd.get("image") and not (IMAGES_DIR / qd["image"]).exists():
            errors.append(f'{label}: image "{qd["image"]}" not found in images/')
    return errors


# The upload parser sanitises image filenames with re.sub(r'[^\w.\-]', '_', name)
# and only matches q["image"] against names present in the ZIP, so we store the
# already-sanitised name in the JSON and under that name in the ZIP.
def safe_image_name(name):
    return re.sub(r'[^\w.\-]', '_', name)


def build_payload(topic):
    questions = []
    for qd in topic["questions"]:
        options = [(qd["correct"], True)] + [(w, False) for w in qd["wrong"]]
        # Deterministic per-question shuffle so the correct answer is not
        # always option A.
        rng = random.Random(qd["question_text"])
        rng.shuffle(options)
        question = {
            "question_text": qd["question_text"],
            "question_type": "multiple_choice",
            "difficulty": qd["difficulty"],
            "points": qd["points"],
            "explanation": qd["explanation"],
            "answers": [
                {"text": text, "is_correct": is_correct, "order": n}
                for n, (text, is_correct) in enumerate(options, start=1)
            ],
        }
        if qd.get("image"):
            question["image"] = safe_image_name(qd["image"])
        questions.append(question)
    return {
        "subject": "maths",
        "strand": topic["strand"],
        "topic": topic["topic"],
        "year_level": YEAR_LEVEL,
        "questions": questions,
    }


def post_validate(payload, label):
    """Validate the final JSON payload the way the upload parser would."""
    errors = []
    for i, qd in enumerate(payload["questions"], 1):
        answers = qd["answers"]
        n_correct = sum(1 for a in answers if a["is_correct"])
        if n_correct != 1:
            errors.append(f'{label} Q{i}: {n_correct} correct answers')
        texts = [re.sub(r'\s+', ' ', a["text"].strip().lower()) for a in answers]
        if len(set(texts)) != len(texts):
            errors.append(f'{label} Q{i}: duplicate options')
        if not all(a["order"] >= 1 for a in answers):
            errors.append(f'{label} Q{i}: order must be 1-based')
    return errors


def main():
    all_errors = []
    summary = []
    for topic in BANK:
        all_errors.extend(validate_topic(topic))

    if all_errors:
        for e in all_errors:
            print('ERROR:', e)
        sys.exit(1)

    for topic in BANK:
        payload = build_payload(topic)
        slug = re.sub(r'[^a-z0-9]+', '_', topic["topic"].lower()).strip('_')
        all_errors.extend(post_validate(payload, topic["topic"]))

        json_path = OUT_DIR / f'{slug}.json'
        json_bytes = json.dumps(payload, ensure_ascii=False, indent=2).encode('utf-8')
        json_path.write_bytes(json_bytes)

        # Images referenced by questions in this topic (deduplicated).
        images = []
        seen = set()
        for qd in topic["questions"]:
            if qd.get("image") and qd["image"] not in seen:
                seen.add(qd["image"])
                images.append(qd["image"])

        zip_path = OUT_DIR / f'{slug}.zip'
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
            zf.writestr('questions.json', json_bytes)
            for img in images:
                zf.write(IMAGES_DIR / img, safe_image_name(img))
        zip_path.write_bytes(buf.getvalue())

        summary.append((topic["strand"], topic["topic"],
                        len(payload["questions"]), len(images), slug))

    if all_errors:
        for e in all_errors:
            print('ERROR:', e)
        sys.exit(1)

    total = 0
    total_imgs = 0
    for strand, name, count, n_imgs, slug in summary:
        extra = f' (+{n_imgs} img)' if n_imgs else ''
        print(f'{strand:24s} {name:45s} {count:3d} q{extra} -> {slug}.json/.zip')
        total += count
        total_imgs += n_imgs
    print(f'{"TOTAL":70s} {total:4d} q, {total_imgs} images')


if __name__ == '__main__':
    main()
