# Generated by Django 4.2.13 on 2026-08-24 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPointsTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="Sum of every PointsAward for this student. Indexed — the rank query counts rows above this value.",
                    ),
                ),
                (
                    "units_completed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many units of work the student has scored on.",
                    ),
                ),
                (
                    "is_ranked",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False for non-students (a teacher trying a quiz), so they never appear on or displace anyone from the board.",
                    ),
                ),
                ("last_earned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "leaderboard_shown_on",
                    models.DateField(
                        blank=True,
                        help_text="Local date the standings pop-up was last shown. Gates the once-a-day modal; stored here rather than in the session so it holds across devices and browsers.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_total",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-total_points", "student_id"],
                "indexes": [
                    models.Index(
                        fields=["is_ranked", "-total_points"],
                        name="rewards_total_board_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PointsAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("maths_quiz", "Subject quiz"),
                            ("basic_facts", "Basic facts"),
                            ("times_tables", "Times tables"),
                            ("homework", "Homework"),
                            ("coding_problem", "Coding problem"),
                            ("coding_exercise", "Coding exercise"),
                            ("worksheet", "Worksheet"),
                            ("number_puzzle", "Number puzzle"),
                            ("brainbuzz", "BrainBuzz"),
                        ],
                        db_index=True,
                        help_text="Which activity this unit of work belongs to.",
                        max_length=32,
                    ),
                ),
                (
                    "unit_key",
                    models.CharField(
                        help_text="Identifies the unit within its source, e.g. a homework id or a 'topic:7:level:3' pair. Opaque outside rewards.services.",
                        max_length=120,
                    ),
                ),
                (
                    "points",
                    models.FloatField(
                        default=0.0,
                        help_text="Best score on this unit so far, normalised to 0–100.",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Human-readable name of the unit, for "where did my points come from" views. Never used for identity.',
                        max_length=160,
                    ),
                ),
                ("first_earned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-points", "source"],
                "indexes": [
                    models.Index(
                        fields=["student", "source"], name="rewards_award_stu_src_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pointsaward",
            constraint=models.UniqueConstraint(
                fields=("student", "source", "unit_key"),
                name="rewards_award_unique_unit",
            ),
        ),
    ]
