# Generated by Django 4.2.13 on 2026-03-30 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0070_add_billing_type_to_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 = unlimited attempts')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, help_text='When to auto-publish (for scheduled status).', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When this homework was actually published to students.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = soft-deleted (hidden from all users).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='classroom.classroom')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='classroom.topic')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False, help_text='Computed on save: submitted_at > homework.due_date')),
                ('content', models.TextField(blank=True, help_text="Student's written answer.")),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/submissions/%Y/%m/')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False, help_text='Controls whether student can see the grade.')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempt_number'],
                'indexes': [models.Index(fields=['student', 'homework'], name='homework_ho_student_13130f_idx')],
                'unique_together': {('homework', 'student', 'attempt_number')},
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['due_date', 'is_active'], name='homework_ho_due_dat_889af8_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['status', 'scheduled_publish_at'], name='homework_ho_status_efd624_idx'),
        ),
    ]
