# Generated by Django 4.2.13 on 2026-04-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0072_term_holidays'),
        ('maths', '0016_add_video_and_answer_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('homework_type', models.CharField(choices=[('topic', 'Topic Quiz'), ('mixed', 'Mixed Quiz')], default='topic', max_length=20)),
                ('num_questions', models.PositiveIntegerField(default=10)),
                ('due_date', models.DateTimeField()),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited attempts.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='classroom.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homework', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, related_name='homework_assignments', to='classroom.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('points', models.FloatField(default=0.0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('homework', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_student_answers', to='maths.question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maths.answer')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='homework.homeworksubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_questions', to='homework.homework')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_question_entries', to='maths.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('homework', 'question')},
            },
        ),
    ]
