# Generated by Django 4.2.13 on 2026-03-31 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0016_add_video_and_answer_image'),
        ('classroom', '0075_delete_holiday'),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('pdf', 'PDF Upload'), ('note', 'Note / Message')], default='quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='homework',
            name='min_score_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum score % for quiz homework (informational).', null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='num_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to select for quiz homework.', null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='quiz_level',
            field=models.ForeignKey(blank=True, help_text='Level for quiz questions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_homeworks', to='classroom.level'),
        ),
        migrations.AddField(
            model_name='homework',
            name='quiz_topics',
            field=models.ManyToManyField(blank=True, help_text='Topics/subtopics for quiz-type homework.', related_name='quiz_homeworks', to='classroom.topic'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher_attachment',
            field=models.FileField(blank=True, help_text="Teacher's worksheet/instructions (PDF type).", null=True, upload_to='homework/teacher_files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='is_auto_completed',
            field=models.BooleanField(default=False, help_text='True when auto-created by quiz completion or mark-as-done.'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='quiz_result',
            field=models.ForeignKey(blank=True, help_text='Direct link to quiz result for score retrieval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_submissions', to='maths.studentfinalanswer'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='quiz_session_id',
            field=models.CharField(blank=True, default='', help_text='Quiz session UUID for linking back to quiz flow.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homework',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Primary topic (used for classification/filtering).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='classroom.topic'),
        ),
        migrations.CreateModel(
            name='HomeworkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_questions', to='homework.homework')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='maths.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('homework', 'question')},
            },
        ),
    ]
