# Generated by Django 4.2.13 on 2026-04-23 09:48
# Manually edited to interleave a data migration between the new-column adds
# and the unique_together re-add — without it every existing row would share
# content_id=0 and the new unique constraint would fail.

from django.db import migrations, models
import django.db.models.deletion


def backfill_subject_slug_and_content_id(apps, schema_editor):
    """Fill ``subject_slug`` + ``content_id`` on existing maths homework rows.

    Every row that exists before Phase 2 is maths — the legacy ``question`` FK
    points to ``maths.Question``. We copy that pk into ``content_id`` and stamp
    ``subject_slug='mathematics'`` so the unique constraint
    ``(homework, subject_slug, content_id)`` / ``(submission, ...)`` can land.
    """
    HomeworkQuestion = apps.get_model('homework', 'HomeworkQuestion')
    HomeworkStudentAnswer = apps.get_model('homework', 'HomeworkStudentAnswer')
    Homework = apps.get_model('homework', 'Homework')

    # HomeworkQuestion
    for hq in HomeworkQuestion.objects.all().iterator():
        if hq.question_id:
            hq.content_id = hq.question_id
            hq.subject_slug = 'mathematics'
            hq.save(update_fields=['content_id', 'subject_slug'])

    # HomeworkStudentAnswer
    for ha in HomeworkStudentAnswer.objects.all().iterator():
        if ha.question_id:
            ha.content_id = ha.question_id
            ha.subject_slug = 'mathematics'
            ha.save(update_fields=['content_id', 'subject_slug'])

    # Homework — always maths today
    Homework.objects.filter(subject_slug='').update(subject_slug='mathematics')


def reverse_noop(apps, schema_editor):
    """Backfill is forward-only — new fields get dropped on reverse anyway."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0017_cleanup_orphaned_questions'),
        ('coding', '0012_add_exercise_uses_browser_sandbox'),
        ('homework', '0007_reapply_legacy_schema_fixes'),
    ]

    operations = [
        # ── Drop old unique_together constraints first ─────────────────────
        migrations.AlterUniqueTogether(
            name='homeworkquestion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='homeworkstudentanswer',
            unique_together=set(),
        ),
        # ── Add the new fields ─────────────────────────────────────────────
        migrations.AddField(
            model_name='homework',
            name='coding_topics',
            field=models.ManyToManyField(
                blank=True, related_name='homework_assignments', to='coding.codingtopic',
            ),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject_slug',
            field=models.CharField(
                db_index=True, default='mathematics',
                help_text='Which subject-plugin owns this homework — drives topic picker, item rendering and grading via classroom.subject_registry.',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='content_id',
            field=models.PositiveIntegerField(
                default=0,
                help_text='pk of the underlying content row (maths.Question.id, coding.CodingExercise.id, ...).',
            ),
        ),
        migrations.AddField(
            model_name='homeworkquestion',
            name='subject_slug',
            field=models.CharField(
                db_index=True, default='mathematics',
                help_text='Binds to classroom.subject_registry plugin slug.',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='answer_data',
            field=models.JSONField(
                blank=True, default=dict,
                help_text='Plugin-specific answer payload (e.g. submitted code, run output).',
            ),
        ),
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='content_id',
            field=models.PositiveIntegerField(
                default=0,
                help_text='pk of the underlying content row (maths.Question.id, coding.CodingExercise.id, ...).',
            ),
        ),
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='subject_slug',
            field=models.CharField(
                db_index=True, default='mathematics',
                help_text='Binds to classroom.subject_registry plugin slug.',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='question',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='homework_question_entries', to='maths.question',
            ),
        ),
        migrations.AlterField(
            model_name='homeworkstudentanswer',
            name='question',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='homework_student_answers', to='maths.question',
            ),
        ),
        # ── Backfill new fields from the legacy maths FK ───────────────────
        migrations.RunPython(backfill_subject_slug_and_content_id, reverse_noop),
        # ── Now the new unique constraints can safely land ─────────────────
        migrations.AlterUniqueTogether(
            name='homeworkquestion',
            unique_together={('homework', 'subject_slug', 'content_id')},
        ),
        migrations.AlterUniqueTogether(
            name='homeworkstudentanswer',
            unique_together={('submission', 'subject_slug', 'content_id')},
        ),
    ]
