"""Add HomeworkUploadSession, pdf_upload homework type, and review fields to HomeworkStudentAnswer."""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_reapply_legacy_schema_fixes'),
        ('classroom', '0086_parentstudent_school_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # HomeworkUploadSession model
        migrations.CreateModel(
            name='HomeworkUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_filename', models.CharField(max_length=255)),
                ('homework_title', models.CharField(blank=True, max_length=200)),
                ('extracted_data', models.JSONField(default=dict)),
                ('extracted_images', models.JSONField(default=dict)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='classroom.classroom',
                    help_text='Pre-selected classroom target, set at upload time.',
                )),
                ('homework', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='upload_sessions',
                    to='homework.homework',
                )),
                ('school', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='classroom.school',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='homework_upload_sessions',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={'ordering': ['-created_at']},
        ),

        # Add pdf_upload to Homework.homework_type choices
        migrations.AlterField(
            model_name='homework',
            name='homework_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('topic', 'Topic Quiz'),
                    ('mixed', 'Mixed Quiz'),
                    ('pdf_upload', 'PDF Upload'),
                ],
                default='topic',
            ),
        ),

        # Review fields on HomeworkStudentAnswer
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='review_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('auto_graded', 'Auto Graded'),
                    ('pending_ai', 'Pending AI Review'),
                    ('ai_graded', 'AI Graded'),
                    ('pending_teacher', 'Pending Teacher Review'),
                    ('teacher_graded', 'Teacher Graded'),
                ],
                default='auto_graded',
            ),
        ),
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='Feedback generated by Claude when grading this answer.'),
        ),
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='ai_score_fraction',
            field=models.FloatField(
                blank=True, null=True,
                help_text='Claude confidence score 0.0–1.0. Multiplied by question points.',
            ),
        ),
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='teacher_feedback',
            field=models.TextField(blank=True, help_text='Feedback written by the teacher when manually grading.'),
        ),
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='graded_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='graded_homework_answers',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='homeworkstudentanswer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
