# Generated by Django 4.2.13 on 2026-05-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_alter_homeworkquestion_unique_together_and_more'),
        ('homework', '0009_ai_grading_cache'),
    ]

    operations = [
    ]
