# Generated by Django 4.2.13 on 2026-05-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0026_upload_session_async_fields'),
        ('homework', '0010_merge_20260510_2233'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aigradingcache',
            name='unique_grading_cache_entry',
        ),
        migrations.AddField(
            model_name='homeworkuploadsession',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworkuploadsession',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Stored temporarily while AI extraction runs in the background.', null=True, upload_to='homework_uploads/'),
        ),
        migrations.AddField(
            model_name='homeworkuploadsession',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='processing', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='aigradingcache',
            unique_together={('question', 'normalised_answer')},
        ),
    ]
