# Generated by Django 4.2.13 on 2026-05-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0011_upload_session_async_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigradingcache',
            name='human_verified',
            field=models.BooleanField(default=False, help_text='True when a teacher manually graded this answer — used as a golden example.'),
        ),
    ]
