# Generated by Django 5.2.8 on 2026-05-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_merge_20260511_1142'),
        ('homework', '0011_upload_session_async_fields'),
    ]

    operations = [
    ]
