# Generated by Django 4.2.13 on 2026-05-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0012_ai_grading_cache_human_verified'),
        ('homework', '0012_merge_20260511_1752'),
    ]

    operations = [
    ]
