# Generated by Django 4.2.13 on 2026-05-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0013_merge_cpp267'),
        ('homework', '0013_merge_homework_leaf_nodes'),
        ('homework', '0013_merge_homework_leaves'),
    ]

    operations = [
    ]
