# Generated by Django 4.2.13 on 2026-05-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0013_merge_20260515_1202'),
        ('homework', '0014_merge_20260516_1104'),
    ]

    operations = [
    ]
