# Generated by Django 5.2.8 on 2026-05-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0013_merge_20260515_1202'),
        ('homework', '0013_merge_20260518_1346'),
        ('homework', '0014_merge_20260516_1104'),
    ]

    operations = [
    ]
