# Generated by Django 5.2.8 on 2026-05-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_merge_20260518_1646'),
        ('homework', '0015_merge_20260519_1154'),
    ]

    operations = [
    ]
