# Generated by Django 4.2.13 on 2026-06-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0016_merge_20260520_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkuploadsession',
            name='shape_naming',
            field=models.BooleanField(default=False, help_text='Name-the-shape mode: AI generates one "name this shape" question per shape.'),
        ),
    ]
