# Generated by Django 4.2.13 on 2026-06-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0016_merge_20260520_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='When this homework should automatically go live. Leave blank to publish immediately on creation. A future value schedules it — students see nothing and get no email until then.', null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Set when the homework actually went live. This is the single gate for student visibility and the publish notification email.', null=True),
        ),
    ]
