# Generated by Django 4.2.13 on 2026-06-13 23:12
#
# Made idempotent (2026-06-14): the original two AddField operations crash with
# "Duplicate column name" on environments where one of these columns already
# exists (e.g. a half-applied run — MySQL auto-commits DDL, so a failure on the
# second AddField leaves the first column behind with the migration unrecorded;
# and prod already had `published_at` from an earlier schema state). We now add
# each column only if it is missing, while keeping Django's migration *state*
# unchanged via SeparateDatabaseAndState so the model fields stay tracked.

from django.db import migrations, models


_PUBLISH_AT = models.DateTimeField(
    blank=True, null=True,
    help_text='When this homework should automatically go live. Leave blank to '
              'publish immediately on creation. A future value schedules it — '
              'students see nothing and get no email until then.',
)
_PUBLISHED_AT = models.DateTimeField(
    blank=True, null=True,
    help_text='Set when the homework actually went live. This is the single gate '
              'for student visibility and the publish notification email.',
)

_COLUMNS = (
    ('publish_at', 'datetime(6) NULL'),
    ('published_at', 'datetime(6) NULL'),
)


def _add_missing_columns(apps, schema_editor):
    """Add publish_at / published_at to homework_homework only if absent."""
    conn = schema_editor.connection
    table = 'homework_homework'
    with conn.cursor() as cur:
        cur.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = DATABASE() AND table_name = %s",
            [table],
        )
        existing = {row[0] for row in cur.fetchall()}
    for name, ddl in _COLUMNS:
        if name not in existing:
            schema_editor.execute(
                f"ALTER TABLE {table} ADD COLUMN {name} {ddl}"
            )


def _noop_reverse(apps, schema_editor):
    """No-op on reverse — column drops are handled by Django's state side."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0016_merge_20260520_1011'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_missing_columns, _noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='homework', name='publish_at', field=_PUBLISH_AT,
                ),
                migrations.AddField(
                    model_name='homework', name='published_at', field=_PUBLISHED_AT,
                ),
            ],
        ),
    ]
