# Generated by Django 4.2.13 on 2026-06-14 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0017_homeworkuploadsession_shape_naming'),
        ('homework', '0018_backfill_published_at'),
    ]

    operations = [
    ]
