# Generated by Django 4.2.13 on 2026-06-20 01:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0022_homework_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='homework',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
