# Generated by Django 4.2.13 on 2026-06-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0017_cpp316_language_topic_levels'),
        ('homework', '0023_alter_homework_options_alter_homework_managers'),
    ]

    operations = [
    ]
