# Generated by Django 4.2.13 on 2026-07-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0024_cpp316_language_topic_levels'),
        ('homework', '0024_merge_20260625_0832'),
    ]

    operations = [
    ]
