# Generated by Django 4.2.13 on 2026-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0024_homework_json_upload_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkuploadsession",
            name="progress_message",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="homeworkuploadsession",
            name="progress_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
