# Generated by Django 4.2.13 on 2026-08-29 23:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0120_repair_classroom_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("homework", "0026_homeworkuploadsession_page_selection"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_slug",
                    models.CharField(
                        db_index=True,
                        default="mathematics",
                        help_text="Which subject-plugin owns this schedule — drives the topic picker and question selection via classroom.subject_registry.",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("year", "Academic year"),
                            ("term", "Term"),
                            ("custom", "Custom date range"),
                        ],
                        default="term",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "release_weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                        help_text="Day of the week each set goes live.",
                    ),
                ),
                (
                    "release_time",
                    models.TimeField(
                        default=datetime.time(8, 0),
                        help_text="Time of day each set goes live (school local time).",
                    ),
                ),
                (
                    "due_days",
                    models.PositiveSmallIntegerField(
                        default=7, help_text="Due date = release + this many days."
                    ),
                ),
                (
                    "lead_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Build each set this many days before its release, so the teacher can preview, edit or delete it before students ever see it.",
                    ),
                ),
                ("num_questions", models.PositiveIntegerField(default=10)),
                (
                    "question_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional single question type to draw; blank means any type.",
                        max_length=30,
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for unlimited attempts.",
                        null=True,
                    ),
                ),
                (
                    "avoid_repeat_weeks",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Do not reuse questions this class has already had in the last N weeks. 0 disables the check. When the topic bank is too small to honour it the set is topped up with repeats rather than coming out short.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to pause generation without deleting the plan.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_schedules",
                        to="classroom.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_schedules",
                        to="classroom.classroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_question_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_schedules",
                        to="classroom.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField()),
                (
                    "week_start_date",
                    models.DateField(help_text="Monday of this teaching week."),
                ),
                (
                    "week_end_date",
                    models.DateField(help_text="Sunday of this teaching week."),
                ),
                (
                    "topic_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Plugin topic ids planned for this week.",
                    ),
                ),
                ("topic_labels", models.JSONField(blank=True, default=list)),
                (
                    "num_questions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override the schedule's question count for this week only.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "skip_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Why this week was created inactive (e.g. a school holiday).",
                        max_length=200,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generated", "Generated"),
                            ("skipped", "Skipped"),
                            ("no_content", "No questions found"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generation_message", models.TextField(blank=True, default="")),
                (
                    "generated_homework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="homework.homework",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="homework.questionschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number"],
                "indexes": [
                    models.Index(
                        fields=["schedule", "week_start_date"],
                        name="homework_sc_schedul_987ede_idx",
                    )
                ],
                "unique_together": {("schedule", "week_number")},
            },
        ),
        migrations.AddIndex(
            model_name="questionschedule",
            index=models.Index(
                fields=["classroom", "subject_slug"],
                name="homework_qu_classro_806fcf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionschedule",
            index=models.Index(
                fields=["is_active", "start_date"],
                name="homework_qu_is_acti_c604da_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionschedule",
            unique_together={("classroom", "subject_slug", "name")},
        ),
    ]
