# Generated by Django 4.2.13 on 2026-09-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0025_merge_20260703_2134'),
        ('homework', '0027_questionschedule_scheduleweek_and_more'),
    ]

    operations = [
    ]
