# Generated by Django 4.2.13 on 2026-09-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0028_reconcile_submission_score_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkdraft",
            name="art_picture_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which classroom.progress_art picture this student is drawing as they work through this homework. Stored rather than re-derived so a paper resumed days later continues the SAME drawing, even if the picture library has gained or lost entries meanwhile. How much of it is drawn is NOT stored — that is counted from answers_data.",
                max_length=40,
            ),
        ),
    ]
