# Generated by Django 4.2.13 on 2026-09-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0028_merge_20260907_2129'),
        ('homework', '0029_homeworkdraft_art_picture_key'),
    ]

    operations = [
    ]
