# Generated by Django 4.2.13 on 2026-06-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0100_cpp297_expense_model'),
        ('taskqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_tasks', to='classroom.school'),
        ),
    ]
