# Generated by Django 4.2.13 on 2026-06-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0101_add_year10_maths_level'),
        ('taskqueue', '0002_alter_backgroundtask_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('worksheet', 'Worksheet'), ('ai_import', 'AI Import'), ('homework', 'Homework PDF')], db_index=True, max_length=20)),
                ('session_id', models.PositiveIntegerField(blank=True, help_text='PK of the upload session that produced this usage.', null=True)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('est_cost_usd', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='classroom.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
