# Generated by Django 4.2.13 on 2026-08-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskqueue", "0003_aiusagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagelog",
            name="provider",
            field=models.CharField(
                choices=[
                    ("anthropic", "Anthropic (Claude)"),
                    ("openai", "OpenAI (GPT)"),
                ],
                db_index=True,
                default="anthropic",
                help_text="Which vendor billed this call. Drives the rate used.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="aiusagelog",
            name="source",
            field=models.CharField(
                choices=[
                    ("worksheet", "Worksheet"),
                    ("ai_import", "AI Import"),
                    ("homework", "Homework PDF"),
                    ("question_review", "Question review"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
