# Generated by Django 4.2.13 on 2026-04-03 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Optional inline SVG markup for the category icon')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Category',
                'verbose_name_plural': 'Help Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body_markdown', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('module', models.CharField(blank=True, choices=[('', '(No specific module)'), ('classroom', 'Classroom / Classes'), ('billing', 'Billing & Payments'), ('attendance', 'Attendance'), ('progress', 'Progress & Reports'), ('quiz', 'Quizzes & Questions'), ('maths', 'Maths'), ('coding', 'Coding'), ('music', 'Music'), ('science', 'Science'), ('number_puzzles', 'Number Puzzles'), ('ai_import', 'AI Import'), ('audit', 'Audit'), ('accounts', 'Account & Profile'), ('hierarchy', 'School Hierarchy'), ('invoicing', 'Invoicing'), ('salaries', 'Salaries')], max_length=100)),
                ('page_url_name', models.CharField(blank=True, help_text='Django URL name for context-sensitive help (e.g. teacher_dashboard, enrollment_requests). Leave blank for module-level articles.', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to top of help centre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help.helpcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer_markdown', models.TextField()),
                ('role_group', models.CharField(choices=[('hoi', 'Head of Institute / Owner'), ('hod', 'Head of Department'), ('teacher', 'Teachers (all levels)'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('student', 'Student'), ('admin', 'Admin')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='help.helpcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_group', models.CharField(choices=[('hoi', 'Head of Institute / Owner'), ('hod', 'Head of Department'), ('teacher', 'Teachers (all levels)'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('student', 'Student'), ('admin', 'Admin')], max_length=30)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_roles', to='help.helparticle')),
            ],
            options={
                'verbose_name': 'Article Role',
                'verbose_name_plural': 'Article Roles',
                'unique_together': {('article', 'role_group')},
            },
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['module'], name='help_helpar_module_81e943_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['page_url_name'], name='help_helpar_page_ur_3915ef_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['is_published'], name='help_helpar_is_publ_bca0fb_idx'),
        ),
    ]
