# Generated by Django 4.2.13 on 2026-03-29 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0070_add_billing_type_to_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_filename', models.CharField(max_length=255)),
                ('extracted_data', models.JSONField(default=dict)),
                ('extracted_images', models.JSONField(default=dict)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIImportUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_import_usage', to='classroom.school')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('school', 'period_start')},
            },
        ),
    ]
