# Generated by Django 4.2.13 on 2026-06-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimportsession',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiimportsession',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='ai_import_pdfs/'),
        ),
        migrations.AddField(
            model_name='aiimportsession',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=20),
        ),
    ]
