# Generated by Django 4.2.13 on 2026-06-21 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0104_classroom_whatsapp_group_id'),
        ('homework', '0023_alter_homework_options_alter_homework_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('meta_template_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(default='utility', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('body_param_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('opted_in', models.BooleanField(default=False)),
                ('opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('receive_publish', models.BooleanField(default=True)),
                ('receive_results', models.BooleanField(default=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(blank=True, null=True)),
                ('notify_on_publish', models.BooleanField(blank=True, null=True)),
                ('notify_on_submission', models.BooleanField(blank=True, null=True)),
                ('sender_phone_id', models.CharField(blank=True, max_length=64)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='classroom.school')),
            ],
            options={
                'verbose_name': 'WhatsApp config',
                'verbose_name_plural': 'WhatsApp configs',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(blank=True, max_length=30)),
                ('template_params', models.JSONField(blank=True, default=list)),
                ('event_type', models.CharField(blank=True, choices=[('homework_published', 'Homework published'), ('homework_result', 'Homework result')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('undeliverable', 'Undeliverable')], default='queued', max_length=15)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_detail', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to=settings.AUTH_USER_MODEL)),
                ('related_homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='homework.homework')),
                ('related_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='homework.homeworksubmission')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='classroom.school')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='whatsapp.whatsapptemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'status'], name='whatsapp_wh_event_t_7e8ab3_idx')],
            },
        ),
    ]
