# Generated by Django 4.2.13 on 2026-06-22 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jira_sprint_id",
                    models.IntegerField(
                        help_text="Jira's own numeric sprint id (from the Agile API).",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("future", "Future"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("goal", models.TextField(blank=True, default="")),
                ("committed_points", models.FloatField(default=0)),
                ("baseline_captured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date", "-jira_sprint_id"],
            },
        ),
        migrations.CreateModel(
            name="SprintSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("remaining_points", models.FloatField(default=0)),
                ("completed_points", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="sprints.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["snapshot_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="sprintsnapshot",
            constraint=models.UniqueConstraint(
                fields=("sprint", "snapshot_date"),
                name="unique_sprint_snapshot_per_day",
            ),
        ),
    ]
