# Generated by Django 4.2.13 on 2026-06-23 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        unique=True,
                    ),
                ),
                ("remaining_points", models.FloatField(default=0)),
                ("completed_points", models.FloatField(default=0)),
                ("open_issue_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["snapshot_date"],
            },
        ),
    ]
