# Generated by Django 4.2.13 on 2026-03-15 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPuzzleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('operators_allowed', models.CharField(max_length=20)),
                ('min_operand', models.PositiveIntegerField(default=1)),
                ('max_operand', models.PositiveIntegerField(default=9)),
                ('num_operands', models.PositiveIntegerField(default=2)),
                ('brackets_shown', models.BooleanField(default=False)),
                ('brackets_required', models.BooleanField(default=False)),
                ('nested_brackets', models.BooleanField(default=False)),
                ('puzzles_per_set', models.PositiveIntegerField(default=10)),
                ('unlock_threshold', models.PositiveIntegerField(default=8)),
                ('max_result', models.PositiveIntegerField(default=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='number_puzzles.numberpuzzlelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NumberPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operands', models.JSONField()),
                ('operands_hash', models.CharField(editable=False, max_length=32)),
                ('target', models.IntegerField()),
                ('display_template', models.CharField(max_length=200)),
                ('solution', models.CharField(max_length=200)),
                ('has_multiple_solutions', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='number_puzzles.numberpuzzlelevel')),
            ],
            options={
                'ordering': ['level', 'id'],
                'unique_together': {('level', 'operands_hash', 'target')},
            },
        ),
        migrations.CreateModel(
            name='StudentPuzzleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('best_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_puzzles_attempted', models.PositiveIntegerField(default=0)),
                ('total_puzzles_correct', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='number_puzzles.numberpuzzlelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level__number'],
                'unique_together': {('student', 'level')},
            },
        ),
        migrations.CreateModel(
            name='SessionPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assignments', to='number_puzzles.numberpuzzle')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_puzzles', to='number_puzzles.puzzlesession')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('session', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('student_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='number_puzzles.numberpuzzle')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='number_puzzles.puzzlesession')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('session', 'question_number')},
            },
        ),
    ]
