# Generated by Django 4.2.13 on 2026-03-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0059_classstudent_is_active_alter_enrollment_status'),
        ('billing', '0003_seed_promo_unlimited'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_price_id', models.CharField(blank=True, max_length=200)),
                ('class_limit', models.PositiveIntegerField(help_text='Maximum active classes allowed.')),
                ('student_limit', models.PositiveIntegerField(help_text='Maximum active students allowed.')),
                ('invoice_limit_yearly', models.PositiveIntegerField(help_text='Invoices included per year before overage billing.')),
                ('extra_invoice_rate', models.DecimalField(decimal_places=2, help_text='Cost per invoice beyond the yearly limit.', max_digits=6)),
                ('stripe_overage_price_id', models.CharField(blank=True, help_text='Stripe metered price ID for invoice overages.', max_length=200)),
                ('trial_days', models.PositiveSmallIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trialing', max_length=20)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('invoices_used_this_year', models.PositiveIntegerField(default=0)),
                ('invoice_year_start', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_subscriptions', to='billing.instituteplan')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='classroom.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('teachers_attendance', 'Teachers Attendance'), ('students_attendance', 'Students Attendance'), ('student_progress_reports', 'Student Progress Reports')], max_length=50)),
                ('stripe_subscription_item_id', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('school_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='billing.schoolsubscription')),
            ],
            options={
                'ordering': ['module'],
                'unique_together': {('school_subscription', 'module')},
            },
        ),
    ]
