# Generated by Django 4.2.13 on 2026-03-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_seed_institute_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
