# Generated by Django 4.2.13 on 2026-03-22 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_seed_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_percent', models.PositiveSmallIntegerField(default=100, help_text='100 = fully free (unlimited access), otherwise % off monthly price.')),
                ('override_class_limit', models.PositiveIntegerField(blank=True, help_text='Override class limit. Leave blank to use plan default. 0 = unlimited.', null=True)),
                ('override_student_limit', models.PositiveIntegerField(blank=True, help_text='Override student limit. Leave blank to use plan default. 0 = unlimited.', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='discount_code',
            field=models.ForeignKey(blank=True, help_text='Discount code applied at registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.institutediscountcode'),
        ),
    ]
