# Generated by Django 4.2.13 on 2026-03-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_institutediscountcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutediscountcode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Number of times this code can be used. Default 1 (single-use).'),
        ),
    ]
