# Generated by Django 4.2.13 on 2026-03-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_institutediscountcode_max_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubscription',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text='Set to True after the first trial. Prevents repeat trials on upgrade/downgrade.'),
        ),
    ]
