# Generated by Django 4.2.13 on 2026-03-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_schoolsubscription_has_used_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutediscountcode',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Stripe Coupon ID. When set, this coupon is applied to the Stripe subscription.', max_length=100),
        ),
    ]
