# Generated by Django 4.2.13 on 2026-03-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_add_stripe_coupon_to_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Stripe Coupon ID. Applied to checkout when discount is not 100%.', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
