# Generated by Django 4.2.13 on 2026-03-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_add_cancel_at_period_end_and_stripe_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('stripe_price_id', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module'],
            },
        ),
    ]
