# Generated by Django 4.2.13 on 2026-03-23 08:21

from django.db import migrations


def seed_modules(apps, schema_editor):
    ModuleProduct = apps.get_model('billing', 'ModuleProduct')
    modules = [
        {
            'module': 'teachers_attendance',
            'name': 'Teachers Attendance',
            'price': 10.00,
        },
        {
            'module': 'students_attendance',
            'name': 'Students Attendance',
            'price': 10.00,
        },
        {
            'module': 'student_progress_reports',
            'name': 'Student Progress Reports',
            'price': 10.00,
        },
    ]
    for m in modules:
        ModuleProduct.objects.get_or_create(
            module=m['module'],
            defaults={'name': m['name'], 'price': m['price']},
        )


def reverse_seed(apps, schema_editor):
    ModuleProduct = apps.get_model('billing', 'ModuleProduct')
    ModuleProduct.objects.filter(
        module__in=['teachers_attendance', 'students_attendance', 'student_progress_reports']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_add_module_product'),
    ]

    operations = [
        migrations.RunPython(seed_modules, reverse_seed),
    ]
