# Generated by Django 4.2.13 on 2026-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_seed_module_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='grant_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days of access granted when code is redeemed. For 100% codes this sets the subscription period.', null=True),
        ),
    ]
