# Generated by Django 4.2.13 on 2026-03-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_add_grant_days_to_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='grant_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days of access granted. Leave blank for unlimited.', null=True),
        ),
    ]
