# Generated by Django 4.2.13 on 2026-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_add_grant_days_to_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='100 = fully free (no payment). Less than 100 = partial discount.'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='grant_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days of access granted. Leave blank to use package default.', null=True),
        ),
    ]
