# Generated by Django 4.2.13 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_add_discount_percent_to_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='promo_code_used',
            field=models.CharField(blank=True, help_text='Promo code used to activate this subscription.', max_length=50),
        ),
    ]
