# Generated by Django 4.2.13 on 2026-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_modulesubscription_module_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='applicable_packages',
            field=models.ManyToManyField(blank=True, help_text='Packages this code applies to. Leave empty for all packages.', related_name='discount_codes', to='billing.package'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='duration',
            field=models.CharField(choices=[('forever', 'Forever'), ('once', 'Once'), ('repeating', 'Multiple Months')], default='forever', help_text='Stripe coupon duration: forever, once, or repeating (multiple months).', max_length=20),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='duration_in_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of months for repeating duration. Required when duration is "repeating".', null=True),
        ),
        migrations.AddField(
            model_name='institutediscountcode',
            name='applicable_modules',
            field=models.ManyToManyField(blank=True, help_text='Modules this code applies to. Leave empty for all modules.', related_name='discount_codes', to='billing.moduleproduct'),
        ),
        migrations.AddField(
            model_name='institutediscountcode',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, help_text='Plans this code applies to. Leave empty for all plans.', related_name='discount_codes', to='billing.instituteplan'),
        ),
        migrations.AddField(
            model_name='institutediscountcode',
            name='duration',
            field=models.CharField(choices=[('forever', 'Forever'), ('once', 'Once'), ('repeating', 'Multiple Months')], default='forever', help_text='Stripe coupon duration: forever, once, or repeating (multiple months).', max_length=20),
        ),
        migrations.AddField(
            model_name='institutediscountcode',
            name='duration_in_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of months for repeating duration. Required when duration is "repeating".', null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_packages',
            field=models.ManyToManyField(blank=True, help_text='Packages this code applies to. Leave empty for all packages.', related_name='promo_codes', to='billing.package'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='duration',
            field=models.CharField(choices=[('forever', 'Forever'), ('once', 'Once'), ('repeating', 'Multiple Months')], default='forever', help_text='Stripe coupon duration: forever, once, or repeating (multiple months).', max_length=20),
        ),
        migrations.AddField(
            model_name='promocode',
            name='duration_in_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of months for repeating duration.', null=True),
        ),
    ]
