# Generated by Django 4.2.13 on 2026-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_add_duration_and_product_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutediscountcode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True),
        ),
    ]
