# Generated by Django 4.2.13 on 2026-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_institutediscountcode_max_uses_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
    ]
