# Generated by Django 4.2.13 on 2026-03-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0021_add_duration_and_product_fields"),
        ("billing", "0022_institutediscountcode_max_uses_nullable"),
    ]

    operations = []
