# Generated by Django 4.2.13 on 2026-03-31 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0023_merge_20260401_0046"),
        ("billing", "0023_merge_20260401_0047"),
    ]

    operations = []
