# Generated by Django 4.2.13 on 2026-04-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_currency_usd'),
        ('billing', '0024_merge_20260401_1045'),
    ]

    operations = [
    ]
