# Generated by Django 4.2.13 on 2026-04-02 11:10

from django.db import migrations


def make_platinum_unlimited(apps, schema_editor):
    InstitutePlan = apps.get_model('billing', 'InstitutePlan')
    InstitutePlan.objects.filter(slug='platinum').update(
        class_limit=0,
        student_limit=0,
        invoice_limit_yearly=0,
    )


def revert_platinum(apps, schema_editor):
    InstitutePlan = apps.get_model('billing', 'InstitutePlan')
    InstitutePlan.objects.filter(slug='platinum').update(
        class_limit=20,
        student_limit=400,
        invoice_limit_yearly=2000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_merge_0023_currency_usd_0024_merge_20260401_1045'),
    ]

    operations = [
        migrations.RunPython(make_platinum_unlimited, revert_platinum),
    ]
