# Generated by Django 4.2.13 on 2026-04-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_invoicestripe_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark as the default student subscription package. Only one should be default.'),
        ),
    ]
