# Generated by Django 4.2.13 on 2026-05-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_add_is_default_to_package'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schoolsubscription',
            index=models.Index(fields=['status'], name='billing_sch_status_8e2c6a_idx'),
        ),
    ]
