# Generated by Django 4.2.13 on 2026-05-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_ai_grading_module'),
        ('billing', '0029_perf_composite_indexes'),
    ]

    operations = [
    ]
