# Generated by Django 5.2.8 on 2026-05-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_merge_20260510_2233'),
        ('billing', '0030_merge_20260511_1142'),
    ]

    operations = [
    ]
