# Generated by Django 4.2.13 on 2026-05-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_merge_20260511_1752'),
        ('billing', '0032_merge_billing_leaf_nodes'),
    ]

    operations = [
    ]
