# Generated by Django 4.2.13 on 2026-05-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_merge_billing_leaf_nodes'),
        ('billing', '0033_merge_billing_leaves'),
        ('billing', '0033_merge_cpp267'),
    ]

    operations = [
    ]
