# Generated by Django 4.2.13 on 2026-05-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_merge_20260515_1202'),
        ('billing', '0034_merge_20260516_1104'),
    ]

    operations = [
    ]
