# Generated by Django 5.2.8 on 2026-05-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_merge_20260519_1154'),
        ('billing', '0035_merge_20260519_1807'),
    ]

    operations = [
    ]
