# Generated by Django 4.2.13 on 2026-06-20 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0036_merge_20260520_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_code',
            field=models.ForeignKey(blank=True, help_text='Discount code redeemed for this subscription, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_subscriptions', to='billing.discountcode'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_percent_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Percent off at redemption (100 = fully free). Snapshot, not live.', null=True),
        ),
    ]
