# Generated by Django 4.2.13 on 2026-06-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_subscription_discount_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('claude_api', 'Claude API (Anthropic)'), ('claude_code', 'Claude Code'), ('digitalocean', 'DigitalOcean'), ('resend', 'Resend (email)'), ('godaddy', 'GoDaddy (domain)'), ('stripe_fees', 'Stripe fees'), ('other', 'Other')], default='other', max_length=32)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost in NZD per occurrence.', max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('start_date', models.DateField(help_text='First period this cost applies. Day is ignored — costs are booked to the 1st of the month.')),
                ('end_date', models.DateField(blank=True, help_text='Optional: stop generating after this date (e.g. cancelled).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'vendor'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('claude_api', 'Claude API (Anthropic)'), ('claude_code', 'Claude Code'), ('digitalocean', 'DigitalOcean'), ('resend', 'Resend (email)'), ('godaddy', 'GoDaddy (domain)'), ('stripe_fees', 'Stripe fees'), ('other', 'Other')], default='other', max_length=32)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost in NZD (convert foreign bills before entering).', max_digits=10)),
                ('incurred_on', models.DateField(help_text='Date the cost applies to. Use the 1st of the month for monthly bills so it groups cleanly.')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: the bill amount in its native currency, for reference only (not used in totals).', max_digits=10, null=True)),
                ('original_currency', models.CharField(blank=True, max_length=3)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('recurring', 'Recurring template'), ('ai_grading', 'AI grading (auto)')], default='manual', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='billing.recurringexpense')),
            ],
            options={
                'ordering': ['-incurred_on', 'category'],
                'indexes': [models.Index(fields=['incurred_on'], name='billing_exp_incurre_ac9fb3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring__isnull', False)), fields=('recurring', 'incurred_on'), name='uniq_recurring_expense_per_date'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'ai_grading')), fields=('source', 'incurred_on'), name='uniq_ai_grading_expense_per_month'),
        ),
    ]
