# Generated by Django 4.2.13 on 2026-06-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_recurringexpense_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('recurring', 'Recurring template'), ('ai_grading', 'AI usage (auto)'), ('digitalocean_api', 'DigitalOcean API (auto)')], default='manual', max_length=20),
        ),
    ]
