# Generated by Django 4.2.13 on 2026-08-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0039_alter_expense_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("claude_api", "Claude API (Anthropic)"),
                    ("claude_code", "Claude Code"),
                    ("openai_api", "OpenAI API (GPT)"),
                    ("digitalocean", "DigitalOcean"),
                    ("resend", "Resend (email)"),
                    ("godaddy", "GoDaddy (domain)"),
                    ("stripe_fees", "Stripe fees"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="category",
            field=models.CharField(
                choices=[
                    ("claude_api", "Claude API (Anthropic)"),
                    ("claude_code", "Claude Code"),
                    ("openai_api", "OpenAI API (GPT)"),
                    ("digitalocean", "DigitalOcean"),
                    ("resend", "Resend (email)"),
                    ("godaddy", "GoDaddy (domain)"),
                    ("stripe_fees", "Stripe fees"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
