# Generated by Django 4.2.13 on 2026-08-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0040_openai_cost_tracking"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expense",
            name="uniq_ai_grading_expense_per_month",
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "ai_grading")),
                fields=("source", "incurred_on", "category"),
                name="uniq_ai_grading_expense_per_month_vendor",
            ),
        ),
    ]
