# Generated by Django 4.2.13 on 2026-08-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0041_ai_expense_per_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual entry"),
                    ("recurring", "Recurring template"),
                    ("ai_grading", "AI usage (auto)"),
                    ("digitalocean_api", "DigitalOcean API (auto)"),
                    ("ai_vendor_api", "AI vendor billed (auto)"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
