# Generated by Django 4.2.13 on 2026-08-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0043_github_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="is_estimate",
            field=models.BooleanField(
                default=False,
                help_text="Placeholder for a cost nobody can fetch (Claude Code bills per use with no API). A charge entered by hand for the same month replaces the estimate instead of adding to it.",
            ),
        ),
    ]
