# Generated by Django 4.2.13 on 2026-08-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0044_recurring_expense_is_estimate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("claude_api", "Claude API (Anthropic)"),
                    ("claude_code", "Claude Code"),
                    ("openai_api", "OpenAI API (GPT)"),
                    ("digitalocean", "DigitalOcean"),
                    ("resend", "Resend (email)"),
                    ("godaddy", "GoDaddy (domain)"),
                    ("github", "GitHub"),
                    ("stripe_fees", "Stripe fees"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual entry"),
                    ("recurring", "Recurring template"),
                    ("ai_grading", "AI usage (auto)"),
                    ("digitalocean_api", "DigitalOcean API (auto)"),
                    ("github_api", "GitHub billing API (auto)"),
                    ("ai_vendor_api", "AI vendor billed (auto)"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="category",
            field=models.CharField(
                choices=[
                    ("claude_api", "Claude API (Anthropic)"),
                    ("claude_code", "Claude Code"),
                    ("openai_api", "OpenAI API (GPT)"),
                    ("digitalocean", "DigitalOcean"),
                    ("resend", "Resend (email)"),
                    ("godaddy", "GoDaddy (domain)"),
                    ("github", "GitHub"),
                    ("stripe_fees", "Stripe fees"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
