# Generated by Django 4.2.13 on 2026-09-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0045_github_billing_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigradingusage",
            name="highest_alert_sent",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Highest usage-percentage warning already emailed for this period (0 = none sent). The 75/80/85/90/95/100% alerts fire once each: without this they would re-send on every answer graded past the threshold. Resets naturally, since each month gets its own row.",
            ),
        ),
    ]
