# Generated by Django 4.2.13 on 2026-09-02 19:55

from django.db import migrations, models


def keep_one_default(apps, schema_editor):
    """Leave at most one package flagged default.

    Two defaults never raised — `_get_student_package()` takes
    `filter(is_default=True).first()` under `ordering = ['order', 'price']`, so
    the tie was broken silently. Keep whichever that resolution would already
    have chosen, so this migration changes who nothing lands on, and clear the
    rest.
    """
    Package = apps.get_model("billing", "Package")
    winner = Package.objects.filter(is_default=True).order_by(
        "order", "price", "pk",
    ).first()
    if winner is None:
        return
    Package.objects.filter(is_default=True).exclude(pk=winner.pk).update(
        is_default=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0045_github_billing_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="The default student subscription package — the one school students are put on. Marking a package default clears the flag on every other package.",
            ),
        ),
        migrations.RunPython(keep_one_default, migrations.RunPython.noop),
    ]
