# Generated by Django 4.2.13 on 2026-09-03 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0045_github_billing_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="grants_student_basic",
            field=models.BooleanField(
                default=False,
                help_text="Put students who redeem this code on the Student Basic module — the free promotional edition, without the AI-graded questions. Off by default: an ordinary code grants the app in full.",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="grants_student_basic",
            field=models.BooleanField(
                default=False,
                help_text="Put students who redeem this code on the Student Basic module — the free promotional edition, without the AI-graded questions. Off by default: an ordinary code grants the app in full.",
            ),
        ),
        migrations.CreateModel(
            name="StudentModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            (
                                "student_basic",
                                "Student Basic — self-marked questions only",
                            ),
                            ("student_ai_grading", "AI Graded Questions"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to switch the module off without losing the record of it.",
                    ),
                ),
                (
                    "source_code",
                    models.CharField(
                        blank=True,
                        help_text="The promotion/discount code that granted it, if any.",
                        max_length=50,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Why this student has it — shown on the admin list.",
                        max_length=200,
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who attached this module. Blank when a promotion code did.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_modules",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["module"],
                "unique_together": {("subscription", "module")},
            },
        ),
    ]
