# Generated by Django 4.2.13 on 2026-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0047_ai_grading_alert_watermark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modulesubscription",
            name="module",
            field=models.CharField(
                choices=[
                    ("teachers_attendance", "Teachers Attendance"),
                    ("students_attendance", "Students Attendance"),
                    ("student_progress_reports", "Student Progress Reports"),
                    ("ai_import_starter", "AI Question Import - Starter"),
                    ("ai_import_professional", "AI Question Import - Professional"),
                    ("ai_import_enterprise", "AI Question Import - Enterprise"),
                    ("ai_grading_starter", "AI Grading - Starter (1,000 answers/mo)"),
                    (
                        "ai_grading_professional",
                        "AI Grading - Professional (5,000 answers/mo)",
                    ),
                    ("ai_grading_enterprise", "AI Grading - Enterprise (unlimited)"),
                    (
                        "report_automation",
                        "Student Report Automation (scheduled sending)",
                    ),
                    (
                        "question_automation",
                        "Question Automation (scheduled to term/year)",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
