# Generated by Django 4.2.13 on 2026-09-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0053_seed_invoicing_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleproduct",
            name="schedules_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many question-automation schedules may run at the same time. Null = unlimited. Counts schedules whose date window covers today and which are not paused — never the schedules a school has ever created, which only ever grows.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="modulesubscription",
            name="module",
            field=models.CharField(
                choices=[
                    ("teachers_attendance", "Teachers Attendance"),
                    ("students_attendance", "Students Attendance"),
                    ("student_progress_reports", "Student Progress Reports"),
                    ("ai_import_starter", "AI Question Import - Starter"),
                    ("ai_import_professional", "AI Question Import - Professional"),
                    ("ai_import_enterprise", "AI Question Import - Enterprise"),
                    ("ai_grading_starter", "AI Grading - Starter (1,000 answers/mo)"),
                    (
                        "ai_grading_professional",
                        "AI Grading - Professional (5,000 answers/mo)",
                    ),
                    ("ai_grading_enterprise", "AI Grading - Enterprise (unlimited)"),
                    (
                        "report_automation",
                        "Student Report Automation (scheduled sending)",
                    ),
                    (
                        "question_automation_starter",
                        "Question Automation - Starter (15 schedules)",
                    ),
                    (
                        "question_automation_professional",
                        "Question Automation - Professional (75 schedules)",
                    ),
                    (
                        "question_automation_unlimited",
                        "Question Automation - Unlimited",
                    ),
                    ("brainbuzz", "BrainBuzz Live Quiz"),
                    ("worksheets", "Worksheets"),
                    ("whatsapp_notifications", "WhatsApp Parent Notifications"),
                    ("invoicing", "Student Invoicing"),
                ],
                max_length=50,
            ),
        ),
    ]
