# Generated by Django 4.2.13 on 2026-09-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0055_seed_question_automation_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="scope",
            field=models.CharField(
                choices=[
                    ("everything", "Everything (plan + all modules)"),
                    ("plans", "Institute plans only"),
                ],
                default="everything",
                help_text='Which products this discount may apply to. "Everything" also prevents any other discount being added alongside it, since two discounts on one line compound.',
                max_length=20,
            ),
        ),
    ]
