# Generated by Django 4.2.13 on 2026-03-06 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maths.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('level_number',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_total_seconds', models.PositiveIntegerField(default=0, help_text='Total seconds spent today')),
                ('weekly_total_seconds', models.PositiveIntegerField(default=0, help_text='Total seconds spent this week')),
                ('last_reset_date', models.DateField(auto_now=True, help_text='Last date when daily time was reset')),
                ('last_reset_week', models.IntegerField(default=0, help_text='ISO week number of last weekly reset')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last time activity was recorded')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maths_time_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('calculation', 'Calculation')], default='multiple_choice', max_length=20)),
                ('difficulty', models.PositiveIntegerField(default=1, help_text='1=Easy, 2=Medium, 3=Hard')),
                ('points', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this question', null=True, upload_to='questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='maths.level')),
                ('topic', models.ForeignKey(blank=True, help_text='Topic this question belongs to (e.g., BODMAS/PEMDAS, Measurements, Fractions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='maths.topic')),
            ],
            options={
                'ordering': ['level', 'difficulty', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='level',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='levels', to='maths.topic'),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(default=maths.models.generate_class_code, max_length=8, unique=True)),
                ('levels', models.ManyToManyField(blank=True, related_name='classrooms', to='maths.level')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maths_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for multiple choice options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='maths.question')),
            ],
            options={
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicLevelStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_points', models.DecimalField(decimal_places=2, default=0, help_text='Average points across all students', max_digits=10)),
                ('sigma', models.DecimalField(decimal_places=2, default=0, help_text='Standard deviation (sigma)', max_digits=10)),
                ('student_count', models.PositiveIntegerField(default=0, help_text='Number of students who have completed this topic-level')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time statistics were calculated')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statistics', to='maths.level')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_statistics', to='maths.topic')),
            ],
            options={
                'ordering': ['level__level_number', 'topic__name'],
                'indexes': [models.Index(fields=['level', 'topic'], name='maths_topic_level_i_267d9e_idx')],
                'unique_together': {('level', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='StudentFinalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session identifier for this attempt', max_length=100)),
                ('attempt_number', models.PositiveIntegerField(help_text='Attempt number for this student-topic-level combination (increments for each new attempt)')),
                ('points_earned', models.DecimalField(decimal_places=2, help_text='Final points earned for this attempt', max_digits=10)),
                ('last_updated_time', models.DateTimeField(auto_now=True, help_text='Last time this record was updated')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_answers', to='maths.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maths_final_answers', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_answers', to='maths.topic')),
            ],
            options={
                'ordering': ['-last_updated_time'],
                'indexes': [models.Index(fields=['student', 'topic', 'level'], name='maths_stude_student_ad30a8_idx'), models.Index(fields=['student', 'topic', 'level', 'attempt_number'], name='maths_stude_student_2e8b01_idx')],
                'unique_together': {('student', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='For short answer questions')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, default='', help_text='Session identifier for tracking attempts', max_length=100)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, help_text='Time taken for this attempt in seconds')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='maths.question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maths.answer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maths_student_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answered_at'],
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='maths.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maths_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='BasicFactsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session identifier for tracking attempts', max_length=100)),
                ('score', models.PositiveIntegerField(help_text='Number of correct answers')),
                ('total_points', models.PositiveIntegerField(help_text='Total possible points')),
                ('time_taken_seconds', models.PositiveIntegerField(help_text='Time taken for this attempt in seconds')),
                ('points', models.DecimalField(decimal_places=2, help_text='Calculated points based on score, time, and percentage', max_digits=10)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_facts_results', to='maths.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maths_basic_facts_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['student', 'level'], name='maths_basic_student_e1bd97_idx'), models.Index(fields=['student', 'level', 'session_id'], name='maths_basic_student_8dd087_idx')],
            },
        ),
    ]
