# Generated by Django 4.2.13 on 2026-03-06 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicfactsresult',
            name='level_number',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric level within the subtopic (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='basicfactsresult',
            name='subtopic',
            field=models.CharField(blank=True, default='', help_text='e.g. Addition, Subtraction, Multiplication, Division, PlaceValue', max_length=20),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Groups all answers from one quiz session'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='ordered_answer_ids',
            field=models.JSONField(blank=True, help_text='For drag-drop questions', null=True),
        ),
        migrations.AlterField(
            model_name='basicfactsresult',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_facts_results', to='maths.level'),
        ),
        migrations.AddIndex(
            model_name='basicfactsresult',
            index=models.Index(fields=['student', 'subtopic', 'level_number'], name='maths_basic_student_f345c4_idx'),
        ),
    ]
