# Generated by Django 4.2.13 on 2026-03-06 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_add_attempt_and_subtopic_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfinalanswer',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='studentfinalanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='basicfactsresult',
            name='questions_data',
            field=models.JSONField(blank=True, default=list, help_text='Stores generated questions + student answers for review.'),
        ),
        migrations.AddField(
            model_name='studentfinalanswer',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this result was completed'),
        ),
        migrations.AddField(
            model_name='studentfinalanswer',
            name='points',
            field=models.FloatField(default=0.0, help_text='Calculated points based on score and time'),
        ),
        migrations.AddField(
            model_name='studentfinalanswer',
            name='quiz_type',
            field=models.CharField(blank=True, choices=[('topic', 'Topic Quiz'), ('mixed', 'Mixed Quiz'), ('times_table', 'Times Table')], default='topic', max_length=20),
        ),
        migrations.AddField(
            model_name='studentfinalanswer',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of correct answers'),
        ),
        migrations.AddField(
            model_name='studentfinalanswer',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time taken for this attempt in seconds'),
        ),
        migrations.AddField(
            model_name='studentfinalanswer',
            name='total_questions',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total questions in this attempt'),
        ),
        migrations.AlterField(
            model_name='studentfinalanswer',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, help_text='Attempt number for this student-topic-level combination'),
        ),
        migrations.AlterField(
            model_name='studentfinalanswer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_answers', to='maths.level'),
        ),
        migrations.AlterField(
            model_name='studentfinalanswer',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy: points from consolidation migration', max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentfinalanswer',
            name='session_id',
            field=models.CharField(blank=True, default=uuid.uuid4, help_text='Session identifier for this attempt', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentfinalanswer',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_answers', to='maths.topic'),
        ),
    ]
