# Generated by Django 4.2.13 on 2026-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_add_quiz_engine_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinalanswer',
            name='operation',
            field=models.CharField(blank=True, default='', help_text="Operation for times-table quizzes: 'multiplication' or 'division'", max_length=20),
        ),
    ]
