# Generated by Django 4.2.13 on 2026-03-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0038_department_subject_and_question_school'),
        ('maths', '0004_add_operation_to_studentfinalanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Null = global/shared question. Set = private to this school only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.school'),
        ),
    ]
