# Generated by Django 4.2.13 on 2026-03-09 08:42

from django.db import migrations


def backfill_scores(apps, schema_editor):
    """
    Backfill score/total_questions on StudentFinalAnswer records that were
    created before migration 0003 added those fields (all defaulted to 0).
    Compute from the matching StudentAnswer rows keyed by session_id.
    """
    StudentFinalAnswer = apps.get_model('maths', 'StudentFinalAnswer')
    StudentAnswer = apps.get_model('maths', 'StudentAnswer')

    qs = StudentFinalAnswer.objects.filter(score=0, total_questions=0)
    updated = 0
    for fa in qs.iterator():
        answers = StudentAnswer.objects.filter(
            student_id=fa.student_id,
            session_id=str(fa.session_id),
        )
        total = answers.count()
        if total == 0:
            continue
        correct = answers.filter(is_correct=True).count()
        fa.score = correct
        fa.total_questions = total
        # Recompute points: (percentage * 100 * 60) / time
        time_taken = fa.time_taken_seconds or 1
        percentage = correct / total if total else 0
        fa.points = round((percentage * 100 * 60) / time_taken, 2)
        fa.save(update_fields=['score', 'total_questions', 'points'])
        updated += 1


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0005_department_subject_and_question_school'),
    ]

    operations = [
        migrations.RunPython(backfill_scores, migrations.RunPython.noop),
    ]
