# Generated by Django 4.2.13 on 2026-03-12 04:10

from django.db import migrations, models


def backfill_table_number(apps, schema_editor):
    """Copy level.level_number → table_number for existing times-table records."""
    StudentFinalAnswer = apps.get_model('maths', 'StudentFinalAnswer')
    Level = apps.get_model('classroom', 'Level')
    rows = StudentFinalAnswer.objects.filter(
        quiz_type='times_table',
        level__isnull=False,
        table_number__isnull=True,
    ).select_related('level')
    count = 0
    for row in rows:
        row.table_number = row.level.level_number
        row.save(update_fields=['table_number'])
        count += 1
    if count:
        print(f'  Backfilled table_number on {count} times-table records')


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0006_backfill_final_answer_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinalanswer',
            name='table_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Times-table number (1-12). Only set for quiz_type='times_table'.", null=True),
        ),
        migrations.RunPython(backfill_table_number, migrations.RunPython.noop),
    ]
