# Generated by Django 4.2.13 on 2026-03-13 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maths', '0007_add_table_number_to_studentfinalanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'question', 'attempt_id')},
        ),
    ]
