# Generated by Django 4.2.13 on 2026-03-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0059_classstudent_is_active_alter_enrollment_status'),
        ('maths', '0008_fix_studentanswer_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Null = not class-scoped. Set = visible to this class only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maths_questions', to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Null = not department-scoped. Set = visible to this department only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.department'),
        ),
    ]
