# Generated by Django 4.2.13 on 2026-03-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0015_fix_orphaned_index_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, help_text='Image answer for MCQ', null=True, upload_to='answers/'),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video for this question', null=True, upload_to='questions/videos/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
    ]
