# Generated by Django 4.2.13 on 2026-05-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0017_cleanup_orphaned_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('calculation', 'Calculation'), ('long_division', 'Long Division')], default='multiple_choice', max_length=20),
        ),
    ]
