# Generated by Django 4.2.13 on 2026-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0018_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dividend',
            field=models.PositiveIntegerField(blank=True, help_text='Long-division: number being divided', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='divisor',
            field=models.PositiveIntegerField(blank=True, help_text='Long-division: number dividing', null=True),
        ),
    ]
