# Generated by Django 4.2.13 on 2026-05-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0019_question_dividend_question_divisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='target_number',
            field=models.PositiveIntegerField(blank=True, help_text='Prime-factorization: number to factorise', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('calculation', 'Calculation'), ('long_division', 'Long Division'), ('prime_factorization', 'Prime Factorization')], default='multiple_choice', max_length=20),
        ),
    ]
