# Generated by Django 4.2.13 on 2026-05-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0023_long_division_factors_under_number_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinalanswer',
            name='shuffled',
            field=models.BooleanField(default=False, help_text='Whether the questions were presented in random order'),
        ),
    ]
