# Generated by Django 4.2.13 on 2026-05-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0018_extended_answer_and_grading'),
        ('maths', '0024_add_shuffled_to_studentfinalanswer'),
    ]

    operations = [
    ]
