# Generated by Django 4.2.13 on 2026-05-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0025_merge_20260510_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('calculation', 'Calculation'), ('extended_answer', 'Extended Answer (written proof/explanation)'), ('long_division', 'Long Division'), ('prime_factorization', 'Prime Factorization')], default='multiple_choice', max_length=20),
        ),
    ]
