# Generated by Django 5.2.8 on 2026-05-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0025_merge_20260511_1142'),
        ('maths', '0026_upload_session_async_fields'),
    ]

    operations = [
    ]
