# Generated by Django 4.2.13 on 2026-06-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0027_merge_20260511_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_format',
            field=models.CharField(choices=[('text', 'Text — exact match (case/space-insensitive)'), ('algebra', 'Algebra — simplified polynomial (e.g. expand & simplify)')], default='text', help_text='For short_answer / calculation questions. "Algebra" grades the answer as a fully simplified, expanded polynomial — e.g. (2x+3)(x-5) must be entered as "2x^2 - 7x - 15". Term order and spacing are ignored, but un-combined like terms and un-expanded brackets are marked wrong even when algebraically equal.', max_length=10),
        ),
    ]
