# Generated by Django 4.2.13 on 2026-06-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0028_question_answer_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='operands',
            field=models.JSONField(blank=True, help_text='Column arithmetic: list of numbers top-to-bottom, e.g. [90, 82]', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='operator',
            field=models.CharField(blank=True, default='', help_text="Column arithmetic operator: '+', '-' or '*'", max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('calculation', 'Calculation'), ('extended_answer', 'Extended Answer (written proof/explanation)'), ('long_division', 'Long Division'), ('prime_factorization', 'Prime Factorization'), ('column_operation', 'Column Arithmetic')], default='multiple_choice', max_length=20),
        ),
    ]
