# Generated by Django 4.2.13 on 2026-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0029_question_operands_question_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_tolerance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Measure: accepted ± band. 135 ± 2 marks 133–137 correct. NULL or 0 = exact match.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_unit',
            field=models.CharField(blank=True, default='', help_text="Measure: unit shown in the answer box, e.g. '°', 'cm', 'g'.", max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='numeric_answer',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Measure: the true value to be measured (e.g. 135 for a 135° angle).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('calculation', 'Calculation'), ('extended_answer', 'Extended Answer (written proof/explanation)'), ('long_division', 'Long Division'), ('prime_factorization', 'Prime Factorization'), ('column_operation', 'Column Arithmetic'), ('measure', 'Measure (angle/scale, tolerance-graded)')], default='multiple_choice', max_length=20),
        ),
    ]
