# Generated by Django 4.2.13 on 2026-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0030_question_answer_tolerance_question_answer_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grid_spec',
            field=models.JSONField(blank=True, help_text='draw_on_grid only. Dot grid + shape + correct target set (grid-index coords).', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('calculation', 'Calculation'), ('extended_answer', 'Extended Answer (written proof/explanation)'), ('long_division', 'Long Division'), ('prime_factorization', 'Prime Factorization'), ('column_operation', 'Column Arithmetic'), ('measure', 'Measure (angle/scale, tolerance-graded)'), ('draw_on_grid', 'Draw on Grid (symmetry / reflection / plot)')], default='multiple_choice', max_length=20),
        ),
    ]
