# Generated by Django 4.2.13 on 2026-06-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0032_seed_geometry_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfinalanswer",
            name="questions_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Stores the questions + student answers for later review.",
            ),
        ),
    ]
