# Generated by Django 4.2.13 on 2026-06-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0033_studentfinalanswer_questions_data'),
        ('maths', '0034_seed_shape_select_question'),
    ]

    operations = [
    ]
