# Generated by Django 4.2.13 on 2026-06-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0035_merge_20260616_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='graph_spec',
            field=models.JSONField(blank=True, help_text='read_graph only. Render-only line-graph (axes/series); answer uses the measure numeric fields.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='plane_spec',
            field=models.JSONField(blank=True, help_text='plot_points / plot_line / identify_coords only. Signed coordinate plane (set-comparison graded).', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('calculation', 'Calculation'), ('extended_answer', 'Extended Answer (written proof/explanation)'), ('long_division', 'Long Division'), ('prime_factorization', 'Prime Factorization'), ('column_operation', 'Column Arithmetic'), ('measure', 'Measure (angle/scale, tolerance-graded)'), ('draw_on_grid', 'Draw on Grid (symmetry / reflection / plot)'), ('shape_select', 'Shape Select (find & colour shapes)'), ('plot_points', 'Plot Points (Cartesian plane)'), ('plot_line', 'Plot a Line / Shape (Cartesian plane)'), ('identify_coords', 'Identify Coordinates (type the point)'), ('read_graph', 'Read a Graph (read off a value)')], default='multiple_choice', max_length=20),
        ),
    ]
