# Generated by Django 4.2.13 on 2026-07-14 04:56
#
# Made idempotent (2026-07-18): the original AddField / AddIndex operations
# crash the deploy `migrate` with "Duplicate column name 'number_line_spec'" on
# environments where a previous run half-applied. MySQL auto-commits DDL, so if
# the first attempt added the column but then failed on a later operation, the
# column is left behind while the migration stays *unrecorded* — the retry then
# re-adds the same column and dies. We now add the column and the index only if
# they are missing, while keeping Django's migration *state* unchanged via
# SeparateDatabaseAndState so the model field + index stay tracked. Follows the
# same pattern as homework/0017. The guards are MySQL-specific (information_
# schema); the SQLite test DB is built from models without running migrations
# (see conftest.django_db_use_migrations), so these RunPython bodies only ever
# execute against MySQL on a real deploy.

from django.db import migrations, models


_NUMBER_LINE_SPEC = models.JSONField(
    blank=True,
    help_text="number_line only. Scale + mode + correct target set (mark: set-comparison; read: numeric tolerance).",
    null=True,
)

_TLS_INDEX = models.Index(
    fields=["level", "topic"], name="maths_tls_level_topic_idx"
)


def _add_number_line_spec_if_missing(apps, schema_editor):
    """Add maths_question.number_line_spec only if the column is absent."""
    conn = schema_editor.connection
    table = "maths_question"
    with conn.cursor() as cur:
        cur.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = DATABASE() AND table_name = %s "
            "AND column_name = 'number_line_spec'",
            [table],
        )
        exists = cur.fetchone() is not None
    if not exists:
        schema_editor.execute(
            f"ALTER TABLE {table} ADD COLUMN number_line_spec json NULL"
        )


def _add_tls_index_if_missing(apps, schema_editor):
    """Add the (level_id, topic_id) index on maths_topiclevelstatistics only if
    it is absent — the index the original AddIndex operation would create."""
    conn = schema_editor.connection
    table = "maths_topiclevelstatistics"
    index_name = "maths_tls_level_topic_idx"
    with conn.cursor() as cur:
        cur.execute(
            "SELECT 1 FROM information_schema.statistics "
            "WHERE table_schema = DATABASE() AND table_name = %s "
            "AND index_name = %s LIMIT 1",
            [table, index_name],
        )
        exists = cur.fetchone() is not None
    if not exists:
        schema_editor.execute(
            f"CREATE INDEX {index_name} ON {table} (level_id, topic_id)"
        )


def _noop_reverse(apps, schema_editor):
    """No-op on reverse — the drops are handled by Django's state side."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0036_question_graph_spec_question_plane_spec_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _add_number_line_spec_if_missing, _noop_reverse
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="question",
                    name="number_line_spec",
                    field=_NUMBER_LINE_SPEC,
                ),
            ],
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("short_answer", "Short Answer"),
                    ("fill_blank", "Fill in the Blank"),
                    ("calculation", "Calculation"),
                    ("extended_answer", "Extended Answer (written proof/explanation)"),
                    ("long_division", "Long Division"),
                    ("prime_factorization", "Prime Factorization"),
                    ("column_operation", "Column Arithmetic"),
                    ("measure", "Measure (angle/scale, tolerance-graded)"),
                    ("draw_on_grid", "Draw on Grid (symmetry / reflection / plot)"),
                    ("shape_select", "Shape Select (find & colour shapes)"),
                    ("plot_points", "Plot Points (Cartesian plane)"),
                    ("plot_line", "Plot a Line / Shape (Cartesian plane)"),
                    ("identify_coords", "Identify Coordinates (type the point)"),
                    ("read_graph", "Read a Graph (read off a value)"),
                    ("number_line", "Number Line (mark or read a value)"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_tls_index_if_missing, _noop_reverse),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="topiclevelstatistics",
                    index=_TLS_INDEX,
                ),
            ],
        ),
    ]
