# Generated by Django 4.2.13 on 2026-07-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0036_question_graph_spec_question_plane_spec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="number_line_spec",
            field=models.JSONField(
                blank=True,
                help_text="number_line only. Scale + mode + correct target set (mark: set-comparison; read: numeric tolerance).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("short_answer", "Short Answer"),
                    ("fill_blank", "Fill in the Blank"),
                    ("calculation", "Calculation"),
                    ("extended_answer", "Extended Answer (written proof/explanation)"),
                    ("long_division", "Long Division"),
                    ("prime_factorization", "Prime Factorization"),
                    ("column_operation", "Column Arithmetic"),
                    ("measure", "Measure (angle/scale, tolerance-graded)"),
                    ("draw_on_grid", "Draw on Grid (symmetry / reflection / plot)"),
                    ("shape_select", "Shape Select (find & colour shapes)"),
                    ("plot_points", "Plot Points (Cartesian plane)"),
                    ("plot_line", "Plot a Line / Shape (Cartesian plane)"),
                    ("identify_coords", "Identify Coordinates (type the point)"),
                    ("read_graph", "Read a Graph (read off a value)"),
                    ("number_line", "Number Line (mark or read a value)"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="topiclevelstatistics",
            index=models.Index(
                fields=["level", "topic"], name="maths_tls_level_topic_idx"
            ),
        ),
    ]
