# Generated by Django 4.2.13 on 2026-07-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0037_question_number_line_spec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="table_spec",
            field=models.JSONField(
                blank=True,
                help_text="table_of_values only. Headers + rows of given/answer cells (numeric-tolerance graded).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("short_answer", "Short Answer"),
                    ("fill_blank", "Fill in the Blank"),
                    ("calculation", "Calculation"),
                    ("extended_answer", "Extended Answer (written proof/explanation)"),
                    ("long_division", "Long Division"),
                    ("prime_factorization", "Prime Factorization"),
                    ("column_operation", "Column Arithmetic"),
                    ("measure", "Measure (angle/scale, tolerance-graded)"),
                    ("draw_on_grid", "Draw on Grid (symmetry / reflection / plot)"),
                    ("shape_select", "Shape Select (find & colour shapes)"),
                    ("plot_points", "Plot Points (Cartesian plane)"),
                    ("plot_line", "Plot a Line / Shape (Cartesian plane)"),
                    ("identify_coords", "Identify Coordinates (type the point)"),
                    ("read_graph", "Read a Graph (read off a value)"),
                    ("number_line", "Number Line (mark or read a value)"),
                    ("table_of_values", "Table of Values (fill in the x/y table)"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
    ]
