# Generated by Django 4.2.13 on 2026-07-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0038_question_table_spec_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_format",
            field=models.CharField(
                choices=[
                    ("text", "Text — exact match (case/space-insensitive)"),
                    (
                        "algebra",
                        "Algebra — simplified polynomial (e.g. expand & simplify)",
                    ),
                    (
                        "equation",
                        "Equation — algebraic equivalence (accepts vertex / factored / expanded form)",
                    ),
                ],
                default="text",
                help_text='For short_answer / calculation questions. "Algebra" grades the answer as a fully simplified, expanded polynomial — e.g. (2x+3)(x-5) must be entered as "2x^2 - 7x - 15". "Equation" grades by algebraic equivalence — for "write the equation" questions any spelling of the same curve is accepted (y=2(x-1)^2-2 == y=2x^2-4x). Term order and spacing are always ignored.',
                max_length=10,
            ),
        ),
    ]
