# Generated by Django 4.2.13 on 2026-08-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0039_alter_question_answer_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_format",
            field=models.CharField(
                choices=[
                    ("text", "Text — exact match (case/space-insensitive)"),
                    (
                        "algebra",
                        "Algebra — simplified polynomial (e.g. expand & simplify)",
                    ),
                    (
                        "equation",
                        "Equation — algebraic equivalence (accepts vertex / factored / expanded form)",
                    ),
                    (
                        "set",
                        'Set — list every value, any order (e.g. "what are the multiples of 9 between 50 and 70?")',
                    ),
                ],
                default="text",
                help_text='For short_answer / calculation questions. "Algebra" grades the answer as a fully simplified, expanded polynomial — e.g. (2x+3)(x-5) must be entered as "2x^2 - 7x - 15". "Equation" grades by algebraic equivalence — for "write the equation" questions any spelling of the same curve is accepted (y=2(x-1)^2-2 == y=2x^2-4x). Term order and spacing are always ignored. "Set" is for "list every value" questions — store the values as one comma-separated answer ("54, 63"); the student must give them all, in any order. Leave as "Text" when the order of the values is part of the answer (e.g. "write these numbers in order").',
                max_length=10,
            ),
        ),
    ]
