# Generated by Django 4.2.13 on 2026-08-17 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0115_location_color"),
        ("maths", "0040_alter_question_answer_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionHealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "level_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("choice_questions", models.PositiveIntegerField(default=0)),
                (
                    "arithmetic_verified",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Questions whose own maths was evaluated and checked.",
                    ),
                ),
                (
                    "unverifiable",
                    models.PositiveIntegerField(
                        default=0, help_text="Word problems etc. that need a human."
                    ),
                ),
                (
                    "questions_blocking",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Questions with an issue that can mismark a student.",
                    ),
                ),
                (
                    "questions_advisory",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Questions with only non-mismarking issues.",
                    ),
                ),
                (
                    "issue_counts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g. {'EQUIVALENT-OPTION': 14, 'WRONG-ANSWER-KEY': 2}",
                    ),
                ),
                (
                    "flagged_questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{'id': 6017, 'codes': ['EQUIVALENT-OPTION'], 'text': '...'}]",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_snapshots",
                        to="classroom.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "question health snapshot",
                "ordering": ["-created_at"],
            },
        ),
    ]
