# Generated by Django 4.2.13 on 2026-08-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0041_question_health_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAIReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("ok", "Reviewed — no objection"),
                            ("flagged", "Flagged for human review"),
                            ("error", "Review failed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short human-readable explanation, shown to whoever triages.",
                    ),
                ),
                ("question_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_pass_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "adjudicator_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("escalated", models.BooleanField(default=False)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_reviews",
                        to="maths.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "question AI review",
                "ordering": ["-reviewed_at"],
                "indexes": [
                    models.Index(
                        fields=["question", "-reviewed_at"],
                        name="maths_quest_questio_15184d_idx",
                    )
                ],
            },
        ),
    ]
