# Generated by Django 4.2.13 on 2026-08-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0042_question_ai_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionhealthsnapshot",
            name="typed_questions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Short-answer / calculation questions scanned (CPP-378). Previously unmeasured, so health read better than it was.",
            ),
        ),
    ]
