# Generated by Django 4.2.13 on 2026-08-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0044_question_answer_format_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="blank_spec",
            field=models.JSONField(
                blank=True,
                help_text='fill_blank only. Accepted answers per blank, positional. Mark each blank in the question text with "___".',
                null=True,
            ),
        ),
    ]
