# Generated by Django 4.2.13 on 2026-08-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0045_question_blank_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sketch_spec",
            field=models.JSONField(
                blank=True,
                help_text="sketch_graph only. The plane to draw plus the key features (vertex / intercepts / axis of symmetry) the answer is marked against, feature by feature.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("short_answer", "Short Answer"),
                    ("fill_blank", "Fill in the Blank"),
                    ("calculation", "Calculation"),
                    ("extended_answer", "Extended Answer (written proof/explanation)"),
                    ("long_division", "Long Division"),
                    ("prime_factorization", "Prime Factorization"),
                    ("column_operation", "Column Arithmetic"),
                    ("measure", "Measure (angle/scale, tolerance-graded)"),
                    ("draw_on_grid", "Draw on Grid (symmetry / reflection / plot)"),
                    ("shape_select", "Shape Select (find & colour shapes)"),
                    ("plot_points", "Plot Points (Cartesian plane)"),
                    ("plot_line", "Plot a Line / Shape (Cartesian plane)"),
                    ("identify_coords", "Identify Coordinates (type the point)"),
                    ("read_graph", "Read a Graph (read off a value)"),
                    ("number_line", "Number Line (mark or read a value)"),
                    ("table_of_values", "Table of Values (fill in the x/y table)"),
                    (
                        "sketch_graph",
                        "Sketch a Graph (state vertex / intercepts / axis of symmetry)",
                    ),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
    ]
