# Generated by Django 4.2.13 on 2026-09-05 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0120_repair_classroom_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0003_feedbackimage"),
        ("maths", "0046_question_sketch_spec_alter_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionhealthsnapshot",
            name="questions_cleared",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Flagged questions a person reviewed and marked correct, so left out of the counts above (CPP-398). Recorded rather than merely subtracted: a suppressed question that vanishes without a number is how a clean-looking bank hides work.",
            ),
        ),
        migrations.CreateModel(
            name="QuestionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("correct", "Reviewed and correct"),
                            ("broken", "Reviewed — needs fixing"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why, in the reviewer's words. Shown next to the verdict.",
                    ),
                ),
                ("question_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="human_reviews",
                        to="maths.question",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "question review",
                "ordering": ["-reviewed_at"],
                "indexes": [
                    models.Index(
                        fields=["question", "-reviewed_at"],
                        name="maths_quest_questio_7d8444_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What the reporter wrote, copied so the report stands alone.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        blank=True,
                        help_text="The feedback item this came in on, for the description, screenshots and Jira key.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_reports",
                        to="feedback.feedback",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="maths.question",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_reports",
                        to="classroom.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "question report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["question", "-created_at"],
                        name="maths_quest_questio_f3e442_idx",
                    )
                ],
            },
        ),
    ]
