# Generated by Django 4.2.13 on 2026-09-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maths", "0047_question_reports_and_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="retired_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set to withdraw this question from all future selection. Past submissions keep it, shown greyed out. Clear it to bring the question back.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="retired_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why it was withdrawn — shown to the reviewer, so the next person does not have to rediscover the fault.",
            ),
        ),
    ]
