# Generated by Django 4.2.13 on 2026-03-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('billing', 'Billing'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, help_text='Heroicon name (e.g. "calculator") or emoji', max_length=50)),
                ('external_url', models.URLField(blank=True, help_text='Full URL to the external subject app. null = not yet available.', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_coming_soon', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#16a34a', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, help_text='Optional link to internal classroom.Subject for future use.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.subject')),
            ],
            options={
                'verbose_name': 'Subject App',
                'verbose_name_plural': 'Subject Apps',
                'ordering': ['order', 'name'],
            },
        ),
    ]
