# Generated by Django 4.2.13 on 2026-03-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_contactmessage_subjectapp'),
        ('classroom', '0031_seed_year8_fractions'),
    ]

    operations = [
    ]
