# Generated by Django 4.2.13 on 2026-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0033_classsession_progresscriteria_school_topiclevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteacher',
            name='role',
            field=models.CharField(choices=[('head_of_institute', 'Head of Institute'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Teacher'), ('junior_teacher', 'Junior Teacher')], default='teacher', max_length=20),
        ),
    ]
