# Generated by Django 4.2.13 on 2026-03-08 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0034_rename_hod_to_hoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, help_text='The HoD (Head of Department) user assigned to this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='classroom.school')),
            ],
            options={
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'slug')},
            },
        ),
        migrations.AlterField(
            model_name='schoolteacher',
            name='role',
            field=models.CharField(choices=[('head_of_institute', 'Head of Institute'), ('head_of_department', 'Head of Department'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Teacher'), ('junior_teacher', 'Junior Teacher')], default='teacher', max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this class belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='classroom.department'),
        ),
        migrations.CreateModel(
            name='DepartmentTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_teachers', to='classroom.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'teacher'],
                'unique_together': {('department', 'teacher')},
            },
        ),
    ]
