# Generated by Django 4.2.13 on 2026-03-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0036_studentattendance_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolteacher',
            name='specialty',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
