# Generated by Django 4.2.13 on 2026-03-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0037_schoolteacher_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Link to an existing subject module for pre-built questions. Null = custom subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='classroom.subject'),
        ),
    ]
