# Generated by Django 4.2.13 on 2026-03-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0038_department_subject_and_question_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
