# Generated by Django 4.2.13 on 2026-03-10 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0040_add_school_student_and_level_school_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
