# Generated by Django 4.2.13 on 2026-03-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0041_add_created_by_to_classsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresscriteria',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for top-level criteria; set for sub-criteria.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='classroom.progresscriteria'),
        ),
        migrations.AlterUniqueTogether(
            name='progressrecord',
            unique_together={('student', 'criteria', 'session')},
        ),
    ]
