# Generated by Django 4.2.13 on 2026-03-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0042_progresscriteria_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this level belongs to. Year levels are auto-assigned when a department is created with a subject module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='classroom.department'),
        ),
    ]
