# Generated by Django 4.2.13 on 2026-03-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0043_level_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='department',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED — use DepartmentLevel instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='classroom.department'),
        ),
        migrations.CreateModel(
            name='DepartmentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_display_name', models.CharField(blank=True, help_text='Optional override, e.g. "Year 1 (AU)" to relabel a level for this department.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_levels', to='classroom.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_levels', to='classroom.level')),
            ],
            options={
                'ordering': ['order', 'level__level_number'],
                'unique_together': {('department', 'level')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='mapped_levels',
            field=models.ManyToManyField(blank=True, related_name='mapped_departments', through='classroom.DepartmentLevel', to='classroom.level'),
        ),
    ]
