# Generated by Django 4.2.13 on 2026-03-14 10:48

from django.db import migrations


def forwards(apps, schema_editor):
    """Copy existing Level.department FK data into the new DepartmentLevel M2M table."""
    Level = apps.get_model('classroom', 'Level')
    DepartmentLevel = apps.get_model('classroom', 'DepartmentLevel')
    for level in Level.objects.filter(department__isnull=False):
        DepartmentLevel.objects.get_or_create(
            department=level.department,
            level=level,
            defaults={'order': level.level_number},
        )


def backwards(apps, schema_editor):
    """No-op reverse — DepartmentLevel rows are left in place."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0044_department_level_m2m'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
