# Generated by Django 4.2.13 on 2026-03-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0045_backfill_department_level_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Which subject this level belongs to. Used to filter levels when mapping to departments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='classroom.subject'),
        ),
    ]
