# Generated by Django 4.2.13 on 2026-03-14 10:50

from django.db import migrations


def forwards(apps, schema_editor):
    """Set subject=Mathematics for all Year levels (1-9) and Basic Facts levels (100-199)."""
    Subject = apps.get_model('classroom', 'Subject')
    Level = apps.get_model('classroom', 'Level')

    maths = Subject.objects.filter(slug='mathematics').first()
    if maths:
        # Year levels 1-9 and Basic Facts 100-199 all belong to Mathematics
        Level.objects.filter(
            level_number__lt=200, school__isnull=True, subject__isnull=True,
        ).update(subject=maths)


def backwards(apps, schema_editor):
    Level = apps.get_model('classroom', 'Level')
    Level.objects.filter(level_number__lt=200).update(subject=None)


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0046_level_subject_fk'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
