# Generated by Django 4.2.13 on 2026-03-16 08:46
# Step 1: Create DepartmentSubject model + M2M field (keep old subject FK for data migration)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0049_subject_school_global_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_subjects', to='classroom.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_subjects', to='classroom.subject')),
            ],
            options={
                'ordering': ['order', 'subject__name'],
                'unique_together': {('department', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='departments_m2m', through='classroom.DepartmentSubject', to='classroom.subject'),
        ),
    ]
