# Generated by Django 4.2.13 on 2026-03-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0052_remove_department_subject_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='fee_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee override for this class. NULL = inherit from level/subject/department.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='fee_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual fee override for this student. NULL = inherit from class cascade.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='default_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default fee (NZD) for all subjects/levels/classes in this department.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='departmentlevel',
            name='fee_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee override for this level. NULL = inherit from subject or department.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='departmentsubject',
            name='fee_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee override for this subject. NULL = inherit from department.', max_digits=8, null=True),
        ),
    ]
