# Generated by Django 4.2.13 on 2026-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0055_csvimport_invoice_studentfeeoverride_invoicepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_bsb',
            field=models.CharField(blank=True, max_length=20, verbose_name='BSB'),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='invoice_due_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days after issue date before payment is due.'),
        ),
        migrations.AddField(
            model_name='school',
            name='invoice_terms',
            field=models.TextField(blank=True, help_text='Terms & conditions shown on invoices.'),
        ),
    ]
