# Generated by Django 4.2.13 on 2026-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0056_invoice_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outstanding amount from before the system. Consumed on first invoice.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(choices=[('overpayment', 'Overpayment'), ('invoice_cancelled', 'Invoice Cancelled'), ('applied_to_invoice', 'Applied to Invoice'), ('opening_balance', 'Opening Balance Credit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='rate_source',
            field=models.CharField(choices=[('student_override', 'Student Override'), ('department_default', 'Department Default'), ('opening_balance', 'Opening Balance')], max_length=20),
        ),
    ]
