# Generated by Django 4.2.13 on 2026-03-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0058_salary_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=20),
        ),
    ]
