# Generated by Django 4.2.13 on 2026-03-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0060_parent_models'),
        ('classroom', '0060_school_suspension'),
    ]

    operations = [
    ]
