# Generated by Django 4.2.13 on 2026-03-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0061_merge_0060_parent_models_0060_school_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abn',
            field=models.CharField(blank=True, max_length=50, verbose_name='ABN / Tax ID'),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='state_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
