# Generated by Django 4.2.13 on 2026-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0063_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='student_id_code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated student ID (e.g. STU-001-0042). Used for parent linking.', max_length=20),
        ),
    ]
