# Generated by Django 4.2.13 on 2026-03-24 06:26

from django.db import migrations


def backfill_student_ids(apps, schema_editor):
    """Generate student_id_code for all existing SchoolStudent records."""
    SchoolStudent = apps.get_model('classroom', 'SchoolStudent')
    # Group by school and assign sequential IDs
    school_ids = SchoolStudent.objects.values_list('school_id', flat=True).distinct()
    for school_id in school_ids:
        entries = SchoolStudent.objects.filter(
            school_id=school_id, student_id_code='',
        ).order_by('joined_at', 'pk')
        for seq, entry in enumerate(entries, start=1):
            entry.student_id_code = f'STU-{school_id:03d}-{seq:04d}'
            entry.save(update_fields=['student_id_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0064_add_student_id_code'),
    ]

    operations = [
        migrations.RunPython(backfill_student_ids, migrations.RunPython.noop),
    ]
