# Generated by Django 4.2.13 on 2026-03-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0060_guardian_models'),
        ('classroom', '0065_backfill_student_id_codes'),
    ]

    operations = [
    ]
