# Generated by Django 4.2.13 on 2026-03-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0066_merge_20260325_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abn',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business Registration Number'),
        ),
        migrations.AddField(
            model_name='department',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='bank_bsb',
            field=models.CharField(blank=True, max_length=20, verbose_name='BSB'),
        ),
        migrations.AddField(
            model_name='department',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='GST / VAT Number'),
        ),
        migrations.AddField(
            model_name='department',
            name='invoice_due_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='invoice_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, upload_to='department_logos/'),
        ),
        migrations.AddField(
            model_name='department',
            name='outgoing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='department',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='state_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='GST / VAT Number'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='outgoing_email',
            field=models.EmailField(blank=True, help_text='Outgoing email address used for invoices and communications.', max_length=254),
        ),
        migrations.AlterField(
            model_name='school',
            name='abn',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business Registration Number'),
        ),
    ]
