# Generated by Django 4.2.13 on 2026-03-26 10:49

from django.db import migrations, models
from django.utils import timezone


def mark_existing_schools_published(apps, schema_editor):
    """Existing schools should be treated as already published."""
    School = apps.get_model('classroom', 'School')
    School.objects.filter(is_published=False).update(
        is_published=True,
        published_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0067_institute_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the school has been published. Unpublished schools are in setup mode.'),
        ),
        migrations.AddField(
            model_name='school',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolstudent',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When the student was notified about being added to this school.', null=True),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When the teacher was notified about being added to this school.', null=True),
        ),
        migrations.AlterField(
            model_name='schoolteacher',
            name='role',
            field=models.CharField(choices=[('head_of_institute', 'Head of Institute'), ('head_of_department', 'Head of Department'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Teacher'), ('junior_teacher', 'Junior Teacher'), ('accountant', 'Accountant')], default='teacher', max_length=20),
        ),
        migrations.RunPython(
            mark_existing_schools_published,
            migrations.RunPython.noop,
        ),
    ]
