# Generated by Django 4.2.13 on 2026-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0068_school_publish_and_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='pending_password',
            field=models.CharField(blank=True, help_text='Temporary plain-text password stored until publish email is sent, then cleared.', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='pending_password',
            field=models.CharField(blank=True, help_text='Temporary plain-text password stored until publish email is sent, then cleared.', max_length=50),
        ),
    ]
