# Generated by Django 4.2.13 on 2026-03-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0069_pending_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_type',
            field=models.CharField(choices=[('post_term', 'Post-Term'), ('upfront', 'Upfront')], default='post_term', max_length=20),
        ),
    ]
