# Generated by Django 4.2.13 on 2026-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0072_term_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('month', 'Month'), ('term', 'Term'), ('year', 'Year')], default='custom', max_length=10),
        ),
    ]
