# Generated by Django 4.2.13 on 2026-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0072_term_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='default_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default fee (USD) for all subjects/levels/classes in this department.', max_digits=8, null=True),
        ),
    ]
