# Generated by Django 4.2.13 on 2026-04-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0072_term_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('criteria_approval', 'Criteria Approval Request'), ('criteria_approved', 'Criteria Approved'), ('criteria_rejected', 'Criteria Rejected'), ('enrollment_request', 'Enrollment Request'), ('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('attendance', 'Attendance'), ('parent_link_request', 'Parent Link Request'), ('parent_link_approved', 'Parent Link Approved'), ('parent_link_rejected', 'Parent Link Rejected'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='ParentLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_link_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_link_requests', to='classroom.schoolstudent')),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('parent', 'school_student')},
            },
        ),
    ]
