# Generated by Django 4.2.13 on 2026-03-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0071_term_confirmation_and_holiday"),
        ("classroom", "0073_invoice_period_type"),
    ]

    operations = []
