# Generated by Django 4.2.13 on 2026-03-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0074_merge_20260401_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
