# Generated by Django 4.2.13 on 2026-04-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0073_currency_usd'),
        ('classroom', '0076_merge_0074_merge_20260401_0046_0075_delete_holiday'),
    ]

    operations = [
    ]
