# Generated by Django 4.2.13 on 2026-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0077_merge_20260402_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone (e.g. America/New_York, Pacific/Auckland). Used for scheduling and "today" calculations. Falls back to server TIME_ZONE if blank.', max_length=63),
        ),
    ]
