# Generated by Django 4.2.13 on 2026-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0073_classroom_bank_gst_overrides'),
        ('classroom', '0074_seed_currencies'),
        ('classroom', '0078_school_timezone'),
    ]

    operations = [
    ]
