# Generated by Django 4.2.13 on 2026-04-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0074_seed_currencies'),
        ('classroom', '0079_merge_20260404_1707'),
        ('classroom', '0079_merge_bank_gst_overrides'),
    ]

    operations = [
    ]
