# Generated by Django 4.2.13 on 2026-04-04 22:50
#
# Uses RunPython so we can detect the collation of classroom_currency.code
# at migration time and create the FK columns with the same collation.
# This is required because MySQL 8.0 rejects foreign key constraints whose
# columns have different collations.  Production databases may use
# utf8mb4_unicode_ci while a fresh test database uses utf8mb4_0900_ai_ci.

from django.db import migrations, models
import django.db.models.deletion


def _add_currency_fk_columns(apps, schema_editor):
    """Add currency FK columns matching classroom_currency.code's collation."""
    db = schema_editor.connection
    if db.vendor == 'sqlite':
        # SQLite has no charset/collation concept; use normal DDL.
        with db.cursor() as cursor:
            cursor.execute(
                "ALTER TABLE classroom_classroom "
                "ADD COLUMN currency_override_id varchar(3) NULL DEFAULT NULL"
            )
            cursor.execute(
                "ALTER TABLE classroom_department "
                "ADD COLUMN currency_override_id varchar(3) NULL DEFAULT NULL"
            )
            cursor.execute(
                "ALTER TABLE classroom_school "
                "ADD COLUMN default_currency_id varchar(3) NULL DEFAULT NULL"
            )
        return

    # MySQL/MariaDB: read the collation of classroom_currency.code
    with db.cursor() as cursor:
        cursor.execute(
            "SELECT COLLATION_NAME "
            "FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() "
            "  AND TABLE_NAME = 'classroom_currency' "
            "  AND COLUMN_NAME = 'code'"
        )
        row = cursor.fetchone()
    collation = row[0] if row else 'utf8mb4_0900_ai_ci'

    with db.cursor() as cursor:
        cursor.execute(
            f"ALTER TABLE `classroom_classroom` "
            f"ADD COLUMN `currency_override_id` varchar(3) "
            f"    COLLATE {collation} NULL DEFAULT NULL, "
            f"ADD CONSTRAINT `classroom_classroom_currency_override_id_fk` "
            f"    FOREIGN KEY (`currency_override_id`) "
            f"    REFERENCES `classroom_currency` (`code`) "
            f"    ON DELETE SET NULL"
        )
        cursor.execute(
            f"ALTER TABLE `classroom_department` "
            f"ADD COLUMN `currency_override_id` varchar(3) "
            f"    COLLATE {collation} NULL DEFAULT NULL, "
            f"ADD CONSTRAINT `classroom_department_currency_override_id_fk` "
            f"    FOREIGN KEY (`currency_override_id`) "
            f"    REFERENCES `classroom_currency` (`code`) "
            f"    ON DELETE SET NULL"
        )
        cursor.execute(
            f"ALTER TABLE `classroom_school` "
            f"ADD COLUMN `default_currency_id` varchar(3) "
            f"    COLLATE {collation} NULL DEFAULT NULL, "
            f"ADD CONSTRAINT `classroom_school_default_currency_id_fk` "
            f"    FOREIGN KEY (`default_currency_id`) "
            f"    REFERENCES `classroom_currency` (`code`) "
            f"    ON DELETE SET NULL"
        )


def _remove_currency_fk_columns(apps, schema_editor):
    """Reverse: drop the FK columns added by _add_currency_fk_columns."""
    db = schema_editor.connection
    if db.vendor == 'sqlite':
        # SQLite 3.35+ supports DROP COLUMN; older versions do not.
        # For test environments just leave them — the DB is ephemeral.
        return

    with db.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE `classroom_classroom` "
            "DROP FOREIGN KEY `classroom_classroom_currency_override_id_fk`, "
            "DROP COLUMN `currency_override_id`"
        )
        cursor.execute(
            "ALTER TABLE `classroom_department` "
            "DROP FOREIGN KEY `classroom_department_currency_override_id_fk`, "
            "DROP COLUMN `currency_override_id`"
        )
        cursor.execute(
            "ALTER TABLE `classroom_school` "
            "DROP FOREIGN KEY `classroom_school_default_currency_id_fk`, "
            "DROP COLUMN `default_currency_id`"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0079_merge_20260405_0205'),
    ]

    operations = [
        migrations.RunPython(
            _add_currency_fk_columns,
            _remove_currency_fk_columns,
            hints={'target_db': 'default'},
        ),
        # Declare the state changes so Django's ORM knows about the new fields.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='classroom',
                    name='currency_override',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Currency override for this class. Null = inherit from department.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='classes',
                        to='classroom.currency',
                    ),
                ),
                migrations.AddField(
                    model_name='department',
                    name='currency_override',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Currency override for this department. Null = inherit from school.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='departments',
                        to='classroom.currency',
                    ),
                ),
                migrations.AddField(
                    model_name='school',
                    name='default_currency',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Default currency for invoices. Null = USD system default.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='schools',
                        to='classroom.currency',
                    ),
                ),
            ],
            database_operations=[],  # actual DDL done by RunPython above
        ),
    ]
