# Generated by Django 4.2.13 on 2026-04-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0079_merge_20260404_1707'),
        ('classroom', '0080_currency_fk_fields'),
    ]

    operations = [
    ]
