# Generated by Django 4.2.13 on 2026-04-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0079_merge_bank_gst_overrides'),
        ('classroom', '0081_merge_20260405_1231'),
    ]

    operations = [
    ]
