# Generated by Django 4.2.13 on 2026-04-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0080_merge_20260405_1139'),
        ('classroom', '0080_merge_20260405_1708'),
        ('classroom', '0081_merge_20260405_1231'),
    ]

    operations = [
    ]
