# Generated by Django 4.2.13 on 2026-04-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0073_add_parent_link_request_model'),
        ('classroom', '0079_merge_20260405_1031'),
        ('classroom', '0080_merge_20260405_1139'),
        ('classroom', '0082_merge_20260405_1712'),
    ]

    operations = [
    ]
