# Generated by Django 4.2.13 on 2026-04-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0082_merge_20260405_1725'),
        ('classroom', '0083_merge_20260405_1848'),
    ]

    operations = [
    ]
