# Generated by Django 4.2.13 on 2026-04-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0073_stripe_payment_links'),
        ('classroom', '0084_merge_20260405_2014'),
    ]

    operations = [
    ]
