# Generated by Django 4.2.13 on 2026-04-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0079_merge_20260404_1819'),
        ('classroom', '0085_merge_20260406_0843'),
    ]

    operations = [
    ]
