# Generated by Django 4.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0087_nullable_bank_account_gst_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('criteria_approval', 'Criteria Approval Request'),
                    ('criteria_approved', 'Criteria Approved'),
                    ('criteria_rejected', 'Criteria Rejected'),
                    ('enrollment_request', 'Enrollment Request'),
                    ('enrollment_approved', 'Enrollment Approved'),
                    ('enrollment_rejected', 'Enrollment Rejected'),
                    ('attendance', 'Attendance'),
                    ('parent_link_request', 'Parent Link Request'),
                    ('parent_link_approved', 'Parent Link Approved'),
                    ('parent_link_rejected', 'Parent Link Rejected'),
                    ('homework_assigned', 'Homework Assigned'),
                    ('general', 'General'),
                ],
                default='general',
                max_length=30,
            ),
        ),
    ]
