# Generated by Django 5.2.8 on 2026-04-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0086_parentstudent_school_nullable'),
        ('classroom', '0087_add_coding_subject_app'),
    ]

    operations = [
    ]
