# Generated by Django 5.2.8 on 2026-04-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0087_nullable_bank_account_gst_overrides'),
        ('classroom', '0088_merge_20260413_0800'),
    ]

    operations = [
    ]
