# Generated by Django 4.2.13 on 2026-04-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0089_merge_20260413_0936'),
        ('classroom', '0089_merge_notifications_and_school_default_fee'),
    ]

    operations = [
    ]
