# Generated by Django 5.2.8 on 2026-04-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0089_merge_20260413_0936'),
        ('classroom', '0089_merge_notifications_and_school_default_fee'),
    ]

    operations = [
    ]
