# Generated by Django 5.2.8 on 2026-04-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0090_merge_20260416_1654'),
        ('classroom', '0090_merge_20260417_0030'),
    ]

    operations = [
    ]
