# Generated by Django 5.2.8 on 2026-04-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0091_merge_20260417_1200'),
        ('classroom', '0091_merge_20260420_1152'),
    ]

    operations = [
    ]
