# Generated by Django 5.2.8 on 2026-04-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0093_delete_flipzo_subjectapp'),
        ('classroom', '0093_seed_coding_subject'),
    ]

    operations = [
    ]
