# Generated by Django 5.2.8 on 2026-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0094_classstudent_billing_start_date'),
        ('classroom', '0094_merge_20260424_1130'),
    ]

    operations = [
    ]
