# Generated by Django 4.2.13 on 2026-05-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0095_merge_20260429_2301'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['classroom', 'status'], name='classroom_c_classro_96f8db_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['classroom', 'is_active'], name='classroom_c_classro_721799_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['school', 'is_active'], name='classroom_d_school__b0de52_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['classroom', 'status'], name='classroom_e_classro_00f1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'status'], name='classroom_i_school__02a57f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='classroom_n_user_id_e1b9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolstudent',
            index=models.Index(fields=['school', 'is_active'], name='classroom_s_school__500162_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolteacher',
            index=models.Index(fields=['school', 'is_active'], name='classroom_s_school__ed18ad_idx'),
        ),
    ]
