# Generated by Django 5.2.8 on 2026-06-03 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0100_cpp297_expense_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cards', to='classroom.school')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school', 'card_number'],
                'indexes': [models.Index(fields=['card_number'], name='classroom_s_card_nu_e1d696_idx'), models.Index(fields=['school', 'is_claimed'], name='classroom_s_school__d891e9_idx')],
            },
        ),
    ]
