# Generated by Django 4.2.13 on 2026-06-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0103_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='whatsapp_group_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
