# Generated by Django 4.2.13 on 2026-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0104_classroom_whatsapp_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription_discount_code',
            field=models.CharField(blank=True, help_text='Subscription discount code (a billing.DiscountCode) families can use at checkout. When set, it can be included in welcome/resend emails.', max_length=50),
        ),
    ]
