# Generated by Django 4.2.13 on 2026-06-27 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0105_school_subscription_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresscriteria',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Null = applies to all subjects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_criteria', to='classroom.subject'),
        ),
    ]
