# Generated by Django 5.2.8 on 2026-06-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0105_scheduledmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduledmessage',
            new_name='classroom_s_school__f782a3_idx',
            old_name='classroom_s_school__idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledmessage',
            new_name='classroom_s_next_ru_40ff0f_idx',
            old_name='classroom_s_next_ru_idx',
        ),
    ]
