# Generated by Django 4.2.13 on 2026-06-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0101_add_student_card_model'),
        ('classroom', '0105_school_subscription_discount_code'),
    ]

    operations = [
    ]
