# Generated by Django 4.2.13 on 2026-06-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0106_alter_progresscriteria_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressrecord',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('beginning', 'Beginning'), ('developing', 'Developing'), ('confident', 'Confident'), ('advanced', 'Advanced')], default='not_started', max_length=20),
        ),
    ]
