# Generated by Django 4.2.13 on 2026-06-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0101_seed_languages_subject'),
        ('classroom', '0106_merge_20260625_0712'),
    ]

    operations = [
    ]
