# Generated by Django 4.2.13 on 2026-06-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0107_alter_progressrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_reports', to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='include_coding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='include_homework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='include_maths',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='include_rubric',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='summary_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
