# Generated by Django 5.2.8 on 2026-06-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0105_school_subscription_discount_code'),
        ('classroom', '0107_scheduledmessageattachment'),
    ]

    operations = [
    ]
