# Generated by Django 4.2.13 on 2026-06-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0107_merge_20260625_0832'),
        ('classroom', '0108_progressreport_classroom_and_more'),
    ]

    operations = [
    ]
