# Generated by Django 4.2.13 on 2026-07-03 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0108_progressreport_classroom_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progressrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='The class this progress was recorded for. Null = legacy record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='classroom.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='progressrecord',
            unique_together={('student', 'criteria', 'classroom', 'session')},
        ),
    ]
