# Generated by Django 4.2.13 on 2026-07-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0109_alter_progressrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreportcomment',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Class this comment was recorded in (per-class tracking, §12.10). Null = legacy / class-agnostic comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_report_comments', to='classroom.classroom'),
        ),
    ]
