# Generated by Django 4.2.13 on 2026-07-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0109_merge_20260628_2238'),
        ('classroom', '0109_seed_languages_subject'),
    ]

    operations = [
    ]
