# Generated by Django 4.2.13 on 2026-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0111_balancezeroingbatch_invoicepayment_zeroing_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="classstudent",
            name="moved_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set when the student was deactivated here via a Move (not a plain Remove). While set, the student retains homework access to this class. Cleared on re-enrolment or when the student leaves the school.",
                null=True,
            ),
        ),
    ]
