# Generated by Django 4.2.13 on 2026-07-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0112_classstudent_moved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classstudent",
            name="moved_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set when the student left THIS class but is still in the school (a class change / move), so they retain the class’s homework. Stays None for a whole-school removal (which revokes). Cleared on re-enrolment or when the student leaves the school.",
                null=True,
            ),
        ),
    ]
