# Generated by Django 4.2.13 on 2026-08-12 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0113_alter_classstudent_moved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Mark this class as delivered online. Combine with a location for hybrid (mixed) delivery.",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Optional. The street address of this location.",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this location as an online / virtual venue.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        help_text="The institute this location belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="classroom.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="classroom",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Where this class is held. Optional.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="classroom.location",
            ),
        ),
    ]
