# Generated by Django 4.2.13 on 2026-08-13 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0114_classroom_is_online_location_classroom_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional accent colour as a hex value (e.g. #4f46e5). Used to tint this location's class tiles on the Classes page.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a colour as a hex value like #4f46e5.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
            ),
        ),
    ]
