# Generated by Django 4.2.13 on 2026-08-19 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0115_location_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailqueue",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queued_emails",
                to="classroom.invoice",
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queued_emails",
                to="classroom.school",
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["status", "created_at"], name="classroom_e_status_f0a7eb_idx"
            ),
        ),
    ]
