# Generated by Django 4.2.13 on 2026-09-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0110_merge_20260703_2134'),
        ('classroom', '0120_repair_classroom_subject'),
    ]

    operations = [
    ]
