# Generated by Django 4.2.13 on 2026-09-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0121_merge_20260907_2129'),
        ('classroom', '0121_topic_alias'),
    ]

    operations = [
    ]
