# Generated by Django 4.2.13 on 2026-06-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehit',
            name='client_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='pagehit',
            index=models.Index(fields=['created_at', 'user'], name='usage_pageh_created_e98dd6_idx'),
        ),
    ]
