# Generated by Django 5.2.8 on 2026-04-24 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0094_merge_20260424_1130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainBuzzSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='6-character alphanumeric join code (A-Z, 2-9; no 0/O/1/I/L)', max_length=6, unique=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('between', 'Between Questions'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], db_index=True, default='lobby', max_length=20)),
                ('current_index', models.IntegerField(default=0)),
                ('state_version', models.IntegerField(default=0)),
                ('question_deadline', models.DateTimeField(blank=True, null=True)),
                ('time_per_question_sec', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brainbuzz_sessions_hosted', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brainbuzz_sessions', to='classroom.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrainBuzzParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brainbuzz_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='brainbuzz.brainbuzzsession')),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='BrainBuzzSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True / False'), ('short', 'Short Answer'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=20)),
                ('options_json', models.JSONField(blank=True, default=list, help_text='MCQ/TF options: [{"label":"A","text":"...","is_correct":true}]')),
                ('correct_short_answer', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('points_base', models.IntegerField(default=1000)),
                ('source_model', models.CharField(help_text='Source model name (e.g., "CodingExercise", "MathsQuestion")', max_length=100)),
                ('source_id', models.IntegerField(help_text='Source primary key for analytics')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='brainbuzz.brainbuzzsession')),
            ],
            options={
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BrainBuzzAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_label', models.CharField(blank=True, help_text='For MCQ/TF: "A", "B", "C", "D", "T", "F", etc.', max_length=1, null=True)),
                ('short_answer_text', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_ms', models.IntegerField()),
                ('points_awarded', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='brainbuzz.brainbuzzparticipant')),
                ('session_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='brainbuzz.brainbuzzsessionquestion')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brainbuzzsession',
            index=models.Index(fields=['code', 'status'], name='bb_session_code_status_idx'),
        ),
        migrations.AddIndex(
            model_name='brainbuzzsession',
            index=models.Index(fields=['host', 'created_at'], name='bb_session_host_created_idx'),
        ),
        migrations.AddIndex(
            model_name='brainbuzzparticipant',
            index=models.Index(fields=['session', 'nickname'], name='bb_part_session_nick_idx'),
        ),
        migrations.AddConstraint(
            model_name='brainbuzzparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'nickname'), name='unique_session_nickname'),
        ),
        migrations.AddIndex(
            model_name='brainbuzzsessionquestion',
            index=models.Index(fields=['session', 'order'], name='bb_sq_session_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brainbuzzsessionquestion',
            unique_together={('session', 'order')},
        ),
        migrations.AddIndex(
            model_name='brainbuzzanswer',
            index=models.Index(fields=['session_question', 'participant'], name='bb_ans_sq_part_idx'),
        ),
        migrations.AddIndex(
            model_name='brainbuzzanswer',
            index=models.Index(fields=['is_correct'], name='bb_ans_is_correct_idx'),
        ),
        migrations.AddConstraint(
            model_name='brainbuzzanswer',
            constraint=models.UniqueConstraint(fields=('participant', 'session_question'), name='unique_participant_question'),
        ),
    ]
