# Generated by Django 5.2.8 on 2026-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainbuzz', '0002_brainbuzz_reveal_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainbuzzparticipant',
            name='last_correct_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last correct answer (used for tie-breaking in rankings)', null=True),
        ),
    ]
