# Generated by Django 4.2.13 on 2026-05-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainbuzz', '0006_add_quiz_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainbuzzsessionquestion',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Absolute URL of the question image, snapshotted at session creation.', max_length=500),
        ),
        migrations.AlterField(
            model_name='brainbuzzsessionquestion',
            name='options_json',
            field=models.JSONField(blank=True, default=list, help_text='MCQ/TF options: [{"label":"A","text":"...","is_correct":true,"image_url":""}]'),
        ),
    ]
