# Generated by Django 4.2.13 on 2026-05-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainbuzz', '0007_sessionquestion_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainbuzzsessionquestion',
            name='time_limit_sec',
            field=models.IntegerField(default=20),
        ),
    ]
