# Generated by Django 4.2.13 on 2026-05-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainbuzz', '0009_sessionquestion_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainbuzzparticipant',
            name='avatar',
            field=models.CharField(blank=True, default='🦁', max_length=10),
        ),
    ]
