# Generated by Django 4.2.13 on 2026-06-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainbuzz', '0010_alter_brainbuzzparticipant_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainbuzzquizquestion',
            name='answer_format',
            field=models.CharField(choices=[('text', 'Text — exact match (case/space-insensitive)'), ('algebra', 'Algebra — simplified polynomial (e.g. expand & simplify)')], default='text', help_text='How a typed answer is graded. "algebra" = simplified-polynomial match.', max_length=10),
        ),
        migrations.AddField(
            model_name='brainbuzzsessionquestion',
            name='answer_format',
            field=models.CharField(choices=[('text', 'Text — exact match (case/space-insensitive)'), ('algebra', 'Algebra — simplified polynomial (e.g. expand & simplify)')], default='text', help_text='How a typed answer is graded. "algebra" = simplified-polynomial match.', max_length=10),
        ),
    ]
