# Generated by Django 4.2.13 on 2026-05-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetquestion',
            name='content_id',
            field=models.PositiveIntegerField(default=0, help_text='pk of the content row (maths.Question.id, CodingExercise.id, etc.).'),
        ),
        migrations.AddField(
            model_name='worksheetquestion',
            name='subject_slug',
            field=models.CharField(db_index=True, default='mathematics', help_text='Subject plugin slug: mathematics, coding, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='worksheetstudentanswer',
            name='answer_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        # NOTE: unique_worksheet_question_content constraint is added in
        # 0003_backfill_content_id AFTER the data migration sets content_id
        # correctly — adding it here would fail because all existing rows
        # would have content_id=0, violating (worksheet, subject_slug, 0).
    ]
