# Generated by Django 4.2.13 on 2026-05-17 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0027_merge_20260511_1752'),
        ('coding', '0017_merge_20260429_2301'),
        ('worksheets', '0003_backfill_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetquestion',
            name='coding_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_entries', to='coding.codingexercise'),
        ),
        migrations.AlterField(
            model_name='worksheetquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_entries', to='maths.question'),
        ),
    ]
