# Generated by Django 4.2.13 on 2026-05-17 02:56

from django.db import migrations, models
import django.db.models.deletion


def backfill_content_id(apps, schema_editor):
    """Set content_id = question_id for all existing maths student-answer rows.

    Without this, every row gets content_id=0 (the column default), which
    causes a duplicate-key error when the new unique_together constraint on
    (submission, subject_slug, content_id) is applied to a submission that
    already has more than one answer.
    """
    WorksheetStudentAnswer = apps.get_model('worksheets', 'WorksheetStudentAnswer')
    (
        WorksheetStudentAnswer.objects
        .filter(question_id__isnull=False, content_id=0)
        .update(content_id=models.F('question_id'))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0027_merge_20260511_1752'),
        ('coding', '0017_merge_20260429_2301'),
        ('worksheets', '0004_add_coding_exercise_fk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksheetstudentanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='worksheetstudentanswer',
            name='coding_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_student_answers', to='coding.codingexercise'),
        ),
        migrations.AddField(
            model_name='worksheetstudentanswer',
            name='content_id',
            field=models.PositiveIntegerField(default=0, help_text='pk of the content row (maths.Question.id, CodingExercise.id, etc.).'),
        ),
        migrations.AddField(
            model_name='worksheetstudentanswer',
            name='subject_slug',
            field=models.CharField(db_index=True, default='mathematics', max_length=50),
        ),
        migrations.AlterField(
            model_name='worksheetstudentanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_student_answers', to='maths.question'),
        ),
        # Backfill content_id from question_id BEFORE adding the unique constraint.
        # Without this, existing submissions with multiple answers all have
        # content_id=0 and collide on (submission, 'mathematics', 0).
        migrations.RunPython(backfill_content_id, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='worksheetstudentanswer',
            unique_together={('submission', 'subject_slug', 'content_id')},
        ),
    ]
