# Generated by Django 4.2.13 on 2026-06-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0005_add_subject_slug_content_id_to_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetuploadsession',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='worksheetuploadsession',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='worksheets/upload_pdfs/'),
        ),
        migrations.AddField(
            model_name='worksheetuploadsession',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=20),
        ),
    ]
