# Generated by Django 4.2.13 on 2026-08-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0007_worksheetuploadsession_shape_naming"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheetuploadsession",
            name="page_selection",
            field=models.CharField(
                blank=True,
                help_text='Pages to extract, like "2-7, 9". Blank extracts every page.',
                max_length=200,
            ),
        ),
    ]
