# Generated by Django 4.2.13 on 2026-09-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0008_worksheetuploadsession_page_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheetsubmission",
            name="art_picture_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which classroom.progress_art picture this student is drawing as they work through the worksheet. A worksheet session is resumed across days, so the choice is pinned here — how much is drawn is counted from the answers, not stored.",
                max_length=40,
            ),
        ),
    ]
