# Generated by Django 4.2.13 on 2026-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("mem_total", models.PositiveIntegerField(default=0)),
                ("mem_used", models.PositiveIntegerField(default=0)),
                ("mem_avail", models.PositiveIntegerField(default=0)),
                ("swap_total", models.PositiveIntegerField(default=0)),
                ("swap_used", models.PositiveIntegerField(default=0)),
                ("disk_used_pct", models.PositiveSmallIntegerField(default=0)),
                ("load1", models.FloatField(default=0)),
                ("nproc", models.PositiveSmallIntegerField(default=1)),
                ("oom_24h", models.PositiveIntegerField(default=0)),
                ("rq_default", models.IntegerField(blank=True, null=True)),
                ("rq_high", models.IntegerField(blank=True, null=True)),
                ("svc_gunicorn", models.CharField(default="unknown", max_length=12)),
                ("svc_worker", models.CharField(default="unknown", max_length=12)),
                ("svc_redis", models.CharField(default="unknown", max_length=12)),
                ("svc_caddy", models.CharField(default="unknown", max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "OK"), ("warn", "Watch"), ("crit", "Critical")],
                        db_index=True,
                        default="ok",
                        max_length=4,
                    ),
                ),
                ("issues", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="ops_opssnap_created_1d1e07_idx"
                    )
                ],
            },
        ),
    ]
