# Generated by Django 4.2.13 on 2026-07-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opssnapshot",
            name="db_cpu_pct",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opssnapshot",
            name="db_disk_pct",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opssnapshot",
            name="db_mem_pct",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
