# Generated by Django 4.2.13 on 2026-09-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0121_topic_alias"),
        ("ops", "0002_opssnapshot_db_cpu_pct_opssnapshot_db_disk_pct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='The name used in code, e.g. "language".',
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What this turns on, and what to watch while it is in pilot.",
                    ),
                ),
                (
                    "rollout",
                    models.CharField(
                        choices=[
                            ("off", "Off — nobody"),
                            ("pilot", "Pilot — only the schools listed below"),
                            ("on", "On — every school"),
                        ],
                        default="off",
                        help_text="Off is the default and the safe answer: a flag nobody has decided about yet is one nobody should be running.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schools",
                    models.ManyToManyField(
                        blank=True,
                        help_text='Schools this is on for while rollout is "pilot".',
                        related_name="feature_flags",
                        to="classroom.school",
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
    ]
