# Generated by Django 4.2.13 on 2026-04-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['game', 'stage__order', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='level',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='cell_data',
            field=models.JSONField(blank=True, default=dict, help_text='Partial answers saved as {row_col: value}.'),
        ),
        migrations.AlterField(
            model_name='level',
            name='answers',
            field=models.JSONField(help_text='Expected answers keyed by direction and clue number.'),
        ),
        migrations.AlterField(
            model_name='level',
            name='clues',
            field=models.JSONField(help_text='Across and down clues with position and length.'),
        ),
        migrations.AlterField(
            model_name='level',
            name='grid_data',
            field=models.JSONField(help_text='Grid layout: rows, cols, blocked cells, clue numbers.'),
        ),
        migrations.AlterField(
            model_name='level',
            name='passage',
            field=models.TextField(blank=True, help_text='Optional reading passage (science crosswords).', null=True),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('theme', models.CharField(choices=[('forest', 'Enchanted Forest'), ('ocean', 'Deep Ocean'), ('space', 'Outer Space'), ('volcano', 'Lava Land'), ('crystal', 'Crystal Cave')], default='forest', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='games.game')),
            ],
            options={
                'ordering': ['game', 'order'],
                'unique_together': {('game', 'order')},
            },
        ),
        migrations.AddField(
            model_name='level',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='games.stage'),
        ),
    ]
